### ISSUE TITLE
écriture manuscrite : raccourci clavier alt pour mode ligne horizontal / vertical => alt + tab

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#100]
Petite remarque : lorsque l'on est en mode manuscrite et que l'on fait alt+tab pour changer de fenêtre, cela à tendance à activer le mode ligne horizontal / vertical. Peut être essayer de trouver un moyen de ne pas activer ce changement d'outil si la touche alt fait partie d'une combinaison ?

**Comment by ClementGre** [comment]
Je note ça, le problème ne sera plus là pour la version 1.3.0 finale.
Merci.

**Comment by ClementGre** [comment]
Il aurais été trop compliqué de détecter quand-est-ce que Alt est pressé avec TAB (car ce sont deux évènements différents et le TAB est géré au niveau système).
J'ai donc mis la touche M à la place de TAB pour activer/désactiver le mode ligne horizontale/verticale.

Merci.
