### ISSUE TITLE
problème avec l'utilisation d'une tablette graphique

### ISSUE THREAD

**Issue by asdebled** [ClementGre/PDF4Teachers#103]
Bonjour, 
tout d'abord merci pour cette nouvelle version géniale qui permet d'intégrer des dessins. PDFTeachers répond maintenant à tous mes besoins et plus encore !
Il me reste cependant un problème. Je corrige habituellement mes copies en m'aidant d'une tablette graphique car dans ma matière j'ai beaucoup de schémas à main levée à faire. J'utilise une tablette graphique Wacom Intuos avec son stylet. Malheureusement, alors que je n'ai pas de problème pour dessiner avec la souris, je ne peux pas dessiner avec ma tablette : le pdf défile en même temps que j'écris et le trait suit alors un trajet totalement déformé. 
Je précise que je n'ai aucun problème d'utilisation de ma tablette avec d'autres logiciels.
Est-ce que vous pourriez m'aider à résoudre ce problème s'il vous plaît ?

**Comment by ClementGre** [comment]
Bonjour,
ceci est dû à la configuration de la tablette, qui défile lors du dessin.
J'ai pu le résoudre de mon côté en désactivant l'utilisation de Windows Ink dans les paramètres de l'application Wacom. C'est une coche à décocher (je ne peut pas vous dire exactement où).

J'espère que vous réussirez à résoudre votre problème.
\- Clément Grennerat

**Comment by asdebled** [comment]
Un grand merci pour votre réponse. Cela fonctionne parfaitement !
Merci encore ce logiciel qui va assurément beaucoup me servir à l'avenir.
