### ISSUE TITLE
Pc utilisé avec pdf4teachers

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#104]
Bonjour,
Je pose ma question ici car je ne sais pas quel canal utiliser pour cette demande. Quel équipement pc, tablette reliée au pc, tablette graphique utilisez-vous avec pdf4teachers? Je suis entrain de renouveler mon équipement et je suis un peu perdu. Pour mes autres utilisations il me faut un pc avec:
* windows 10 pro
* 16 à 32 G de mémoires
* processeur ryzen 9 amd ou core i9 intel
* une caméra
* un clavier numérique
* 15 pouces
Pour pdf4teachers il me faudrait un écran avec stylet en plus mais je ne trouve pas de modèle satisfaisant, notamment un écran complètement retournable (360°). Avez-vous des recommandations à ce sujet?
Ou utilisez-vous un pc plus une tablette à stylet relié à votre pc? Ou un écran graphique à stylet?
Merci pour vos retours.

**Comment by grensv** [comment]
Bonjour mw,Nous avons à la base pensé PDF4teachers pour une utilisation optimale principalement au clavier. Depuis la version 1.3 il est possible de saisir des dessins, et les tablettes graphiques y trouvent donc un intérêt, bien que pour le moment le retour d'expérience des collègues utilisateurs reste limité sur l'usage des stylets / tablettes. Nous avons fait les tests avec une Wacom de base et avons quelques retours aussi avec d'autres modèles.La configuration PC dont vous parlez sera largement suffisante. A noter que plus l'écran est grand, plus la correction est efficace (pour pouvoir afficher le maximum d'éléments déjà saisis).Vincent.Le 4 août 2021 01:03, mw ***@***.***> a écrit :

Bonjour,

Je pose ma question ici car je ne sais pas quel canal utiliser pour cette demande. Quel équipement pc, tablette reliée au pc, tablette graphique utilisez-vous avec pdf4teachers? Je suis entrain de renouveler mon équipement et je suis un peu perdu. Pour mes autres utilisations il me faut un pc avec:

windows 10 pro16 à 32 G de mémoiresprocesseur ryzen 9 amd ou core i9 intelune caméraun clavier numérique15 pouces

Pour pdf4teachers il me faudrait un écran avec stylet en plus mais je ne trouve pas de modèle satisfaisant, notamment un écran complètement retournable (360°). Avez-vous des recommandations à ce sujet?

Ou utilisez-vous un pc plus une tablette à stylet relié à votre pc? Ou un écran graphique à stylet?

Merci pour vos retours.

**Comment by ClementGre** [comment]
Je ferme ainsi cette Issue.
