### ISSUE TITLE
Modification de l'association pour les fichiers pdf sous linux

### ISSUE THREAD

**Issue by pi3141** [ClementGre/PDF4Teachers#105]
Sous debian 10, après installation, les fichiers pdf sont associés avec le logiciel pdf4teachers sans demander l'avis de l'utilisateur.
En plus de cela, le type mime des pdf semble modifié. Thunar m'indique que mes fichiers pdf sont de type : "PDF4Teachers PDF file format". Même en rétablissant l'association avec ma visionneuse pdf pour thunar, certaines applications (telegram par exemple) continuent d'ouvrir les pdf avec PDF4Teachers.

**Comment by ClementGre** [comment]
Bonjour, 

Le type "PDF4Teachers PDF file format" a bien été corrigé en "Portable Document Format" pour la prochaine version.

PDF4Teachers définit ses associations de fichiers par le biais de JPackage, qui permet de créer le .deb, .dmg et .exe.
Je n'ai que très peu de contrôle là dessus, et celà relèverait peut-être d'un bug de Java. Sous Kubuntu 20.04, je n'ai pas ce problème, mon visioneur PDF est bien resté l'application par défaut pour les PDF.

Un moyen de vous débarasser de ce problème serait de désinstaller PDF4Teachers, puis de le réinstaller avec la version .tar.gz, qui n'enregistre pas les associations dans le système.

Je ferme donc cette issue.
Merci à vous, Clément G.
