### ISSUE TITLE
Retournement image

### ISSUE THREAD

**Issue by BrigitteAlain** [ClementGre/PDF4Teachers#107]
Bonjour,
la réorientation des images ne s'enregistre pas

![image](https://user-images.githubusercontent.com/91541068/135084402-547fc400-f276-45f3-835f-01bf50080836.png)

**Comment by ClementGre** [comment]
Bonjour @BrigitteAlain,
j'imagine que vous parlez d'un problème d'orientation lors de la conversion image/pdf ?

Normalement, l'orientation des images est bien prise en compte lors de l'ajout d'éléments "image".

Je vais essayer de régler ce problème pour la prochaine version.
En attendant, vous pouvez réorienter les pages avec le menu en haut à droite des pages, ou au trackpad.

Merci à vous,
Clément G.

**Comment by ClementGre** [comment]
Bonjour,
ce problème a été résolu. Les données EXIF de rotation des images sont maintenant prises en compte lors de la conversion Images => PDF.

Merci à vous,
Clément G.
