### ISSUE TITLE
Implementation d'un système de note par compétences

### ISSUE THREAD

**Issue by pierretravers** [ClementGre/PDF4Teachers#11]
Il pourrait être très intéressant de pouvoir ajouter à la copie de l'élève un deuxième pdf (en page n+1 ou en page 0 par exemple) une notation faite d'une grille préparée en amont par l'enseignant (au format pdf j'imagine que c'est plus simple) et dans laquelle il aura donné un barème (ou une grille de compétences) cochée par le prof directement dans le soft.
Encore merci, bravo et bon courage ;-)

**Comment by themsou** [comment]
Bonjour,

si j'ai bien compris, vous souhaitez fusionner des fichiers PDF. Je garde cette issue ouverte pour y penser lors du développement de la prochaine mise à jour "MINOR" (1.2.0).

Le système de notes a déjà été développé, il va sortir avec la version 1.1.0 dans quelques jours. Vous pourrez saisir votre barème dans l'application, rentrer les notes sur chaque copies puis exporter vos notes dans un tableau CSV. Il n'y a pas d'implémentation pour les compétences, vous devrez créer une note par compétence sur 4 par exemple.

Cordialement, Clément G.

**Comment by grensv** [comment]
Je pense qu'avec les évolutions actuelles de l'évaluation, la fonctionnalité de grille de compétences doit être réfléchie.
Pierre, l'outil de notation / barème, que je teste en ce moment, va en gros permettre d'associer chaque question (à travers son numéro ou nom) à une note sur un barème libre. L'outil fait ensuite la somme, à travers une approche hiérarchique (on peut choisir d'afficher les sommes intermédiaires des groupes de questions, ou pas, idem pour le total).
L'outil notation permet ensuite d'exporter les détails de notation de chaque copie en un fichier .csv
Pour les compétences, Clément propose d'utiliser ceci en détaillant chaque compétence, par exemple sur 4. Ce qui soulève les questions suivantes:
- sommes nous OK pour évaluer une compétence sur une note chiffrée, alors que une part de la démarche compétences a été de supprimer la notation chiffrée ? Dans ce cas, il faudrait un outil parallèle, qui permette les classiques point vert/jaune/orange/rouge...
- Souhaite-t-on pouvoir en parallèle effectuer une notation chiffrée **et** une évaluation de compétences ? Idem, dans ce cas il faudrait un outil parallèle.

Vincent.

**Comment by pierretravers** [comment]
Je me permets qques remarques que j'espère "bienveillantes et constructives" ;-) :

- La philosophie qui sous-tend l'éval par compétence suppose que la notation (=taux de réussite objectivé à un exercice) est indépendante de l'acquisition et de la maîtrise de compétences (qui sont plus transversales et sans doute moins faciles à objectiver dans leur niveau de maîtrise). Est-il dès lors bien utile/pertinent  de lier les deux systématiquement ? (je rejoins donc la remarque de Vincent)
-Il est sans doute beaucoup plus simple et ouvert de laisser à l'enseignant le soin de définir lui même les compétences qu'il veut évaluer sur chaque paquet de copie (si on pousse, on peut même penser qu'en cas de différenciation, il souhaite le faire pour chaque copie, mais ça ne facilite pas le boulot) 
      *soit par l'intégration (comme je l'ai suggéré)d'une grille ajoutée à la copie, 
      *soit par l'intégration de ces compétences sous la forme de commentaires avec le module déjà présent (on peut imaginer une nouvelle catégorie d'éléments "compétences" sauvegardées à la manière des favoris)

- Dans tous les cas, les deux types d'éval ne me paraissent pas être inconciliables (au contraire, elles peuvent se compléter) et sont sans doute réalisables en l'état actuel du soft (mais demande un peu d'imagination et de courage au prof pour ajouter tout ça à la mano).

En tout cas encore merci pour ce beau logiciel ainsi que pour avoir pris le temps de me lire et de me répondre.

**Comment by grensv** [comment]
Pierre,

Avec Clément, nous sommes très contents que PDF4Teachers prenne son envol, et c'est grâce à des débats comme celui-ci que l'on pourra le faire évoluer dans la bonne direction. Merci donc pour ces contributions. 
Pour ce qui est des fonctionnalités liées aux compétences, on se projette sur la version N+2, mais bien anticiper évitera de perdre du temps au codage.
Mon idée (dans le prolongement de mes premières idées qui ont mené à la création de PDF4Teachers et à son développement logiciel par Clément) est de faire quelque chose de très efficace. Je suis prof en IUT, et l'évaluation par compétences n'y était pour le moment présente que selon la volonté des enseignants (c'est en train de changer, nous réécrivons en ce moment les diplômes en compétences).
Je pense que selon les situations pédagogiques, certains collègues souhaiterons :
- notation chiffrée uniquement
- évaluation de compétences uniquement
- combinaison des 2, comme tu le suggères au 2ème point
J'aimerais donc bien quelque chose qui permette ces 3 possibilités, toujours de manière très efficace (donc génération de la grille automatiquement, etc...)
En attendant on va bricoler avec ce qu'on a, mais je verrais bien un outil supplémentaire, qui puisse relier ce qui apparaitra dans la grille aux différentes questions/exercices (et donc peut-être à la notation) : il me semble intéressant pour l'élève de pouvoir lier la compétence évaluée à l'exercice qu'il a mal réussi, et ce serait plus efficace / pertinent pour le prof à la saisie.

**Comment by MatQ07** [comment]
Bonjour,
Avec la version actuelle, j'arrive à faire une notation "traditionnelle" avec la fameuse note sur 20 en parallèle à une notation par compétences (chiffrée i.e. 1, 2, 3, 4) **totalement décorrélées** (c'est le fondement de la notation par compétences, dans les cas extrèmes, on devrait pouvoir avoir 20/20 sans valider toutes les compétences ou 0/20 en les validant toutes). Je pense que le développeur aurait des chances de pouvoir l'intégrer facilement (mais n'étant pas moi-même dévelopepur, je prends des pincettes).

**Situation actuelle :** 
- Pour le moment, je crée une sous-note de "Total" qui s'appelle "note" et une autre qui s'appelle "compétences.
- Sur la copie de l'élève, je met la note "Total" en blanc taille 6 dans un coin blanc pour la rendre invisible.
- C'est "note" qui fait ma note sur 20 et chaque item de compétence est reporté dans un tableau en en-tête de mon devoir qui les récapitule.
- Le seul hic vient du fait que j'ai quand-même la somme de mes notations de compétences chiffrées qui s'affiche et que ça ne veut rien dire. Les élèves semblent y attacher une importance d'autant plus grande que je leur dit que ça n'en a pas ...

**Pistes pour améliorer la situation :**
Que les choses soient claires, je n'ai pas la prétention de dire que cette méthode est la meilleure, mais en l'occurence, elle a le mérite de me permettre de gérer des notes et des compétences indépendamment l'une de l'autre, je propose donc de creuser un peu.
- Peut-on rajouter une option "cacher/montrer" à un élément du barème (qui serait accessible par un clic droit dans le récapitulatif des éléments de la colonne de gauche) sans que cela n'impacte tous les éléments du même niveau ?
- Peut-on avoir plusieurs éléments de départ ?

**Améliorations supplémentaires :**
Dans le cas ou Clement arriverait à mettre en oeuvre un barème avec un élément de départ "note" et un élément de départ "compétences" par exemple, il y a une spécificité quand à l'usage des compétences qui varie d'un enseignant à l'autre. Certains ne jurent que par une moyenne de chaque élément évalué correspondant à la même compétence (j'évalue la compétence A à 3 reprises dans le devoir que je propose, l'élève a vert, jaune et rouge, la moyenne sera de jaune ce qui correpondra au niveau de validation final de la compétence dans mon devoir) et d'autres qui considèrent que le niveau de validation finale de la compétence A dans mon devoir sera le meilleur résultat que l'élève aura obtenu lors des 3 fois où il aura eu à l'exercer (de mon interprétation, c'est plus l'esprit dans lequel les compétences ont été introduites, mais je sais que des collègues fonctionnent d'une manière ou d'une autre selon leur préférence et je trouve ça bien). L'histoire des codes couleur n'est qu'esthétique, les compétences peuvent être traitées en termes chiffrés (j'ai vu des solutions de notation qui les évaluaient en %age et qui permettaient à l'utilisateur de déterminer la couleur de son point en fonction de plages qu'il avait sélectionnées mais ça me paraît lourd pour une prochaine version.
Merci en tous cas à Vincent pour son super boulot !

**Comment by grensv** [comment]
Bonjour,
Tout d'abord, MatQ07 je rectifie, c'est Clément qu'il faut remercier pour son super boulot : je n'ai que eu l'idée de base, et j'aide Clément à faire évoluer PDF4Teachers sur le plan conceptuel uniquement. C'est lui qui a tout le mérite du codage.

Pour une prochaine version majeure, en faisant la synthèse de ce que je comprends des besoins exprimés (je n'ai pas de recul en éval par compétences, en IUT on s'y met tout juste, et encore on traine des pieds), j'aurais tendance à proposer un système parallèle à celui du barème (pas mal de copier-coller au niveau code), mais avec des différences cependant : 
   * pas de hiérarchie entre les compétences
   * pas de somme entre des compétences différentes
   * évaluation chiffrée de la compétence, proposé par défaut sur 4? (non acquis, en voie d'acquisition, presque acquis....),  mais libre à l'enseignant de changer sur 100 si il préfère un pourcentage, ou autre valeur chiffrée.
   * pas d'auto-proposition de la compétence suivante puisqu'il n'y a plus de hiérarchie
   * possibilité d'évaluer plusieurs fois la même compétence : là on garde un système d'auto-calcul, avec plusieurs options : moyenne des évaluations de cette même compétence, min, max, autre ? Ce choix est commun à l'ensemble des compétences et se règle dans les paramètres de l'éval par compétence.
   * au lieu d'afficher le Total, affichage d'un petit tableau avec la liste des compétences et leur résultat d'évaluation (avec au choix soit affichage chiffré tel que saisi dans la copie, soit système de couleur dont la correspondance avec les chiffres est choisie dans les préférences, avec pour chaque couleur les intervalles chiffrés correspondants - Mais alors question : combien de couleurs ??? Si à la base le système préconisé est plutôt 3 couleurs rouge-jaune-vert, j'ai vu des enseignants de primaire passer à "l'arc en ciel", avec du orange, du vert clair, vert foncé...
   * pour les inconditionnels des couleurs (je comprends bien la volonté d'éviter l'évaluation chiffrée qui est perçue par l'enfant comme une reproduction de la note), peut-être faut-il proposer un réglage d'affichage en chiffré ou en couleur : en mode couleur, sur la copie, chaque chiffre saisi est immédiatement converti en une pastille de couleur, selon les mêmes règles que définies pour le tableau récapitulatif.

Comme d'habitude, nous sommes preneurs du maximum de retour sur ces propositions, afin que la version qui intègrera ceci soit conçue au plus proche des besoins.
Vincent.

**Comment by ClementGre** [comment]
En effet, la méthode la plus simple pour sortir quelque chose de "propre" serait d'ajouter un onglet offrant à peut près les mêmes fonctionnalités que celui des notes. Il serait alors très facile d'implémenter un sytème permettant de personnaliser les compétences (Couleurs, Lettres, Chiffres, Texte) et le Total (Aucun, Couleur, Lettre, Pourcentage, Note ou Texte). Il serait alors simple de proposer la génération d'un tableau simple, d'un tableau avec un commentaire sur chaque niveau d'une compétence, ou simplement une liste des compétences.

Mais ce serait effectivement assez long à développer : Ajout d'un nouveau type d'éléments, nouvelle interface graphique et exportation des compétences dans un tableau CSV. Il pourrait aussi être possible d'intégrer l'export des compétences avec celui des notes ce qui permettrait d'exporter les deux à a fois.

La question qui se pose est alors : est ce qu'il est plus important pour les utilisateurs de PDF4Teachers d'avoir la mise à jour permettant d'ajouter des images et formes vectorielles/dessin à main levé en premier, ou alors le système de notes par cmpétences ?

\- Clément G.

**Comment by grensv** [comment]
Clément pose une bonne question quand aux priorités à donner : bien que je n'en voit pas personnellement l'intérêt, beaucoup d'utilisateurs potentiels de PDF4Teachers ne s'y intéressent pas car il n'y a pas de fonctions de dessin. L'essence de PDF4Teachers est de saisir le minimum de choses, et re-réutiliser au maximum ce qui a déjà été saisi, et les dessins rentrent à mon avis moins dans cette optique que les annotations texte / Latex. Mais si ça peut faire venir des collègues à PDF4Teachers...
Vincent.

**Comment by MatQ07** [comment]
Oui, alors très clairement, plus j'y réfléchis et plus je trouve cette histoire de dessin assez gadget (et pourtant j’ai une tablette graphique !!!). Si c’est pour faire numériquement la même chose que l'on faisait sur papier, ça n'a qu'un intérêt limité. Mais si ça permet à plus de collègues de s'approprier l'outil et faire des remontées, j'ai envie de dire banco !
Il y a quand-même une chose qui me semble bien avec la fonction dessin, c'est pour commenter l'orthographe. Je remarque que, selon les matières (et probablement leur aisance ortho-gramaticale personnelle), les collègues seront plus ou moins intéressés par la possibilité de signaler leur exaspération relative à l'usage du participe passé et de l'infinitif … Actuellement, je me contente d'un laconique "attention à l'orthographe" en commentaire de chaque petit paragraphe (c'est propre à ma matière, en sciences, on ne demande pas un paragraphe argumenté ou une dissertation comme dans d'autres) car je n'ai pas trouvé de moyen pratique de barrer une faute et de la commenter dans PDF4Teachers (et en ce qui me concerne, une fonction surligner serait idéale).
Après, la fonction dessin permettrait probablement de répondre à l'urgence d'un reconfinement de certains établissements en permettant à chacun de conserver ses habitudes papier, mais l'intérêt de PDF4Teachers est aussi de proposer un mode de fonctionnement très efficace qui est impossible sur papier. Je ne suis pas convaincu qu'une communauté se créerait par la simple grâce de cette fonctionnalité car, si c'est réduire le soft à écrire sur un pdf comme on écrirait sur du papier, les gens retourneront vite au papier ...
Bref, entre la tentation d'attirer du monde pour grossir la communauté et la crainte de les voir en partir rapidement du fait d'une fonctionnalité n'apportant finalement pas grand-chose, il y a en effet un dilemme.  Après, l'EN a quand-même des référents numériques (j'en suis) qui promeuvent ce genre d'outils dans leurs établissements respectifs et sont capables de justifier les intérêts techniques auprès de leurs collègues. J'ai prévu de faire une formation (ou une vidéo) montrant l'efficacité du système.
PS, désolé de ne pas être programmeur, je vous aurais très volontiers aidés, mais là, à part une sorte de "retour client", je ne sais pas trop à quoi je peux servir
PPS, oui, j'avais bien compris que Clément était le créateur de ce super outil, big up à lui !!!

**Comment by ClementGre** [comment]
Oui, en fait la fonction de dessin permettra surtout d'ajouter des images. Les dessins vectoriels permettront principalement de mettre à disposition des icônes/formes sous forme vectorielle et non sous forme d'images. Il sera aussi possible de créer des formes vectorielle à la souris ou en entrant le "path" dans un champ texte.

Je pense qu'il est envisageable de faire un sondage sur Twitter pour voir à peut près ce que veut la communauté en premier.

\- Clément

**Comment by l-leroux** [comment]
Bonjour,
concernant l'évaluation par compétence, un des outils les plus utilisés dans l'EN, gratuit et open-source, et hébergé par plusieurs académies, est [SACoche](https://sacoche.sesamath.net/).
Il peut fournir des fichiers csv qui ressemblent à çà (cf PJ) qu'il peut ensuite réimporter pour de la saisie déportée. Ce fichier contient la liste des codages supportés, et plus ou moins de lignes et de colonnes suivant le nombre des élèves et des compétences utilisées.
L'idéal me semble-t-il serait de pouvoir importer un tel csv, et cocher/saisir pour chaque copie le niveau atteint dans chaque compétence. Ces compétences ne sont pas liées (en tout cas, pas toujours) à un exercice en particulier, et avoir cette liste dans une palette flottante ou un menu latéral, toujours à disposition, pourrait être très pratique. Pour ceux qui utilisent Sacoche, pas besoin ensuite d'intégrer les notes (car l'évaluation par compétences, contrairemetn à ce qu'on entend parfois, c'est TOUJOURS une évaluation avec des notes, seulement ces notes peuvent être chiffrées ou remplacées par des couleurs, peu importe, l'important est qu'elles ne soient pas affectées à des questions mais transversales à des compétences...) elles seront disponible directement dans l'application Sacoche. Il "suffirait" de pouvoir fournir le csv rempli en sortie.
Pour ceux qui ne l'utilisent pas, si pdf4teachers pouvait ajouter à la fin ou au début de la copie une page avec le tableau, ce serait parfait.
Merci pour cet outil dèjà très pratique !
[saisie_deportee_vierge_61_3ga_cahiers_2020-10-30_11h23min47s_i6lv07xgeymhtyd.csv.zip](https://github.com/ClementGre/PDF4Teachers/files/5464479/saisie_deportee_vierge_61_3ga_cahiers_2020-10-30_11h23min47s_i6lv07xgeymhtyd.csv.zip)

**Comment by l-leroux** [comment]
> Il y a quand-même une chose qui me semble bien avec la fonction dessin, c'est pour commenter l'orthographe. Je remarque que, selon les matières (et probablement leur aisance ortho-gramaticale personnelle), les collègues seront plus ou moins intéressés par la possibilité de signaler leur exaspération relative à l'usage du participe passé et de l'infinitif … 

Se mettre en favori un "/" en rouge gros ? ou un "_" idem ?

**Comment by grensv** [comment]
Bonjour,
J'aimerais avancer sur cet aspect ajout d'une grille compétences dans PDF4Teachers, pour la prochaine version majeure je pense. Ne connaissant pas SACoche, j'ai regardé un peu, et effectivement la solution d'un import/export .csv compatible SACoche semble intéressant, que le prof utilise SACoche ou pas.
I-Leroux, serait-ce possible dans les 2 semaines à venir qu'on se fasse une petite visio de 30min à 1H là dessus  ?
Vincent.

**Comment by l-leroux** [comment]
Bonjour, 
oui, on peut poursuivre sur https://sebsauvage.net/paste/?c643dac1f482f93f#qqrquafuInNGqomlyhPIw6/Yy0xZaXfylBJdMmxQemA=
Cordialement,

**Comment by grensv** [comment]
Désolé, avec le décalage horaire, je n’étais plus dispo. Le mieux serait qu’on se place un rendez-vous en conversation privée, et donc se contacter directement par mail. Mon mail est visible sur mon profil git-hub. Donnez moi dans un mail direct vos dispos dans les jours à venir, après 16H.

Merci,
Vincent.

**Comment by l-leroux** [comment]
Bonjour,
je vois que cette amélioration a vu son statut changé récemment : avez vous une idée de la façon et du tempo avec lesquels il sera possible de l'intégrer ?
Merci dans tous les cas !

**Comment by ClementGre** [comment]
En effet, la prochaine version devrait intégrer le système de notation par compétences :
- Un nouvel onglet en cours de développement, qui listera les compétences créées, qu'on pourra noter. 
![image](https://user-images.githubusercontent.com/51322714/169684832-16e3bad4-d2a4-41be-8eae-b2b9ec0c3720.png)
- Il y aura une fenêtre permettant de créer ces compétences et de régler les paramètres liées à la notation (lettres, chiffres, couleurs, options...), qui sera peut-être commune à toutes les éditions.
- Possibilité d'importer les paramètres depuis un CSV SACoche et de ré-exporter ce CSV remplis.
- Exportation csv classique et copie du "barème"/des paramètres sur les pdf du même dossier et de la liste.
- Ajout d'un élément "Grille" qui affichera les résultats sur la copie.

Il s'agit d'une fonctionnalité majeure, qui ne sera pas disponible avant la fin de l'année scolaire (je viens à peine de commencer). Il y a des chances qu'elle sorte cet été.
Merci pour votre soutien !

**Comment by l-leroux** [comment]
Super !
Bon courage et si vous avez besoin de tests supplémentaires, par exemple pour la liaison avec Sacoche, n'hésitez pas à me contacter !

**Comment by ClementGre** [comment]
Oui, j'ai installé un serveur SACoche en local pour pouvoir vérifier que l'intégration fonctionne bien !
L'exportation des icônes en base64 fonctionne parfaitement.

**Comment by ClementGre** [comment]
Plutôt que de fonctionner avec un système d'exportation des compétences comme pour les notes, le système de compétences fonctionnera par devoirs que l'on pourra créer et paramétrer indépendamment des éditions :

<p float="left">
  <img src="https://user-images.githubusercontent.com/51322714/173194431-c81905aa-a745-4bfd-8a96-ce893488d902.png" width="49%" />
  <img src="https://user-images.githubusercontent.com/51322714/173194456-7918acc2-2fbd-44cc-9cee-c960ff05fd99.png" width="49%" />
</p>

Il sera par la suite possible de choisir à quel devoir associer ce document, dans l'onglet compétences :

<img src="https://user-images.githubusercontent.com/51322714/173194645-0b58edd4-43f3-4589-94ac-d1cec2603419.png" width="250" />

Lors de l'import SACoche, il faudra aussi choisir le nom de l'élève auquel la copie doit être associée.

**Comment by l-leroux** [comment]
Miam !
Juste une remarque de forme pas grave : je ne suis pas emballé par l'icône "A" pour l'évaluation par compétences...
Deux idées : 
- EPC (peut-être à la TeX avec un petit p)
- ou une icône type barre de réseau téléphone, pour voir les différents paliers ?
- ou...?

**Comment by l-leroux** [comment]
C'est mieux !
Je pensais à qqch omme çà (sans les axes qui ici n'apportent pas grand chose) : 
![image](https://user-images.githubusercontent.com/73694741/173875563-a11ab9e3-44fe-40f2-ba17-861212d8bab5.png)
mais on va pas chipoter :-)
Ce qui m'étonne c'est que l'onglet soit en première position ? çà ne me semble pas très logique. Je l'aurais plutôt vu entre /20 et T.

**Comment by ClementGre** [comment]
Je peux te proposer cet icône là :

![image](https://user-images.githubusercontent.com/51322714/174047861-501e8dfa-e135-46f2-b068-f13735855061.png)


Pour l'ordre, en fait, il est personalisable par l'utilisateur, c'est moi qui l'avait placé en premier pour simplifier mes tests.
![image](https://user-images.githubusercontent.com/51322714/174047514-cee9bfd9-e13f-404e-9042-982e52d5ddaa.png)

Par défaut, les onglets prennent l'ordre de ma première capture d'écran.

**Comment by ClementGre** [comment]
Dans l'onglet des compétences, il est maintenant possible de définir la "note" attribuée à chaque compétence :

![image](https://user-images.githubusercontent.com/51322714/175776058-1062fd58-e7bb-4e82-b331-e1dc923b82b3.png)

Si on clique sur l'icône, on a accès à un menu déroulant pour choisir la valeur qu'on veut donner à la compétence :

![image](https://user-images.githubusercontent.com/51322714/175776211-cbca0bc1-ab62-4594-8355-f166185e21b0.png)

On peut aussi simplement appuyer sur la touche du clavier après avoir sélectionné la compétence en cliquant dessus.

Le nom de la compétence correspondante n'est pas affiché (je pense que le graphique est suffisant), mais uniquement son graphique correspondant, qui peut être une image/icône, une couleur, ou des lettres comme c'est le cas pour les notations intégrées qui ne peuvent pas être modifiées.

**Comment by ClementGre** [comment]
Concernant le tableau de compétences, comme on a aucune information concernant le détail de l'évaluation, on peut partir sur un tableau tout simple comme celui-ci :

![grille-evaluation-employe-1024x611.png](https://user-images.githubusercontent.com/51322714/179470615-056311d0-e395-40a5-bdda-274fcdbc79bc.png)

Avec bien sûr la description complète de chaque compétence, et avec les icônes (Image, Lettres, Couleurs) à la place de la notation chiffrée sur l'image.

Il existe aussi la variante où il y a une colonne par niveau d'acquisition, mais il me semble qu'il serait aussi clair de mettre directement l'icône du niveau d'acquisition, avec une légende en dessous.

Dites moi ce que vous en pensez.
\- Clément

**Comment by l-leroux** [comment]
Bonjour,
Dans Sacoche, effectivement, les deux existent dans le rendu aux élèves car en particulier pour les plus jeunes, la croix dans la colonne plutôt que le symbole de la note est plus visuel. 
Il y a une option pour classer les compétences dans l'ordre défini pour la saisie ou bien par ordre croissant/décroissant des réussites (j'ai personnellement constaté que c'est plus lisible pour pointer les compétences qu'on a réussi ou pas.
Mais pdf4teachers n'est pas obligé de reprendre toutes ces options, c'est juste une idée. 
En revanche, il faudrait pouvoir débrayer la ligne "Note de savoir-faire", car suivant les situations, il n'y aura pas forcément de note de synthèse par domaine (à moins que cela ne soit une note saisie manuellement dans votre exemple ?)
Bravo en tous cas pour ce développement !

**Comment by ClementGre** [comment]
Oui, il n'y aura pas de moyenne affichée (pas de "Note de savoir-faire" sur l'image).

Je pense rajouter l'option des deux modes de tri des compétences (par défaut, et par réussite), ce qui ne serait pas très compliqué.
Je vais donc partir sur un tableau a seulement deux colonnes, plutôt que la croix dans la ligne, ce sera plus simple à développer.

Merci pour vos retours !

**Comment by ClementGre** [comment]
Voici le futur tableau de compétences :
![image](https://user-images.githubusercontent.com/51322714/180610380-9b5e7ce3-5755-4797-97f6-ca64dd77e463.png)

**Comment by ClementGre** [comment]
La fonctionnalité de notation par compétences est enfin disponible !

Je vous invite à tester les fonctionnalités via la pre-release publié aujourd'hui : https://pdf4teachers.org/Download/?v=1.4.0-pre1

N'hésitez pas à me faire des retours sur les fonctionnalités et à rapporter tout bug ici, ou dans une issue séparée.

La release finale sort très prochainement, merci à vous !

**Comment by ClementGre** [comment]
Je ferme cette issue suite à la publication de la version [1.4.0](https://pdf4teachers.org/Download/).

Merci à tout pour votre contribution !
