### ISSUE TITLE
pdf4teachers n'arrive pas à ouvrir un pdf

### ISSUE THREAD

**Issue by l-leroux** [ClementGre/PDF4Teachers#111]
Lors de l'ouverture du pdf envoyé par mél, les cadres des 4 pages apparaissent tout de suite mais l'animation de chargement tourne en boucle et ne s'arrête pas.
La console indique : +1: 
![image](https://user-images.githubusercontent.com/73694741/146885352-63fa83d7-8a23-436b-8440-62e36df1580e.png)

Version 1.3.1-sn1 sous Linux Mint 20.2

**Comment by ClementGre** [comment]
Ceci est un problème de support du standard de compression d'images JBIG2.
J'avais bien ajouté la dépendance nécessaire, mais un problème l'empêchait d'être disponible après compilation.

Merci pour cette issue, le problème est maintenant réglé et vous pourrez ouvrir ce fichier sans problèmes avec la version 1.3.1 finale.
