### ISSUE TITLE
Touche "suppr" supprime l'élément textuel quand on a le curseur en fin de ligne

### ISSUE THREAD

**Issue by l-leroux** [ClementGre/PDF4Teachers#112]
version 1.3.1-sn1
J'ai inséré le texte suivant 
`Notes : 
Respect des consignes : V
Réduire une expression algébrique : R`
puis supprimé le R et appuyé encore par erreur sur "suppr" et toute la note disparaît.
Cela pourrait être un comportement voulu si la note est vide de la faire disparaître par un appui sur suppr, mais je m'interroge sur le même comportement alors que la note n'est pas vide : bug ou fonctionnalité ?
Ctrl-z fonctionne bien pour remettre la note avant la suppression, donc je suppose qu'on pourrait laisser le comportement actuel, mais qui m'a surpris.

**Comment by ClementGre** [comment]
Ce comportement est bien voulu,
il fallait qu'après avoir sélectionné un élément textuel, l'utilisateur puisse :
- continuer sa rédaction en tapant directement (pour cela, le champ de texte devait prendre le focus),
- appuyer sur suppr pour supprimer l'élément.

Pour avoir ces deux comportement, il fallait accepter que le suppr en fin de ligne permette la suppression de l'élément.
Si vous trouez ça trop dérangeant, je peut voir pour ne faire fonctionner la suppression avec suppr non plus seulement en fin de ligne, mais aussi uniquement avant toute modification de texte (c'est à dire que si le texte a été changé depuis la dernière sélection d'élément, le suppr ne supprimera pas l'élément).
À voir, ça pourrait être un moyen simple de résoudre ce "problème".
