### ISSUE TITLE
Utilisation des "début" et "fin" pendant la saisie de texte

### ISSUE THREAD

**Issue by l-leroux** [ClementGre/PDF4Teachers#113]
version 1.3.1-sn1
Lorsqu'on est en train de saisir un texte, serait-il possible de pouvoir utiliser les touches "début" et "fin" pour aller au début de la ligne et à la fin de la ligne ?
Les touches début et fin semblent inactives en mode saisie, contre les habitudes usuelles de saisie de texte.
Merci !

**Comment by ClementGre** [comment]
Oui,
les touches début et fin sont en fait affectées au défilement dans le document, même lors de la saisie.
Un petit problème dont je ne m'étais pas préoccupé à l'époque.
Je vais régler ça.
