### ISSUE TITLE
Fonctionnalité de division de PDF

### ISSUE THREAD

**Issue by ClementGre** [ClementGre/PDF4Teachers#114]
Il s'agirait d'ajouter une fonction permettant de diviser un grand fichier PDF en plusieurs.
Deux grandes étapes :
- Diviser le PDF en fonction d'une page remarquable (une couleur spécifique)
- Nommer les nouveaux pdf en fonction de noms dans un fichier texte.

Message original de Laurent HIVON :
> L'académie d'Orléans-Tours étudie la faisabilité d'utiliser pdf4teachers dans la corrections de certains concours étant donné la qualité de votre travail dont nous vous remercions.
> 
> 
> Plusieurs étapes sont nécessaires
> 
> 1. Numériser les copies
> Les élèves travaillent sur des copies simples A4 anonymées
> A ce jour, nous récupérons des copies papier et envisageons donc de les récupérer sous forme pdf.
> Les photocopieurs d'établissement permettent aisément d'obtenir un unique fichier pdf former de l'ensemble des copies.
> 
> 2. Transformer un pdf unique en autant de pdf que de copies
> En insérant une page reconnaissable entre chaque copie avant le numérisation, pdf2go permet de fractionner le pdf.
> 
> 3. Renommer les pdfs obtenus
> Renommer les fichiers pdf par une liste de noms stockés dans un fichier texte (ici les numéros d'anonymat) est également faisable.
> AntRenammer sous Windows le fait.
> 
> Les possibilités offertes par pdf4teachers pourraient-elles être étendues pour assurer les deux tâches précédentes ?
> Les trois tâches précédentes pourraient ainsi être réalisées en établissement dans le logiciel que celui utilisé par les corrections par la suite ?

**Comment by ysalmon** [comment]
Je plussoie pour cette fonctionnalité : c'est souvent bien plus rapide de scanner un paquet "en une fois" sur l'appareil. L'automatisation par page reconnaissable est un plus pour les gros volumes, mais déjà, une interface pour couper à la main serait très pratique : dans le grand document PDF, on aurait un bouton pour signifier "le début du PDF jusqu'à la présente page constitue une copie" (étant entendu que la suite est alors le reste du document encore à séparer).

**Comment by ClementGre** [comment]
En effet, il serait intéressant d'avoir une fonction de création d'une copie avec toutes les pages depuis le début ou jusqu'à la fin.

Avec ça devrait aussi arriver l'option de réellement diviser le PDF (modifier le fichier d'origine en enlevant les pages extraites).

Peut-être pour ça serait-il intéressant de faire une réelle interface d'édition des pages, où l'on puisse les sélectionner pour des modifications plus rapides. À voir ce que cela apporte par rapport au temps de développement.

**Comment by ClementGre** [comment]
Bonjour,

cette fonctionnalité a été développée entièrement.

Il est maintenant possible de diviser le PDF ouvert en fonction de pages remarquables, qui sont déterminées automatiquement ou pas.

![image](https://user-images.githubusercontent.com/51322714/158024989-3e0112f9-ea97-40f2-99be-518e485a3ce5.png)

Les noms des documents extraits peut être importé depuis un fichier texte, ou écrits à la main.
La page remarquable est détectée en fonction de la proximité entre la couleur moyenne de la page, et la couleur de référence entrée.
Il est conseillé d'insérer des pages remarquables les plus sombres possibles pour les différencier le plus facilement possible.

![image](https://user-images.githubusercontent.com/51322714/158025186-5e6828ad-bb17-4b4e-818d-832978fd4e43.png)

Les pages détectées sont sélectionnées (C.f #118). Il est alors possible d'aller modifier la sélection à la main en cas d'erreurs. Il faudra donc ensuite passer par ``Diviser le document PDF selon la sélection``

Merci,
\- Clément

**Comment by ysalmon** [comment]
J'ai testé la séparation manuelle en récupérant le master, ça fonctionne très bien.

C'est moi qui vous remercie !
