### ISSUE TITLE
.deb package uses unsupported compression format on Debian

### ISSUE THREAD

**Issue by lucamp** [ClementGre/PDF4Teachers#115]
**Describe the bug**
on debian 11 (stable) PDF4Teachers-Linux-1.3.1.deb fails to install giving this error:

`dpkg-deb: error: archive 'PDF4Teachers-Linux-1.3.1.deb' uses unknown compression for member 'control.tar.zst'`

installing zstd packegs does not fix the issue.

As far as I understand debian's dpkg does not support yet zst compression, which is the default for nowadays ubuntu distros

**Desktop (please complete the following information):**
 - debian 11

**Comment by ClementGre** [comment]
``zst`` compression seems to be a compression format supported only by Ubuntu.

I'll re-upload the release with another compression format.
In the meanwhile, you can download the non-debian .tar.gz archive and install PDF4Teachers using the instructions provided in the archive.

Thank you, Clément Grennerat.

**Comment by ClementGre** [comment]
I just re-uploaded the .deb file with classic xz compression.
deb package should now work on Debian.

\- Clément G.
