### ISSUE TITLE
Gestion des copies doubles

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#116]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Mes étudiants rendent des copies doubles. Une page du fichier PDF que j'obtiens est par conséquent constituée de deux pages côte à côte. Typiquement, avec l'empilement des copies dépliées dans le scanner, je vois les pages comme suit (chaque ligne correspondant à une page du PDF) :

```
10 | 11
12 |  9
6  |  7
8  |  5
2  |  3
4  |  1
```

**Describe the solution you'd like**
Il serait commode de disposer de deux éléments d'interface :

 * l'un qui se contente de couper chaque page double au milieu pour obtenir deux pages
 * l'autre qui fait cette opération et en plus réorganise les pages pour les remettre dans le bon ordre.

Avoir le premier servirait au cas où certains jeux de copies doubles n'ont pas été scannés dans le bon ordre ou comprendrait un mélange de copies doubles et simples (il est sans doute plus clair de faire la réorganisation à la main).

**Comment by ClementGre** [comment]
Bonsoir @ysalmon,

Proposer ceci sous forme d'une mise en page (donc dynamique, qui ne modifie pas le pdf d'origine) serait techniquement un peu trop compliqué, mais il est totalement concevable de proposer une fonction type conversion, qui consiste à défaire un livret (Ce que vous m'avez dit, avec option de réorganiser les pages où pas).

Je note ça pour la prochaines version, merci pour la contribution !
Bonne fin de soirée,
Clément Grennerat

**Comment by ysalmon** [comment]
Oui, je voyais bien ça comme un prétraitement.

Mais en fait, il existe un logiciel, [PDF arranger](https://github.com/pdfarranger/pdfarranger), qui propose une interface graphique pour faire ce genre de choses (il n'y a pas encore de truc pour réarranger automatiquement une copie, par contre) ; je me demande si ça ne serait pas plus pertinent d'en faire une "application compagnonne" plutôt que de réimplémenter ces fonctionnalités.

**Comment by ClementGre** [comment]
D'accord je vois, il vaut mieux se concentrer sur les fonctionnalités spécifiques à la correction de copies, qui n'existent pas autre part.

**Comment by ysalmon** [comment]
En tout cas, si dans l'intervalle quelqu'un en a besoin, j'ai écrit un script pour automatiser ces opérations : https://framagit.org/-/snippets/6481

**Comment by ClementGre** [comment]
Bonjour,
cette fonctionnalité a été totalement développée.

Il est maintenant possible de désassembler un livret, avec diverses options. L'édition du document sera bien préservée, même si on utilise généralement cette fonction avant d'éditer un document.

Cette fonction ne peut pas être effectuée sur plusieurs documents à la fois, il faudra ouvrir le document en question avant de pouvoir démonter le livret via Outils > Outils de PDF > Créer ou démonter un livret. Ce n'est pas forcément gênant, car, d'après #114, toutes les copies sont scannées à la fois, et ensuite séparées en plusieurs PDF. Il suffira d'effectuer la conversion de livret avant de séparer les pages. (il y aura plusieurs pages séparatrices à la fois, mais ce n'est pas dérangeant, elles seront éliminées).

Les copies doubles sont des livrets spéciaux (plusieurs livrets de 4 pages à la suite), il faudra alors activer l'option correspondante (activée par défaut).

![image](https://user-images.githubusercontent.com/51322714/156895229-f741dc81-f94c-41d9-b0bb-e7da5b040b4c.png)

Comme vous avez pu le remarquer, il sera aussi possible de créer un livret, l'opération inverse.

Merci, Clément G.

**Comment by ysalmon** [comment]
J'ai testé. Ça fonctionne bien.

J'ai deux petits bémols :
 * la formulation de la dernière case à cocher n'est pas très claire : la notion de cœur ou d'avant d'un livret n'a pas beaucoup de sens pour moi, et surtout l'idée de commencement est étrange : je pose mon paquet de copies dans le bac du scanneur, et c'est lui qui scanne, c'est pas moi. Je pense qu'une formulation qui parle de l'état actuel du PDF plutôt que de la façon dont il a été obtenu serait plus facile : par exemple, la première page (conceptuelle) est-elle sur la dernière page du PDF ou sur la première ?
  * l'opération modifie le fichier source ; ce n'est pas clair au moment où on lance l'opération, et surtout ce n'est pas forcément ce qu'on souhaite, notamment si on se plante dans le choix de cocher ou non la case que j'évoque ci-dessus. Je propose d'ajouter une case (cochée par défaut) "conserver l'original sous le nom xxx-original.pdf" (il faudra juste lever une erreur et interrompre si ce fichier existe déjà).

Bien vu pour la gestion d'un paquet de copies multiples ; j'ai toujours cherché à faire la séparation d'abord mais en réalité on n'en a pas besoin.

À nouveau, c'est moi qui vous remercie !

**Comment by ClementGre** [comment]
Concernant la formulation, j'ai modifié pour ceci, ce qui est en effet plus compréhensible :
> Inverser l'ordre des pages avant de démonter le livret. Activez cette option si la première page (conceptuelle) est la dernière page du livret.

J'ai aussi ajouté l'option permettant de conserver l'original, que vous pourrez retrouver sur le master.

\- Clément

**Comment by ysalmon** [comment]
Ça semble très bien !!

Petite typo sur la première case : … sera opéré**e**

**Comment by ClementGre** [comment]
Ok c'est corrigé. Je ferme l'issue.
