### ISSUE TITLE
Liens URL page licence du site avec une erreur

### ISSUE THREAD

**Issue by jubonhomme** [ClementGre/PDF4Teachers#117]
Bonjour,

Il y a une coquille sur la page du site https://pdf4teachers.org/About/

Les deux hyperliens ont une erreur de frappe, il y a un "S" en trop dans "Li**s**cence" 
https://pdf4teachers.org/Liscense

On arrive sur une page erreur 404 ... C'est dommage de saboter la page d'une belle Licence libre ;)

![image](https://user-images.githubusercontent.com/29262866/152415910-6e36efe3-e707-4ffa-8385-5f466be5ebcf.png)

**Comment by ClementGre** [comment]
En effet, merci pour la signalisation, le problème est maintenant résolu !

Bonne fin de soirée,
Clément Grennerat
