### ISSUE TITLE
Affichage des pages en grille et sélection de pages

### ISSUE THREAD

**Issue by jubonhomme** [ClementGre/PDF4Teachers#118]
Bonjour,

J'utilise PDF4Teachers pour retravailler des PDF (ordre des pages / suppression / ajout ) et les annoter de façon assez simple. 

Avant d'annoter, je commence toujours par la mise en forme du document : orientation des pages / suppression / ordre etc...
Quand je réalise cette opération j'utilise un niveau de zoom assez bas pour voir et manipuler plusieurs pages à l'écran.
Mais du coup le bandeau des boutons de gestion des pages ( qui apparaît en haut à droite) est assez petit et les boutons sont relativement proches.

![Capture d’écran de 2022-02-03 22-45-12](https://user-images.githubusercontent.com/29262866/152439341-3b314705-cbf4-4f91-af86-14391568c9e5.png)

Je pensais au départ vous demander de conserver une taille de ce bandeau plus grande même lorsque le niveau de zoom est large ou de dupliquer ce bandeau dans la barre d'outils (doublon ?) pour que l'utilisation des boutons reste assez accessible.

Mais en voyant les autres demandes #114 et #116, je pense en effet qu'une vraie interface de mise en forme du PDF serait appréciable.
L'exemple de PDF Arranger que je découvre à cette occasion me semble une bonne piste.
![image](https://user-images.githubusercontent.com/29262866/152440766-d79d9e81-f438-48e6-a981-6d01c7c11877.png)

Je comprends l'idée de se focaliser sur la partie annotation qui est vraiment la partie centrale de votre application, et je ne mesure pas l'investissement en temps qu'il y aurait pour travailler la partie sur la gestion des pages.
Mais l'intérêt d'avoir une seule application qui permette de gérer l'ensemble de la chaîne "copieur qui scanne -> PDF annoté" me semble assez important.  

On pourrait imaginer une interface multi-pages comme dans PDF Arranger (ou LibreOffice ) qui permette de gérer la mise en forme avant de passer à l'annotation. PDF Arranger permet par exemple de glisser des pages directement pour les réorganiser. 
Ça pourrait aussi faciliter la portabilité vers les interfaces tactiles (cf #109   tablettes ou TBI / VPI )

pär exemple : en ajoutant un bouton pour en bas à côté du zoom pour passer à une édition en mode multi pages
![essai](https://user-images.githubusercontent.com/29262866/152444086-98e1a0d2-b254-4f0f-901c-3a2205cb8e43.png)

**Comment by ClementGre** [comment]
Bonjour @jubonhomme,
concernant la taille des boutons d'édition des pages, ils sont censé avoir une taille minimale, j'ai un peut modifié ça, maintenant ils ont vraiment une taille fixe.

Concernant la gestion des pages, il existe en réalité déjà un système permettant de déplacer les pages par glisser-déposer quand le zoom est de moins de 41%, et il existe aussi un bouton en bas à côté du slider de zoom, qui permet de passer directement à un zoom de 40% (cela n'est peut être pas assez documenté).

Ceci revient presque à une réelle interface d'édition de pages si ce n'est que les pages sont en colonne et non en grille, et que l'on ne peut pas les sélectionner pour effectuer des actions groupés.

En poussant encore un peut plus loin le comportement de l'application quand le zoom est de moins de 40%, il y a peut-être moyen de mettre en place une disposition en grille avec une possible sélection.

À voir si cela est faisable, mais je prend en considération cette idée.

\- Clément G.

**Comment by jubonhomme** [comment]
Bonjour @ClementGre 
Ah mais oui ! Je découvre que le zoom < 40 % correspond quasi l'interface dont je parlais.

C'est donc effectivement plus une amélioration de l'interface avec un mode grille car les fonctions sont bien présentes.
Mais en restant sur un affichage vertical on perd beaucoup en lisibilité et on utilise assez mal la taille de l'écran.

![image](https://user-images.githubusercontent.com/29262866/152687272-014abfc1-bbca-4565-a104-8c2617157b06.png)

Donc ma liste de souhaits pour de futurs évolutions :  

- Avoir un picto qui soit plus évident pour le passage à un mode grille
voici un exemple de celui sur le logiciel do•doc pour passer d'une vue page à une vue multipages
![image](https://user-images.githubusercontent.com/29262866/152687453-826a6f29-22ea-40cb-91bf-334ad72a9363.png)

- avoir un cadre de sélection qui identifie la page sélectionnée, si une page est sélectionnée on pense plus facilement au glisser / déposer

- avoir un rappel des numéros de pages 

- pouvoir faire une sélection de plusieurs pages ( encadrant à la souris /  sélection avec maintien touche "Ctrl" / Sélection 1er vignette + Sélection dernière + Maj )

- avoir la possibilité de supprimer une page avec le raccourci touche "Suppr"


C'est juste une liste de propositions comme tu l'évoques dans ton message précédent... c'est déjà fonctionnel et avant tout un grand merci pour ce logiciel déjà très complet !

**Comment by ClementGre** [comment]
Quelques modifications suite à [#122](https://github.com/ClementGre/PDF4Teachers/issues/122#issuecomment-1073028702), qui permet une vue en grille, même lorsque le mode édition des pages n'est pas activé.

Le mode édition des pages n'est donc plus lié au zoom, mais uniquement activable avec le bouton à bascule de la barre du bas.
Deux nouveaux boutons ont été ajoutés de manière à pouvoir choisir d'afficher plusieurs pages sur une seule ligne ou pas.

![image](https://user-images.githubusercontent.com/51322714/159127256-bc0d3901-a37a-4c1c-b2c2-94452dce8907.png)
