### ISSUE TITLE
Mode "écriture continue" pour tablette graphique

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#120]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+label%3A%22enhancement%22+)

**Contexte**

J'ai fait une première (petite) session de correction avec PDF4Teachers et c'est vraiment très pratique !

J'ai travaillé avec une tablette graphique (que je découvre également, donc je suis en rodage). Dans ces conditions, j'ai trouvé plus pratique de faire toutes mes annotations avec l'outil de dessin à main lever : le clavier étant loin (à cause de la tablette), pour des petites remarques c'est plus rapide de les écrire à la main. Ça rapproche aussi le travail de ce qu'on fait sur papier.

**Problème**

Je me suis aperçu que lorsque je passe en mode dessin (Ctrl+D mappé sur un bouton de la tablette), un seul, très long, chemin SVG est créé jusqu'à ce que je termine le dessin (en faisant un clic avec le bouton milieu par exemple). Et manifestement, au fur et à mesure que le chemin s'allonge, le logiciel a du mal à suivre : si j'écris quelques mots, l'écriture devient de moins en moins fluide et le tracé de plus en plus grossier. Ça rentre dans l'ordre si je "coupe" le dessin en plusieurs (ce qui nécessite un clic-milieu puis un Ctrl+D).

Un autre point m'a gêné : si j'utilise le pointeur de la souris (en fait le stylet de la tablette) pour déplacer la page, il arrive que je déplace en fait un dessin qui se trouve à cet endroit.

**Solution envisagée**
Proposer un outil "dessin en continu" en plus de l'actuel outil de dessin. Quand cet outil est actif :
 * poser le crayon (ie cliquer à un endroit de la feuille) commence un chemin libre SVG (comme dans le Ctrl+D actuel) ;
 * l'interruption du dessin (levée du crayon) provoque la terminaison du chemin SVG en cours, mais sans sortir du mode "dessin en continu" ;
 * les objets (annotations, etc.) ne sont pas déplaçables, seul l'affichage de la page dans sa globalité l'est (éventuellement permettre de déplacer un objet si Ctrl est enfoncé, par exemple).
 
Le point qui reste peu clair dans mon esprit est : comment distinguer une commande de déplacement de la page d'une commande de tracé. On pourrait dire que le clic-milieu (ce qui correspond à un bouton du stylet) est nécessaire pour déplacer ; on pourrait à l'inverse déplacer la page par défaut (ie. avec le clic-gauche) et écrire avec le clic-milieu.

**Comment by ClementGre** [comment]
Bonjour,

j'ai développé cette nouvelle fonctionnalité, en espérant qu'elle sera répondre à vos besoins.

- Des options ont été ajoutées dans les paramètres pour permettre la division automatique des éléments, en fonctions de divers critères :
  <img width="400px" src="https://user-images.githubusercontent.com/51322714/159055781-74774b66-468d-42d2-ba3c-aff17669ccc6.png" />
  Je n'ai pas ajouté de raccourcis clavier car ces options ne dérangent pas l’interaction classique avec les éléments et le document, c'est une simple division lors du commencement d'un nouveau segment, si l'une de ces trois conditions est validée.
- Lorsque le curseur survole une nouvelle page (avec le mode dessin activé sur une autre page), un nouvel élément (en mode dessin) est créé sur la nouvelle page, permettant de passer d'une page à l'autre avec fluidité.
- Le défilement est possible avec le clic molette sur l'ensemble du document (éléments, surface de dessin, pages...)

Toute interaction avec le document est donc toujours possible, et il n'y aura pas d'option particulière à activer (à part pour la division).

Merci à vous, Clément Grennerat
