### ISSUE TITLE
Boutons de boite de dialogue non visible (interface zoomée)

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#121]
- [x] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
J'utilise le zoom de l'interface graphique (1.75). La fenêtre principale fonctionne bien, mais lorsqu'une boite de dialogue s'affiche, son contenu n'apparait pas en entier, et notamment pas les boutons.

Je pense que le facteur de zoom n'est pas pris en compte dans le calcul des dimensions de la boite de dialogue.

**Screenshots**
![Screenshot_20220208_222554](https://user-images.githubusercontent.com/536850/153078689-88be11e7-e9c7-492a-af4e-1522eea29f66.png)

**Desktop (please complete the following information):**
 - OS+version: KUbuntu 20.04

**Comment by ClementGre** [comment]
Ce bug est assez courant avec les dialogues.
Je n'ai pas ce bug de mon coté, il est très spécifique de l'OS et des conditions matérielles.

Je vois cependant d'où il vient et j'ai pris des mesures pour le résoudre.
Ce bug ne devrait plus être là dans la prochaine version.

**Comment by ysalmon** [comment]
Sur le master, ça semble mieux se passer, mais pas totalement. Notamment pour le (nouveau) dialogue de Démonter le livret mais aussi pour d'autres plus anciens (mais que je n'avais jamais affichés avant, je ne sais pas si ça joue).
![Screenshot_20220323_224709](https://user-images.githubusercontent.com/536850/159801407-74c4b54b-7f3c-4464-b840-1932c10943cc.png)

**Comment by ClementGre** [comment]
Ok, il y avait encore des petits problèmes que j'ai maintenant réglé, merci d'avoir testé ça.
Vous ne devriez plus avoir ce problème sur le master.
