### ISSUE TITLE
Affichage pleine page et double page

### ISSUE THREAD

**Issue by Keyskeeper** [ClementGre/PDF4Teachers#122]
### Prerequisite

- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+label%3A%22enhancement%22+)

### Is your feature request related to a problem? Please describe.

J'aimerais pouvoir facilement voir une copie entière lorsque je corrige.

Est-il possible de définir un zoom par défaut pour  toutes les copies chargées ?

J'aimerais aussi pouvoir voir deux pages côte à côte sur les grands écrans.

Merci pour ce travail

**Comment by ClementGre** [comment]
Bonjour,

L'issue #118 répond peut-être en partie à vos besoins mais si j'ai bien compris vous souhaiteriez avoir accès à la vue en grille aussi dans un contexte d'édition classique avec éléments, avec un zoom pas nécessairement inférieur à 40%.

Il s'agirait alors pour moi de séparer le système de vue en grille, et le système d'édition des pages.

Concernant le zoom par défaut, actuellement il est définis de manière à maximiser la largeur de la page affichée, mais je peut ajouter dans les paramètres un moyen de définir un niveau de zoom par défaut (ce qu'il y avait dans d'anciennes versions de PDF4Teachers, mais qui a été retiré lors de l'ajout du zoom automatique pour une largeur optimale).

\- Clément

**Comment by Keyskeeper** [comment]
Effectivement,

j'avais lu un peu vite la proposition #118 il semble que cela corresponde bien.

J'ouvre un autre fil pour un autre sujet ;)

Merci encore

**Comment by ClementGre** [comment]
Il me semble que vous, vous souhaitez avoir une vue en grille même lors de la correction. Sachez que la fonctionnalité de #118 apporte ce mode grille uniquement lors de l'édition des pages (déplacement, rotation...), lors d'un zoom < 40%.

Comme je l'ai dit, "Il s'agirait alors pour moi de séparer le système de vue en grille, et le système d'édition des pages" de manière à bénéficier de l'affichage en grille même lors d'un zoom supérieur à 40%.
Ce n'est pas forcément très compliqué à faire, le plus compliqué serait de définir :
- L'affichage en grille est-il toujours activé ? Dans ce cas, l'utilisateur ne pourra pas afficher les pages uniquement en colonnes sans restreindre artificiellement la largeur de l'application.
- Autrement, il faudrait dédoubler ce bouton :
![image](https://user-images.githubusercontent.com/51322714/156895802-f411227b-f025-4ec0-a6d0-d582e6e46011.png)
De manière à avoir "Affichage multi-page"/"Affichage une seule page", comme les boutons suivants de LibreOffice par exemple : 
![image](https://user-images.githubusercontent.com/51322714/156895857-ac495f3d-60c8-4691-9a58-899a7274803c.png)
Et il faudrait aussi un toggle/switch pour activer l'édition des pages (qui serait alors possible avec un zoom de plus de 40%).

concernant la question du niveau de zoom par défaut, cela dépend beaucoup de la largeur de la fenêtre, et il serait inadapté d'ouvrir un document avec un zoom de 200% si l'utilisateur avait mis sa fenêtre en petit dans un coin.
Actuellement (dans la prochaine version), le niveau de zoom est mémorisé binairement : soit le zoom est de moins de 40% et il sera restauré à 40%, sinon si il est de plus de 40% il sera restauré de manière à avoir une largeur maximale. Ce que je pourrais rajouter, après un éventuel développement des fonctionnalités citées plus haut, serait de faire un affichage à deux pages côte à côte (ou plus), mais automatiquement, quand la fenêtre de l'application a une largeur minimum et que le mode Affichage multi-page est activé. Cela me semble être un bon compromis.

Merci, Clément G.

**Comment by ClementGre** [comment]
Bonjour,

j'ai donc séparé le système de vue en grille, et le système d'édition des pages de #118 de manière à bénéficier du mode vue en grille aussi lors de la correction. On a maintenant un bouton à bascule pour le mode édition des pages, et deux boutons à bascule groupée pour passer choisir d'afficher plusieures pages sur une seule ligne ou pas.

![image](https://user-images.githubusercontent.com/51322714/159127094-747640d1-6865-447c-96da-a1801133c560.png)
