### ISSUE TITLE
Plus d'options de soulignement

### ISSUE THREAD

**Issue by built2spill69** [ClementGre/PDF4Teachers#124]
Serait-il possible, s'il-vous-plaît d'ajouter plus de motifs de soulignement ? Voyez l'exemple en photo. 
Je vous remercie. 
![IMG_0919](https://user-images.githubusercontent.com/65373072/157109384-452e9ae6-4cb0-49ac-ad6b-fb7300edaddb.jpg)

**Comment by ClementGre** [comment]
Bonjour,

je peut vous proposer plusieurs motifs de soulignement que vous pouvez utiliser dès maintenant et que je vais certainement rajouter dans les éléments favoris par défaut dans les futures versions.

Sachez que le soulignement dans PDF4Teachers n'est qu'un élément SVG qui est en mode répétition, vous pouvez donc en créer un nouveau via <img width="20px" src="https://user-images.githubusercontent.com/51322714/159115696-29c619a8-31e4-48f2-a3a8-be38b97aadd1.png" /> > Nouveau chemin vectoriel, puis dans les options avancées, sélectionnez ces paramètres : 
![image](https://user-images.githubusercontent.com/51322714/159115728-a10b19b4-7c59-46e4-ad5c-0af6a88eeefb.png)

Ensuite, si vous voulez, vous pouvez créer vos propres motifs via le champ de texte (ou juste copier coller ceux que je vous propose plus loin), je vous renvoie alors vers la documentation des chemins SVG : [https://developer.mozilla.org/fr/docs/Web/SVG/Tutorial/Paths](https://developer.mozilla.org/fr/docs/Web/SVG/Tutorial/Paths).
(Pensez à y entrer un Move vers des coordonnés Y négatifs pour forcer l'élément à être plus haut que le dessin en lui nême).

Voila ce que je peut vous proposer :
![image](https://user-images.githubusercontent.com/51322714/159115692-8e36205a-80ee-4d15-9e70-2e1b2e976249.png)
Dans l'ordre :
- ``M0 1 L1 0 L2 1 M0 -7``
- ``M0 1 L0 1 M2 -7``
- ``M0 1 L1 1 M2 -7``
- ``M0 1 L5 1 M7 -7``
- ``M 0 20 Q20 0, 40 20 Q60 40, 80 20 M80 -100``
