### ISSUE TITLE
Problème de sauvegarde de l'édition

### ISSUE THREAD

**Issue by julie-tournier** [ClementGre/PDF4Teachers#126]
Bonjour,
Lorsque j'utilise pdf4teachers, l'édition n'est plus sauvegardée. 
Bien à vous,
Julie T.

**Comment by ClementGre** [comment]
Bonjour,
- est-ce que vous rencontrez ce problème sur tous les documents, même un nouveau  document nouvellement édité ?
- Pouvez-vous envoyer une capture d'écran de la fenêtre qui apparaît après avoir appuyé sur Ctrl+Alt+C dans PDF4Teachers après avoir essayé d'enregistrer une édition ?
- Que se passe-t-il lors de l'essai d'enregistrement ? (message sauvegardé dans la barre du bas ? Document toujours marqué comme édité ?).

\- Clément Grennerat

**Comment by julie-tournier** [comment]
Bonjour,
Merci pour le retour très rapide.
Oui, tout fonctionnait très bien et maintenant, plus aucune édition n'est
sauvegardée (bien que le message "sauvegardé" apparaissait toujours bien en
bas lorsque je cliquais sur sauvegarder l'édition). Je suis sur Mac, j'ai
testé en faisant "sauvegarder l'édition" et en appuyant sur "commande + S"
Je viens de retenter et rien ne se passe désormais lorsque je sauvegarde.
Pour info, j'ai déjà désinstallé et réinstallé pdf4teacher afin de régler
le problème mais ça ne fonctionne toujours pas.
bien cordialement,
Julie Tournier

**Comment by ClementGre** [comment]
Il va falloir que vous me donniez des détails à propos de ce problème pour que je puisse vous aider :
- est-ce que vous rencontrez ce problème sur tous les documents, même un nouveau  document nouvellement édité ?
- Pouvez-vous envoyer une capture d'écran de la fenêtre qui apparaît après avoir appuyé sur Ctrl+Alt+C dans PDF4Teachers après avoir essayé d'enregistrer une édition ?
- Que se passe-t-il lors de l'essai d'enregistrement ? (message sauvegardé dans la barre du bas ? Document toujours marqué comme édité ?).
- Si vous n'obtenez aucun résultat, vous pouvez essayer de supprimer une partie ou la totalité du dossier de configuration de PDF4Teachers, en copiant les fichiers autre part en attendant, pour ne pas perdre vos données de l'application. Vous pouvez accéder à ce dossier depuis l'application : menu Outils > Débogue > Ouvrir le dossier de données. Pensez à fermer PDF4Teachers avant de modifier le contenu du dossier.
- Pouvez-vous m'indiquer la version de PDF4Teachers que vous utilisez, et éventuellement mettre à jour vers la pre-release 1.4.0 qui est très stable.

\- Clément Grennerat
