### ISSUE TITLE
Respect des dossiers de la spécification XDG

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#127]
### Prerequisite

- [X] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+label%3A%22enhancement%22+)

### Is your feature request related to a problem? Please describe.

Je m'en suis aperçu en allant voir log et caches : sous Linux, PDF4Teachers met tous ses fichiers sous ``$HOME/.PDF4Teachers``.

La spécification XDG demande d'éviter cela (ça met plein de dossiers dans ``$HOME``, déjà…) et d'utiliser des dossiers spécifiques, configurables par variables d'environnement et avec des valeurs par défaut standardisées : https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables.

**Comment by ClementGre** [comment]
Il faudrait donc déplacer le dossier .PDF4Teachers vers ``$XDG_DATA_HOME``, ou ``$HOME/.local/share`` si ``$XDG_DATA_HOME`` n'est pas valide.

Je m'occupe prochainement de ça.

**Comment by ysalmon** [comment]
Oui, après si on veut complètement respecter la spec, on est censé mettre la config dans ``$XDG_CONFIG_HOME`` et les caches dans ``$XDG_DATA_HOME`` (l'idée étant de savoir facilement ce qui doit être sauvegardé/transféré et ce qui peut être effacé sans problème). Mais pour une application de cette envergure c'est peut-être pas nécessaire.
