### ISSUE TITLE
Caractères étendus non exportés dans le pdf

### ISSUE THREAD

**Issue by l-leroux** [ClementGre/PDF4Teachers#130]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.2%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Bonjour,
j'ai ajouté en texte le commentaire suivant : 
"VV → Organiser son travail personnel
R → Respecter les consignes
V → Traduire par une figure (précision du tracé, annotation)
V → Comprendre l'effet des transformations géométriques"
et le caractère "→" a été transformé dans le pdf en "�"
Sans doute un problème d'encodage ou de limitation de la bibliothèque intégrant les textes dans le pdf ?
Merci pour votre travail !

### To Reproduce

1. 
2. 
3. 
4. 

### Check the console

```java
Elle n'est pas vide, mais ne comporte que 2 erreurs,"error reading image metadata", donc je pense que cela n'a rien à voir...
```

### Edits

versionID: 4
texts:
  page0:
  - x: 3093
    y: 180136
    color: '0xff0000ff'
    font: Open Sans
    size: 16.0
    bold: true
    italic: false
    text: |-
      VV → Organiser son travail personnel
      R → Respecter les consignes
      V → Traduire par une figure (précision du tracé, annotation)
      V → Comprendre l'effet des transformations géométriques
    maxWidth: 90.0
  
  - x: 8694
    y: 0
    color: '0xff0000ff'
    font: Open Sans
    size: 16.0
    bold: true
    italic: false
    text: |-
      VV → Organiser son travail personnel
      VV → Respecter les consignes
      VV → Traduire par une figure (précision du tracé, annotation)
      VV → Comprendre l'effet des transformations géométriques
    maxWidth: 90.0
grades:
- {x: 8325, y: 0, page: 0, index: 0, parentPath: '', value: -1.0, total: 0.0, outOfTotal: -1.0,
  name: Total, alwaysVisible: false}
lastScrollValue: 0.0

### Screenshots

![Sélection_051](https://user-images.githubusercontent.com/73694741/169682329-ba79c672-9ed2-4285-93ad-35baec148a6a.png)

### Desktop

Linux Mint 20.3

**Comment by ClementGre** [comment]
Bonjour,
si ce caractère ne s'affiche pas correctement après exportation, c'est qu'il n'est pas supporté par la police choisie.

Dans l'application, JavaFX fait automatiquement une substitution avec une police de l'OS qui supporte ce caractère, mais lors de l'exportation, je ne supporte pas la substitution de police.

Essayez donc de changer de police, ça pourrait peut-être régler le problème.
Il me semble que vous auriez dû avoir un message d'alerte vous indiquant ce problème.

Je vais essayer de reproduire cela de mon côté.

\- Clément

**Comment by ClementGre** [comment]
Ce caractère est supporté par la police Arial par exemple. Calibri supporte aussi ce caractère.
Je veillerais à ajouter une alerte d'information dans la prochaine version, en cas de caractères non supportées.

**Comment by l-leroux** [comment]
D'accord, merci !
C'est effectivement cette différénce de traitement de l'appli et de l'export qui est troublant. Si on avait directement le problème dans l'appli, on penserait peut-être à changer de police...

**Comment by ClementGre** [comment]
Il y aura maintenant un message d'erreur lors de l'export d'un caractère non défini dans la police :
![image](https://user-images.githubusercontent.com/51322714/174059481-ea0a3d12-cfbe-4220-88ec-38aa4142248d.png)

Il serait aussi intéressant de pouvoir changer les polices de tous les éléments textuels du document d'un seul coup.
