### ISSUE TITLE
Renommer un fichier depuis la liste des fichiers

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#131]
### Prerequisite

- [X] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.2%22+label%3A%22enhancement%22+)

### Is your feature request related to a problem? Please describe.

J'ai testé en conditions réelles le démontage de livret puis la séparation de pages. C'est royal !

Cependant, je trouve que le moyen de nommer les fichiers obtenus en séparant selon une sélection n'est pas très commode : on doit cliquer sur les pages où il faut séparer, et ensuite seulement dans la fenêtre de génération on doit donner le noms. Or, le nom des élèves n'est pas visible à ce moment là. Et même sur l'écran de sélection de page, les choses sont souvent un peu petites (ce qui est normal, on veut avoir une vue d'ensemble).

Donc pour faire ma séparation, j'ai généré des noms de fichiers séquentiels : fichier01 à fichier45.

J'ai donc des PDF ainsi nommés.

### Describe the solution you'd like

Finalement, est-ce que le meilleur moment pour nommer un fichier, ce n'est pas quand on commence à corriger la copie ?

On est de toutes façons obligé de saisir à ce moment là le nom (ou le numéro d'anonymat) pour que les notes correspondent à quelque chose.

Dès lors, ce serait commode, dans le menu contextuel qui s'obtient cliquant-droit sur un fichier dans la liste, de pouvoir renommer ce fichier (il faudrait que l'édition suive, au cas où on le fait en fin de correction de copie).

**Comment by ClementGre** [comment]
Il serait en effet agréable d'avoir cette fonctionnalité, qui serait très facile à développer.

J'ajoute ça sur la liste des tâches pour la 1.4.0.

**Comment by ClementGre** [comment]
Bonjour, cette fonctionnalité a été implémentée :

![image](https://user-images.githubusercontent.com/51322714/174310550-7f504584-5e15-46b6-8e09-17cd9d3b197a.png)
![image](https://user-images.githubusercontent.com/51322714/174310620-5c168666-4f4b-4491-8ba6-6586618cce94.png)

On peut y accéder depuis le menu Fichier, depuis la liste des fichiers, ou avec Ctrl + R.

J'ai dans le même temps ajouté une rapide option permettant de créer une copie d'un document.

![image](https://user-images.githubusercontent.com/51322714/174310911-a6ad25dd-1461-4578-8e71-7016f5b31f30.png)
