### ISSUE TITLE
La division de PDF par sélection élimine les pages sélectionnées

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#133]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.2%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Lors d'une division de PDF par sélection, les pages sélectionnées ne se retrouvent dans aucun des documents générés.

Concrètement, si on sélectionne la première page de chaque copie (ce qui est le plus pratique visuellement), on perd cette page dans le résultat.

Je pense que le comportement est décalqué de celui de la division automatique par page de couleur, où les dites pages de couleur doivent être éliminées. Mais pas ici.

**Comment by ClementGre** [comment]
Bonjour,
il serait en effet peut-être intéressant d'ajouter une option "Garder les pages sélectionnées et les inclure dans le document suivant", ou quelque chose comme ça.

Je note ça pour la 1.4.0.

**Comment by ysalmon** [comment]
Oui, c'est ça. Il est plus commode de sélectionner le début d'une copie que la fin, donc il faut considérer la sélection incluse dans ce qui la suit.

**Comment by ClementGre** [comment]
J'ai bien ajouté l'option. Elle sera disponible dans la prochaine version.


![Image](https://user-images.githubusercontent.com/51322714/187071219-03f57f6b-1f96-4369-9089-1a6d39cc45da.png)
