### ISSUE TITLE
Décalage vertical du dessin

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#135]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.2%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Lorsque je corrige à main levée, il arrive que le dessin soit tracé environ un centimètre plus haut que le curseur de la souris (la croix).

J'ai l'impression que ça se produit après que j'ai fait des annulations (Ctrl+Z) dans un tracé (mais ça ne se produit pas à chaque fois que je fais des annulations).

Sortir du mode dessin (Esc) puis y retourner annule le problème (et apparemment, faire perdre le focus à la fenêtre puis y retourner aussi ?).

### Desktop

KUbuntu 22.04

**Comment by ClementGre** [comment]
Il y a en effet un décalage qui se produit lorsque le trait annulé se situait au dessus de l'avant dernier trait (devenu le dernier trait).
Ce phénomène se reproduit aussi sur l'axe X.

Le problème est maintenant réglé, il s'agissait du redimensionnement de l'élément lors de l'annulation, qui était effectué alors même que le mode de dessin était activé.
