### ISSUE TITLE
Erreur lors de l'écrasement d'une exportation PDF

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#136]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.2%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Lorsque j'exporte toutes les copies vers un dossier qui contient déjà des copies exportées, PDF4Teachers ouvre une boite de dialogue signalement qu'un écrasement est susceptible d'avoir lieu.

RQ : il serait pratique de pouvoir dire "écraser tout", car j'ai l'impression qu'on nous demande de le faire fichier par fichier.

Surtout, quand je clique sur Écraser, j'obtiens l'erreur suivante, dans une autre boite de dialogue :
Cannot invoke "javafx.scene.Scene.getWidth()" because "<parameter2>" is null

Cette boit d'erreur s'affiche alors de façon répétée quand je clique sur Continuer.

**Comment by ClementGre** [comment]
Normalement, à partir du deuxième fichier déjà existant, le dialogue devrait être adapté avec les boutons "Toujours [...]" ajoutés :

![image](https://user-images.githubusercontent.com/51322714/174739794-5e6c3683-e1f2-4d04-a6b9-0231e501967a.png)

J'arrive a obtenir votre erreur lorsque j'utilise l'interface zoomée. Cette erreur est due au re-zoom d'une alerte déjà existante.
J'ai un peut modifié le dialogue, le rendant en même temps plus simple, avec juste une coche pour mémoriser le choix.

![image](https://user-images.githubusercontent.com/51322714/174747446-7d089763-9743-4015-a48c-1cb6b258b3fb.png)

Ce problème ne surviendra plus dans la prochaine version. Merci pour le rapport de bug !
