### ISSUE TITLE
Bloqué sur la première lettre

### ISSUE THREAD

**Issue by rtomczak** [ClementGre/PDF4Teachers#143]
Bonjour,
Au bout d'un moment dès que j'entre un nouvel élément textuel, la chose bizarre se passe : je reste bloqué à la première lettre et un choix à gauche m'est proposé.

![image](https://user-images.githubusercontent.com/11694903/198531065-c90dcc2a-12c3-48d8-b5c7-488685f3344b.png)

je ne comprends pas trop pourquoi ...
Merci par avance

**Comment by ClementGre** [comment]
Bonjour,
comme vous pouvez le voir sur votre capture d'écran, le dernier élément de la liste des éléments sur le document est sélectionné, comme il est sélectionné, le champ de texte d'entrée ne peut pas recevoir les entrées clavier.

Si vous cliquez à nouveau sur le champ de texte, il devrait prendre le "focus" et vous serez à nouveau en mesure d'entrer du texte.

La question qui se pose alors est pourquoi est ce que cet élément est sélectionné (à chaque création d'un nouvel élément textuel) ? Normalement, il faut faire flèche haut/bas pour sélectionner les éléments semblables (et ensuite les ajouter avec entrée.

Que ce passe-t-il exactement ? Dès que vous cliquez sur "Nouveau", le dernier élément de la liste est constamment sélectionné sans même que vous ne pressiez la flèche du haut ?

Merci à vous, Clément.
