### ISSUE TITLE
Le retour des boites de dialogue trop petites

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#144]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Bonjour,

je me suis remis à utiliser PDF4T, en version 1.4.0, avec un zoom de 1.25.

J'ai des boites de dialogues trop petites pour afficher tout leur contenu, comme avec #121.

Ça ne le fait pas à chaque fois, mais quand même la plupart du temps.

### Screenshots

![Screenshot_20221102_172825](https://user-images.githubusercontent.com/536850/199567955-7269ae22-1fd7-4926-a0e6-f99163cb40fb.png)

### Desktop

KUbuntu 22.04

**Comment by ClementGre** [comment]
Bonjour,
Je suis désolé pour ce problème qui revient trop souvent (et aussi désolé de vous répondre aussi tard).

En fait, je me bats un peu contre JavaFX et contre l'OS pour d'abord déterminer les dimensions du dialogue (attendre qu'il fasse son "rendu"), puis d'augmenter sa taille en proportions de la taille originale.

Le problème dans la 1.4.0 ne se reproduit que sous linux (Testé sous KUbuntu 21.10).

J'ai recodé une partie de ce fonctionnement d'une manière un peu différente, et le bug ne devrait plus se reproduire.

Pour éviter de se retrouver avec le même bug dans la 1.4.1, je vous publie une snapshot pour que vous puissiez tester : [https://pdf4teachers.org/data/PDF4Teachers-Linux-1.4.1-sn1.deb](https://pdf4teachers.org/data/PDF4Teachers-Linux-1.4.1-sn1.deb).

Merci pour votre contribution !
