### ISSUE TITLE
La sauvegarde des compétences ne fonctionne pas pas après un import d'édition sur un document déjà édité

### ISSUE THREAD

**Issue by levaches01** [ClementGre/PDF4Teachers#146]
Bonjour,
Tout d'abord, merci pour votre super boulot !
Je voulais juste vous signaler un bug au niveau des compétences. J'ai importé un devoir depuis Sacoche et je l'ai importé dans PDF4Teacher. Jusque là tout fonctionne bien. J'ai bien la liste avec les élèves. J'ai importé le dossier où il y a les doc pdf de mes élèves et je commence à corriger. Je met le niveau de compétence de mon élève et là, lorsque je passe à la copie suivante et que je reviens sur la copie précedente, le tableau Sacoche de compétence a disparu. Je dois remettre une seconde fois le niveau de compétence et là, quand je passe à la copie suivante, c'est bien sauvegardé. Il faut faire à chaque fois la manipulation 2 fois pour que le tableau des compétences reste sur la copie.
J'espère avoir été assez clair...
Merci encore pour tout votre travail.
Bien cordialement,

**Comment by ClementGre** [comment]
Bonjour,
en fait, c'est comme si le document n'avait pas été sauvegardé.
Après avoir sauvegardé, dans la liste des fichiers, le check vert/orange, et le nombre de compétences remplies en laissant la souris sur le fichier :
<img width="210" alt="image" src="https://user-images.githubusercontent.com/51322714/201468717-9a354b69-8b1e-46d6-a1a5-5189876c6173.png">

Est-ce que l'édition est entièrement réinitialisé (Devoir et élève déselexionné), ou c'est juste les compétences qui ne sont plus remplies, ou alors juste le tableau qui disparaît ?
Est-ce que vous voyez Est-ce que, si vous ajoutez des éléments textuels, ils disparaissent eux aussi lors de la première fermeture ?

Avant de sauvegarder, est ce que vous voyez bien apparaître l'étoile dans le nom de la fenêtre, indiquant que des modifications ont été faites sur le document :
<img width="262" alt="image" src="https://user-images.githubusercontent.com/51322714/201468811-f2f89fbf-a4f1-4de1-a118-f0ee245f1eac.png">
S'il n'y a pas d'étoile, il n'y aura pas de sauvegarde, mais l'étoile apparaît normalement après toute modification de compétences.

Après avoir reproduit le bug, pouvez-vous presser Ctrl+Alt+C pour accéder à la console. Si vous voyez plus de deux lignes écrites, envoyez-moi une copie d'écran de la fenêtre de console.

Est-ce que vous pouvez reproduire le bug avec un devoir classique, non importé depuis SACoche ?

En espérant que vos réponses me permettent de mieux comprendre ce bug.

**Comment by levaches01** [comment]
Merci pour votre réponse rapide,
En fait, l'édition de compétence disparait totalement. Il faut remettre le devoir dans la liste et de nouveau choisir le nom de l'élève.
En remettant une deuxième fois, ça fonctionne.
J'ai réalisé une vidéo afin de vous montrer le bug : 
[https://www.sltechno.net/PDF4Teacher/Bug_comp%C3%A9tences/Bug_comp%C3%A9tences.html]

Merci

**Comment by ClementGre** [comment]
Merci pour la vidéo !
Malgré tout, je n'arrive pas à reproduire le problème.

Pour reproduire le bug, j'ai besoin de lancer PDF4Teachers dans les mêmes conditions que vous.
Il faudrait que vous m'envoyez :
- votre dossier de données PDF4Teachers (Outils > Débogue > Ouvrir le dossier de données, vous pouvez compresser l'ensemble dans un zip),
- le fichier exporté depuis SACoche, et le fichier d'édition que vous réimportez à chaque fois.

Il serait même mieux si vous pourriez prendre ces fichiers juste après avoir sauvegardé une nouvelle édition, provoquant le bug (2:40 sur votre vidéo).
Envoyez moi alors le chemin dans votre système de fichiers du fichier PDF en question.

Je précise que toutes vos données PDF4Teachers (éléments textuels et éditions) seront partagées, donc il serait préférable que vous m'envoyez ceci par mail : clement.grennerat@gmx.com.
Vous pouvez aussi retirer les éditions des fichiers non concernées si vous voulez (dans le dossier Editions, chaque fichier correspond à une édition, et le nom du fichier est le chemin absolu du PDF correspondant dans le système de fichiers, mais avec les "\" remplacés par "!E!").

**Comment by levaches01** [comment]
Ok, je vous envoie ça dès que possible.
