### ISSUE TITLE
Caractères spéciaux non visibles lors du rendu

### ISSUE THREAD

**Issue by cdaudet** [ClementGre/PDF4Teachers#15]
Bonjour,
Merci pour cette nouvelle version !
Jeudi j'ai repéré un bug sur la version 1.0.3 et je n'ai pas eu le temps de vous l'envoyer avant que cette nouvelle version ne soit disponible. Je viens de tester sur la 1.1.0, le bug persiste.
Il s'agit d'éléments du fichier pdf de la copie qui ne s'affichent pas sur PDF4Teachers.
Je joins des copies d'écran et le fichier pdf de l'élève.

Merci,
Coralie Daudet
[PDF4Teachers_carres.pdf](https://github.com/themsou/PDF4Teachers/files/4569788/PDF4Teachers_carres.pdf)
[KOKILAN Nithushan 20-04.pdf](https://github.com/themsou/PDF4Teachers/files/4569789/KOKILAN.Nithushan.20-04.pdf)

**Comment by grensv** [comment]
Bonjour Coralie,

Merci pour ce retour de bug. Ceci est en effet un peu fâcheux quand ça mène à enlever des points ... 
Nous venons de faire quelques essais avec des polices exotiques (le problème n'existe pas avec les polices les plus courantes), et avons réussi à reproduire le problème avec la police Noteworthy. Je présume qu'on doit pouvoir en trouver quelques autres qui causent ce problème. Je suis preneur pour connaître la police qu'a utilisé cet élève.
Nous avons remarqué que le bug n'apparait qu'à l'affichage, pas à l'exportation car le processus de "rendu" du fichier n'est pas le même. En attendant un correctif, ce type de problème peut être évité en jetant un oeil au fichier exporté lorsqu'il peut y avoir un doute.

Vincent.

**Comment by cdaudet** [comment]
Bonsoir,
Voici la réponse de mon élève. C'est donc bien la même police que vous aviez repérée.
Merci pour votre réponse !
Coralie

> Bonjour madame,
la police que j'utilise s'appelle Noteworthy (c'est une police que j'utilise sur Mac)
Merci

**Comment by ClementGre** [comment]
Bonjour,

malheureusement, ce bug est lié à une dépendance, il est donc très compliqué pour moi de le résoudre directement.
J'ai mis en place un système qui détecte lorsque une erreur se produit avec certains caractères afin de pouvoir alerter l'utilisateur.

![image](https://user-images.githubusercontent.com/51322714/84513156-56a0bc80-acc9-11ea-8823-51ec4de3656d.png)

\- Clément G.
