### ISSUE TITLE
« Un caractère spécial est manquant dans la police…  » alors qu’il est inclus

### ISSUE THREAD

**Issue by pagiraud** [ClementGre/PDF4Teachers#152]
### Prérequis

- [X] J'ai vérifié que le bug n'a pas déjà été rapporté [ici](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] J'ai vérifié que le bug n'est pas un problème utilisateur courant [ici](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Décrivez le bug

Des (les ?) caractères étendus ne sont pas exportés et sont remplacés par un point d’interrogation dans le PDF final alors que le caractère existe dans la police utilisée.

### Pour reproduire

1. Utilisez un caractère comme U+1D49 (e en exposant) pour écrire par exemple XXᵉ siècle.
2. Choisissez une police qui contient ce caractère (Arial, Calibri, Liberation Sans, etc. liste complète [ici](https://www.fileformat.info/info/unicode/char/1d49/fontsupport.htm)). 
3. Exportez le fichier PDF.
4. "Un caractère spécial est manquant dans la police <nom d’une police qui inclut le caractère>."

### Configuration

Kubuntu 22.10

**Comment by ClementGre** [comment]
Cela semble venir du ["Subsetting"](https://fonts.google.com/knowledge/glossary/subsetting) de polices.
(Polices séparées en plusieurs fichiers).

En effet, dans mon dossier ``/usr/share/fonts/truetype/``, j'ai un dossier ``liberation`` et un dossier ``liberation2``, où seul ``liberation2`` contient tous les caractères. ``liberation`` est une version allégée.

Le problème disparaît si je remplace les liberation par liberation2 dans ``/home/clement/.local/share/PDF4Teachers/sysfonts_cache.yml``.
(J'imagine que c'est la même chose pour Arial et autre).

Il faudrait que PDF4Teachers puisse prendre en compte ces particularités. En acceptant qu'une même police ait plusieurs fichiers liées à un même style.

En attendant que je règle le problème, il serait possible d'utiliser des polices non divisées en plusieurs sous-fichiers, ou des polices par défaut compatibles, comme Noto Serif.

**Comment by ClementGre** [comment]
Est-ce que vous pouvez vérifier pourquoi vous avez ce même problème pour Arial et Calibri (rechercher le nom de la police et identifier si vous avez plusieurs fichiers de police ayant le même nom de police "Font Family") ?

**Comment by pagiraud** [comment]
En fait, après vérification de mes fichiers de police (et non consultation de la documentation sur Internet), je vois que ni ma version d’Arial ni ma version de Calibri ne disposent du caractère ᵉ … Il n’y a donc pas de problème de ce côté-là. J’ai installé Calibri manuellement (fichier trouvé sur Internet) et j’ai installé Arial via le paquet ttf-mscorefonts-installer d’Ubuntu. Donc pas de problème pour ces deux polices en réalité…

**Comment by ClementGre** [comment]
D'accord. En fait le subsetting ne semble pas être utilisé à l'échelle d'un OS, et à part pour le problème de libération (où il faudrait alors supprimer le dossier ``liberation`` et ne garder que ``liberation2``), il ne me semble pas nécessaire d'ajouter ce support pour le moment.
Merci pour le rapport !
