### ISSUE TITLE
Can't start app om Mac OS Catalina (v10.15.7)

### ISSUE THREAD

**Issue by tommy-rypi** [ClementGre/PDF4Teachers#153]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

I have tried starting the app several times (latest version), and it just hangs after selecting language.

### To Reproduce

1. Start app.
2. Select language.
3. It hangs.

**Comment by ClementGre** [comment]
Bonjour,
vous pouvez essayer de supprimer vos données de PDF4Teachers, qui peuvent poser problème lors du démarrage.

Rendez vous dans ``/Users/.../Library/Application Support/PDF4Teachers``. Puis tentez de supprimer ou de déplacer le dossier PDF4Teachers.

Cela vous fera repartir comme si c'était votre première installation de PDF4Teachers, et devrais résoudre le problème.
