### ISSUE TITLE
Point d'insertion des éléments décalé lors de l'ajout via le menu contextuel des pages

### ISSUE THREAD

**Issue by grensv** [ClementGre/PDF4Teachers#154]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Lors de l'insertion d'une note (outil barème) à l'aide du menu contextuel, il faudrait que le point d'insertion soit le point du clic droit.
Le point d'insertion est en fait mauvais car il correspond à la position du pointeur lors de la sélection dans le menu contextuel déroulant des propositions de note (Une note faible sera donc insérée plus haut qu'une note élevée)

### To Reproduce

1. créer un barème
2. placer une note avec clic droit -> deuxième clic droit sur la note à placer -> choix de la valeur dans le menu contextuel déroulé.
3. On constate que le note n'est pas placée à l'emplacement du premier clic droit.

### Desktop

OSX 10.14.6

**Comment by ClementGre** [comment]
En effet, cela arrive dès que la souris sort du menu contextuel et survole la page. Le dernier point de la souris sur la page est alors actualisé alors qu'il ne devrait pas l'être.

Cela arrive aussi avec les éléments textuels ou graphiques (images et éléments vectoriels).

Le problème est maintenant réglé et les éléments seront correctement positionnés.

Merci pour le rapport de bug !
