### ISSUE TITLE
Selection de proposition automatique des éléments texte

### ISSUE THREAD

**Issue by grensv** [ClementGre/PDF4Teachers#155]
### Prérequis

- [X] J'ai vérifié que cette fonctionnalité n'a pas déjà été suggéré [ici](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+label%3A%22enhancement%22+)

### Votre demande de fonctionnalité est-elle relative à un problème ? Décrivez.

Pour valider une proposition d'élément textuel en surbrillance dans le panneau des éléments texte, il faut le sélectionner avec les flèches bas / haut puis entrée.
Si on clique dessus, ça insère l'élément, et laisse le début d'élément commencé d'être saisi, ce qui oblige de le supprimer ensuite

### Décrivez la solution que vous aimeriez

Quand on clique sur une proposition d'élément en surbrillance, il est inséré EN REMPLACEMENT de l'élément en cours de saisie

**Comment by ClementGre** [comment]
Il est possible d'ajouter un élément de la liste en remplaçant l'élément sélectionné en faisant Clic + Ctrl/Cmd.

Il est en effet peut-être propice de proposer ce comportement par défaut pour les éléments en surbrillance (contour bleu).
C'est ce que j'ai fait pour la prochaine version, mais peut-être que c'est un peu étrange de remplacer l'élément si on clique sur un élément en surbrillance, mais que si on clique un élément plus bas dans la liste, il n'y ait pas de remplacement. Celui qui déplace sa souris ne va pas forcément cliquer sur l'élément en surbrillance, et le comportement sera alors différent.

À voir si ce n'est pas trop perturbant à l'usage. Peut-être veut-il mieux mettre en avant d'avantage l'utilisation de Ctrl/Cmd pour remplacer l'élément sélectionné dans la documentation ou via des popups d'information.

**Comment by ClementGre** [comment]
Après réflexion, j'ai annulé le code du dernier commit car on ne peut pas détecter si le correcteur souhaite modifier l'élément courant, ou s'il a terminé l'élément et souhaite en ajouter un nouveau.
Effectuer un remplacement uniquement si l'élement est en surbrillance poserait des problèmes de consistence et éventuellement le même problème si le nouvel élément est semblable à l'ancien.

Le mieux reste d'utiliser ``Ctrl + Clic`` sur Windows ou ``Cmd + Clic`` sur Macos.
