### ISSUE TITLE
Données perdues

### ISSUE THREAD

**Issue by bricecc** [ClementGre/PDF4Teachers#156]
Bonjour,

J'ai par erreur effacé une édition sur plusieurs fichiers (les fichiers ont disparu de ma liste à gauche) et je me demandais s'il y avait un moyen de retrouver les données ?

J'imagine que pdf4teachers a un dossier de travail dans lequel il stocke ces données ?

Je travaille avec Mac OS.

Merci d'avance pour votre aide

**Comment by grensv** [comment]
Bonjour Brice,

Je ne suis pas sûr de comprendre pourquoi les fichiers PDF n'apparaissent plus dans le panneau des fichiers. Il suffit éventuellement de les recharger si ils ont été enlevés de la liste. Ce problème peut aussi être lié à un déplacement des fichiers pdf.
Si les fichiers d’edition ont été conservés, avec la version 1.4 sous OSX, ils sont dans le dossier ~/Library/Application Support/PDF4Teachers/editions (fichiers .yml)
Comme c’est un dossier caché, dans le finder on peut y aller avec shift - CMD - G puis taper le chemin ~/Library et naviguer à la main.

Il est possible de charger directement une édition dans PDF4Teachers par 2 méthodes :
- Outils -> Editions des documents du même nom (si un fichier d’edition existe pour ce nom de document, mais que le chemin du document a changé)
- Outils -> Exporter / importer des Editions / barèmes -> Importer une / des editions

Vincent.
