### ISSUE TITLE
Police non reconnue Linux Mint

### ISSUE THREAD

**Issue by jlgenet** [ClementGre/PDF4Teachers#157]
### Prerequisite

- [X] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

### Describe the bug

Bonjour
J'ai un Pb de polices non reconnues sur une ordi Linux Mint ':
Kernel: 5.15.0-60-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: MATE 1.26.0 wm: marco
    dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

J'ai beau changer de police, elle ne change pas dans le texte.
Cela fonctionne au niveau des notes (voir copie écran)
Je ne reproduis pas cela sur un deuxième ordi utilisé précédemment et sur lequel cela fonctionnait (pas dispo d'où le changement de machine)
Merci de vos suggestions
Jean-Luc

### To Reproduce

1. 
2. 
3. 
4. 

### Screenshots

![image](https://user-images.githubusercontent.com/8921045/219328065-d16a2bc3-22f8-4c48-8d9e-452ca5e3cbf2.png)

### Desktop

Kernel: 5.15.0-60-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: MATE 1.26.0 wm: marco     dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

**Comment by ClementGre** [comment]
Bonjour @jlgenet,

vous ne pouvez pas changer de police d'écriture car vous êtes en mode LaTeX (permettant d'écrire des formules mathématiques).

Normalement, le mode LaTeX s'active/désactive en entrant ``$$`` dans le champ de texte. (Tout caractère compris entre deux ``$$`` sera traité comme du code LaTeX).

Ici, vous êtes en mode LaTeX sans avoir entré ``$$``. C'est que le mode LaTeX par défaut est activé dans les paramètres.

Vous pouvez donc régler ce problème en cliquant à nouveau sur LaTeX dans quelque chose comme Mode d'écriture par défaut dans les paramètres, pour désactiver le mode LaTeX par défaut et régler votre problème.

\- Clément Grennerat

**Comment by jlgenet** [comment]
Merci (pour la réponse rapide et pour pdf4teacher)
J'avasis choisis le mode libreoffice... En  en ne sélectionnant ni l'aun ni l'autre j'avais $$&& en début de texte, j'ai supprimé && et ça roule.
Jean-Luc GENET
