### ISSUE TITLE
Erreur d'exportation

### ISSUE THREAD

**Issue by sriviere28** [ClementGre/PDF4Teachers#158]
Bonjour,
Pour commencer un immense merci pour votre travail qui m'a déjà rendu de nombreux services
Malheureusement, depuis plusieurs semaines déjà, je ne peux plus utiliser votre logiciel : dès que j'ajoute le moindre texte sur le PDF et que je demande l'exportation ("Exporter (Régénérer le PDF)") j'obtiens le message d'erreur ci-joint : 
![Message erreur PDF4Teachers réduit](https://user-images.githubusercontent.com/126161346/220892650-5d608011-b50f-47ac-a97d-0debfc44e84e.jpg)
J'ai tenté de désinstaller et réinstaller le logiciel, attendu la mise à jour suivante... sans succès.
Auriez-vous une idée de l'origine de ce problème ?
Merci d'avance pour votre retour.

**Comment by ClementGre** [comment]
Bonjour,
pouvez-vous m'envoyer une capture d'écran de la fenêtre  qui apparaît lorsque vous pressez ``Ctrl+Alt+C``, afin de voir les détails du problème.

**Comment by sriviere28** [comment]
Je suis désolée mais je ne peux rien vous transmettre, aucune fenêtre n'apparaît lorsque je réalise cette combinaison de touches.
Il ne se passe rien du tout.

**Comment by ClementGre** [comment]
Bonjour, désolé de l'imprécision, essayez de presser ``Ctrl+Alt+C`` après avoir quitté le dialogue d'erreur, en ayant la fenêtre principale de PDF4Teachers en avant plan.

**Comment by sriviere28** [comment]
C'est moi qui suis désolée de vous prendre du temps !
Voici la copie d'écran :
![Logs](https://user-images.githubusercontent.com/126161346/220935876-08ff3e1b-64da-426e-8fde-c6641ae9add4.jpg)

**Comment by ClementGre** [comment]
Ce problème est lié à la police d'écriture que vous utilisez.
Pouvez-vous me donner le nom de cette police d'écriture, et essayer de la changer pour voir si cela résous le problème ?

**Comment by sriviere28** [comment]
Merci beaucoup !
C'était la police CAMBRIA.
J'avais en effet changé de police une fois pour me rapprocher de celle du document et je n'avais pas du tout fait le rapprochement quand j'ai rencontré le problème lors de l'exportation.
Mais je viens de faire un essai avec la police Open Sans et même en la combinant avec des formules mathématiques et tout s'est exporté sans aucune difficulté ! Vraiment un immense merci pour votre aide et votre disponibilité ! _(Je regrette juste de ne pas m'être tournée vers vous plus tôt.)_
Votre logiciel m'est vraiment très utile (et régulièrement) dans mon métier d'enseignante. Bravo (et encore merci !) pour ce travail !

**Comment by ClementGre** [comment]
D'accord, je testerai d'exporter avec la police Cambria pour tenter de régler ce bug.
Je suis content que PDF4Teachers vous soit utile !
Merci !
