### ISSUE TITLE
Icône app sous Mac non visible

### ISSUE THREAD

**Issue by jdelmas95** [ClementGre/PDF4Teachers#16]
Bonjour,

Serait-il possible de modifier l'icône qui apparaît dans le Dock, sur Mac ? Il semble qu'il s'agisse de l'icône par défaut et pas de l'icône de l'application.

Merci d'avance.

<img width="316" alt="Capture d’écran 2020-05-03 à 12 15 17" src="https://user-images.githubusercontent.com/32643240/80911689-40055e00-8d38-11ea-8747-3dcc9157263c.png">

**Comment by jdelmas95** [comment]
Corrigé dans la 1.10 ;-)

**Comment by themsou** [comment]
Bonjour,

la version 1.1.1 résous le bug #14, mais elle ramène celui-ci en contrepartie.
Cela est dû à la manière que nous utilisons pour créer le dossier .app, nous faisons tout notre possible pour essayer de régler ce problème.
Ce bug n'est en réalité pas un problème d'icône, c'est l'application qui a un "élément" dans le dock différent du lanceur. Normalement, si vous épinglez le lanceur dans votre dock, vous remarquerez que l'application ajoute un second élément dans le dock après son lancement.

\- Clément G.

**Comment by ClementGre** [comment]
Bonjour,
ce problème (ainsi que le nom de l'application invalide dans la barre de menus) a été résolu pour la version 1.3.0.
Le bug #14 de Java n'a pas été réglé (ce qui aurait permis de réutiliser le packager par défaut de Java). Le .app est toujours créé à la main, quelques paramètres ont étés modifiés pour résoudre ce problème.

Merci à vous,
Clément Grennerat.
