### ISSUE TITLE
correction sur Auto-multiple-choice

### ISSUE THREAD

**Issue by macapus** [ClementGre/PDF4Teachers#160]
Bonjour , je me permets de vous poser la question concernant la correction avec AMC . Les PDF obtenus avec PDF4teacher n'apparaissent pas avec les surcouches de correction dans AMC. Il faut que j'exporte en TIFF dans Apercu sur Mac pour obtenir une vision correcte dans la saisie de AMC. Pourrait on avoir une option pour un export direct en TIFF dans PDF4teacher ou un pdf "aplati" , je ne sais pas si c'est le terme correct. 
Ou peut être ai-je loupé une étape ?

**Comment by ClementGre** [comment]
Bonjour,
PDF4Teachers peut bien exporter un document sous format image (png), mais les annotations ne seront pas présentes.
Si vous souhaitez avoir les annotations, vous devez d'abord exporter en PDF puis ouvrir le fichier exporté et l'exporter en image (boutons rouge en haut à gauche de chaque page, ou clic droit en mode édition des pages).
Si vous souhaitez avoir un PDF à la fin, il faudra reconvertir ces images en document PDF.
Malheureusement, PDF4Teachers ne supporte pas l'export PDF sous forme d'image dans le PDF, car cela a en général peu d'intérêt par rapport à la méthode actuelle qui rend le PDF plus accessible et dans lequel on peut zoomer sans perte.

C'est vrais que la correction mixte avec AMC n'est alors pas très commode.
Vous pouvez peut-être essayer de corriger d'abord avec AMC et seulement après avec PDF4Teachers.

L'idée originale était de partir dans ce sens, avec une possibilité d'exporter les notes AMC sous forme de notes PDF4Teachers ce qui permettait de centraliser les résultats :
https://project.auto-multiple-choice.net/issues/733#note-7
Cela n'a malheureusement pas été fait du côté d'AMC. Le mieux reste donc de faire comme je vous ai dit.

**Comment by macapus** [comment]
ok, merci , je pense faire un dossier de conversion automatique alors pour simplifier le processus.
