### ISSUE TITLE
Nouvelle fonctionnalité : Transformation Image(s) -> PDF

### ISSUE THREAD

**Issue by jdelmas95** [ClementGre/PDF4Teachers#17]
Bonjour,

Il serait fort intéressant de pouvoir sélectionner indifféremment un PDF ou une image (voire un ODT/DOC) qui serait converti immédiatement en PDF pour l'intégrer dans l'appli.

Quand les professeurs (pas trop à l'aise) reçoivent des copies numériques de leurs élèves au format image, PDF (voire ODT/DOC), il serait super de pouvoir les intégrer tout de même, sans que le professeur n'ait besoin de lui même convertir les images en PDF.

Merci en tout cas pour cette application dont je fais beaucoup de publicité sur Twitter !

**Comment by grensv** [comment]
La génération d'un ou plusieurs PDF à partir d'un dossier d'images ou sous-dossiers d'images est au menu de la prochaine version mineure (1.2).
En attendant, voir mon post sur la génération automatisée d'un lot de PDFs à partir de dossiers d'images : https://github.com/themsou/PDF4Teachers/issues/13
