### ISSUE TITLE
Mémoriser le niveau de zoom lors du passage d'un document à l'autre.

### ISSUE THREAD

**Issue by yangauthier** [ClementGre/PDF4Teachers#170]
### Prerequisite

- [X] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.0%22+label%3A%22enhancement%22+)

### Is your feature request related to a problem? Please describe.

Lorsque je passe d'un pdf au suivant, mon facteur de zoom revient par défaut à la largeur de la page et je suis obligé d'ajuster le zoom pour chaque document, ce qui est très fastidieux sur de gros paquets de copies (je n'aime pas que ce soit trop zoomé sur le document).

### Describe the solution you'd like

Il serait pratique de pouvoir définir un facteur de zoom pour l'ensemble des documents ouverts dans une liste, par exemple en faisant automatiquement hériter le document auquel on passe du même facteur de zoom que celui que l'on vient de corriger.

### Describe alternatives you've considered

Une autre possibilité serait de spécifier au sélecteur de niveau de zoom que l'on souhaite appliquer le réglage à toutes les pages.

**Comment by ClementGre** [comment]
Le comportement par défaut lors de l'ouverture d'un document PDF est d'adapter le zoom à la largeur des pages.

Il serait en effet intéressant de garder le même niveau de zoom lors du passage d'un document à l'autre.
Je viens de mettre en place ce comportement qui sera disponible dans la version 1.4.1.

**Comment by yangauthier** [comment]
Merci Clément, et merci aussi à vous 2 pour ce très bel outil qui facilite grandement la vie des correcteurs :) Bonne journée.
