### ISSUE TITLE
Boite de dialogue trop petite

### ISSUE THREAD

**Issue by ysalmon** [ClementGre/PDF4Teachers#171]
Bonjour,

sous 1.4.1, la boite de dialogue d'export de l'édition est bien trop petite  :
![Screenshot_20231031_171512](https://github.com/ClementGre/PDF4Teachers/assets/536850/1bce13a3-0b64-4f94-a3bc-991583fd0024)

En fait, ça ne semble pas spécifique à cette boite : la boite qui demande s'il faut sauvegarder l'édition courante s'affiche comme ça aussi, parfois (mais pour l'export, au contraire, elle est le plus souvent rabougrie, et de temps en temps on l'a avec une taille adaptée).

**Comment by ClementGre** [comment]
Ceci arrive-t-il même quand l'interface n'est pas zoomé, ou s'agit-t-il du même problème que dans #121 et #144 ?

**Comment by ClementGre** [comment]
J'ai pu reproduire le problème sur Kubuntu 21.10.
Il semble qu'en déclarant les fenêtres comme redimentionnables par l'utilisateur, le problème est résolu. Cela permettra de plus de redimentionner les dialogues en cas d'éventuels problèmes futurs.

Vous pouvez tester ce nouveau build pour vérifier que tout va bien :
https://pdf4teachers.org/data/PDF4Teachers-Linux-1.4.1-sn1.deb.
