### ISSUE TITLE
Démonter un livret : rotation non prise en compte.

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#179]
Bonjour.

J'ai scanné des copies doubles (sur les feuilles blanches d'examen). Lorsque j'utilise l'outil "Démonter un livret", Pdf4Teacher me coupe mes pages horizontalement (ce qui me donne le haut de la copie double et le bas de la copie double) au lieu de les couper verticalement (pour avoir la page de gauche et la page de droite). J'ai tenté de faire une rotation avant mais même soucis.

Serait-il possible de choisir le sens de découpe ?

Merci.

**Comment by ClementGre** [comment]
Bonjour,
Il s'agit en effet d'un bug lié au fait que la rotation des pages n'est pas prise en compte lors du démontage d'un livret.
La seule option qui pourrait répondre à votre besoin en attendant la correction de ce bug et la publication d'une nouvelle version de PDF4Teachers serait de générer un nouveau document PDF avec les pages tournées dans que cela se présente sous la forme d'une information de rotation de la page.
Pour cela, vous pouvez exporter une capture de votre document au format image (En mode édition des pages, Clic droit > Capturer, ou bouton capturer à gauche des pages puis "Capturer toutes les pages du document"). Cette fonction permet de générer des images png à partir de chacune des pages (en tenant compte de la rotation). Ces images peuvent ensuite être converties en un nouveau document avec la fonction convertir. Ce nouveau document aura donc les pages tournées de façon native et la fonction de démontage d'un livret fonctionnera comme attendu.

Cette solution est laborieuse mais devrait fonctionner en attendant une mise à jour.
Merci à vous.

**Comment by DegrangeM** [comment]
Pas de soucis pour mon document, je suis passé par l'excellent pdf arranger pour découper les images en deux, j'ai juste du réordonner les pages après coup :)

C'est surtout pour gagner du temps pour les prochaines fois, mais rien d'urgent :)

**Comment by ClementGre** [comment]
Le problème a été résolu dans le code source et la rotation sera prise en compte lors de la création ou du démantèlement d'un livret dans les prochaines versions de PDF4Teachers.
Merci à vous !
