### ISSUE TITLE
Nouvelle fonctionnalité : Rotation des pages

### ISSUE THREAD

**Issue by jdelmas95** [ClementGre/PDF4Teachers#18]
Bonjour,

Quand les élèves envoient leur travail, les fichiers arrivent parfois orientés à 90 ou 180°.

Serait-il possible de pouvoir : 
- orienter une seule page ;
- orienter tout un document en une seule fois ?

Merci d'avance.

**Comment by grensv** [comment]
Fonctionnalité prévue dans la prochaine version majeure (1.2). En attendant, il faut se contenter d'orienter les pages avant avec un autre éditeur PDF 🥵

**Comment by ClementGre** [comment]
Fonctionnalité implémenté dans [#7a2c304](https://github.com/ClementGre/PDF4Teachers/commit/7a2c304032161ae49c35b82a59e01d7ccc71a29f).
