### ISSUE TITLE
Sélection d'un élément précédent durant saisie : remplace au lieu d'ajouter

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#180]
Bonjour.

Si l'on double clic sur la page, commence à écrire "Err" puis sélectionne à gauche "erreur de signe" dans les éléments précédents, le logiciel laisse "Err" à l'endroit où on avait double cliqué, puis ajoute un "erreur de signe" à gauche.

Je pense qu'il serait plus logique de remplacer le "Err" pas "erreur de signe".

Merci.

**Comment by ClementGre** [comment]
Bonjour,
La fonctionnalité d'ajout d'un élément depuis une liste a déjà été implémentée depuis la version 1.3.0 (C.f #84).
Dans la documentation :
> Il est possible d’ajouter un élément depuis une liste en remplacement de l’élément actuellement sélectionné en appuyant sur Ctrl (ou Cmd).

Peut-être que des messages d'astuce devraient être ajoutés pour rendre cette fonctionnalité plus visible.
Merci à vous.

**Comment by DegrangeM** [comment]
Merci ! Ca fonctionne et je ne connaissais pas ce raccourci !

Après y a -t-il un cas où un enseignant voudrait ne pas remplacer le texte ?
