### ISSUE TITLE
Feuille blanche et division par couleur

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#181]
Bonjour.

Pour simplifier la division d'un pdf, j'ai ajouté de page blanche au lieu de sélectionner les pages à diviser (j'ai perdu par erreur plusieurs fois la sélection). Je pensais que je pourrais ensuite couper automatiquement le pdf avec la division par couleur en mettant le réglage à l'extrême, mais, sauf erreur de manipulation de ma part, cela ne fonctionne pas.

Serait-il possible de faire en sorte que cette division par couleur fonctionne avec les pages blanches lorsque le réglage est poussé à l'extrême (d'ailleurs ça manque d'une indication pour savoir dans quel sens est le réglage de sensibilité), ou bien ajouter dans les outils une division par page blanche.

Merci.

**Comment by ClementGre** [comment]
Bonjour,
Si vous souhaitez diviser un document en spécifiant les pages manuellement, vous pouvez sélectionner les première page de chaque nouveau document (mode édition des pages, Ctrl+Clic pour ajouter à la sélection), puis vous pouvez utiliser la fonction Outils > Outils de PDF > Diviser le document PDF selon la sélection (puis cocher la case pour ajouter les pages sélectionnées en début de document si elles sont à préserver).

Mettre la sensibilité à 100% ne fonctionne pas car une égalité stricte était faite entre la différence de couleur et la sensibilité. J'ai remplacé cette égalité par une égalité large et le 100% devrait fonctionner dans de futures versions de PDF4Teachers.
En attendant, vous pouvez mettre la sensibilité à 99%.
Dans le cas ou vous souhaiteriez modifier la séparation qui a été faite par couleurs, comme la détection de couleur sélectionne automatiquement les pages séparatrices, vous pouvez toujours fermer le dialogue, modifier la sélection des pages séparatrices (Ctrl+Clic), puis utiliser la fonction de séparation par sélection, ce qui revient au même. 

Merci à vous.

**Comment by DegrangeM** [comment]
Disons que j'avais essayé par sélectionner mais ayant un grand nombre de pages ... j'ai du lâcher par erreur la touche ctrl vers la fin puisque je n'avais plus que 3 pages sélectionner sur 26. D'où ma tentative de passer par quelque chose de moins dangereux :D

Merci pour la correction de la sensibilité.
