### ISSUE TITLE
Outil de division d'un document : option pour conserver le barème

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#182]
Bonjour.

Serait-il possible de conserver le barème lors d'une division d'un document (ou bien ajouter une option à cocher).

Merci.

**Comment by ClementGre** [comment]
Bonjour et merci de votre suggestion.

J’ai ajouté le support de la conservation de l’édition lors le la division d’un document. L’édition sera divisée de manière à ce que chaque élément reste sur sa page originale. Les tableaux de compétences et les notes chiffrées seront dédoublés sur tous les sous-documents. Les notes sont réinitialisées si elles n’appartiennent pas aux pages originales du sous-document. La copie du barème aura donc bien lieu.

Cela se configurera via une case à cocher sur la fenêtre de division, et sera disponible dans la prochaine version de PDF4Teachers.
Merci a vous !
