### ISSUE TITLE
PDF4teachers-formulaire

### ISSUE THREAD

**Issue by spatangue** [ClementGre/PDF4Teachers#184]
Bonjour,
merci tout d'abord pour cet outil efficace pour annoter des copies pdf et faire diverses petites manip bien pratiques (remettre les pages à l'endroit et dans l'ordre ou enregistrer les annotations redondantes !!)
Par contre, j'avais trouvé intéressant de donner à mes élèves des formulaires avec champs à remplir : cela uniformise la mise en page et fait gagner du temps sur la lecture des réponses. 
Par contre, je viens de m'apercevoir que les **formulaires pdf apparaissent vides dans PDF4Teachers** !! (il ne s'agit pas d'une erreur, ce même fichier est tout à fait complété dans Foxit ou Acrobat reader). C'est bien dommage... Si une solution pouvait être trouvée, ce serait extra !
Je suis bien incapable de savoir si c'est possible ou non d'arranger cela !
Merci.
Bien cordialement, Spat

**Comment by l-leroux** [comment]
Bonjour,
je réponds comme simple utilisateur ayant pas mal cherché autour des formulaires pdf il y a quelques années (comme beaucoup) : j'ai personnellement abandonné en contexte scolaire.
Pourquoi ? les formulaires pdf sont (ou étaient en 2021, mais 3 ans c'est long en informatique...) traités par les différents logiciels de manières différentes. En contexte entreprise où vous maitrisez le logiciel utilisé par les collègues, çà marche, mais en contexte scolaire, entre les navigateurs, les PC, les mac, les ios, les android et la ribanbelle de logiciels utilisés pour lire les pdf, sur un amphi de 200 étudiants, le taux de fichiers à reprendre était tel que j'ai laissé tomber.
Pdf4teacher permet aux élèves d'envoyer des photos qui seront transformées par lots en pdf que vous pourrez annoter...
Si vous avez une expérience différente, je suis preneur !
Cordialement,

**Comment by spatangue** [comment]
Bonjour,
je vous réponds également... Vous avez sans doute raison car selon les logiciels utilisés par les élèves, il y a parfois des bugs incompréhensibles (par exemple, le formulaire se remplit normalement, mais lors de l'enregistrement, il reste vide !) 
Ceci dit, avec 2 ou 3 ajustements et conseils (par ex tester l'enregistrement en ayant rempli qu'un seul champ) en début d'année, cela fonctionne plutôt bien (je crée mes formulaires avec LibreOffice Writer). Quelques élèves seulement m'envoient une photo de leur travail car ils n'arrivent pas à faire autrement et je leur apprends à les convertir eux-mêmes en PDF (juste parce que le logiciel de communication que nous utilisons -Pronote- n’accepte que des fichiers de faible poids) Je travaille de cette manière pour le suivi des devoirs maison et j'en suis assez satisfaite.

Maintenant pdf4teachers permet, en plus d'annoter et de faire pivoter des pages (ce que je sais faire de façon assez simple avec différents lecteurs PDF), d'automatiser les notations, fonction que je n'ai trouvé nulle part ailleurs, et d'enregistrer rapidement des annotations redondantes (c'est possible via Foxit par exemple en utilisant des tampons, mais avec trop de clics pour être vraiment efficace pour mon utilisation). Donc, j'aimerais bien passer à pdf4teachers...
D'autre part, je viens de tester à nouveau des formulaires remplis via pdf4teachers, et ça fonctionne aujourd'hui !! Même celui que j'ai ouvert l'autre jour, corrigé via Foxit reader comme à mon habitude, apparait dans pdf4teachers avec non seulement mes annotations, mais également les réponses élève qui n'étaient pas apparentes. C'est à n'y rien comprendre !
Je vais essayer la correction via pdf4teachers pour ces devoirs...
Cordialement, Spat

**Comment by ClementGre** [comment]
Bonjour, les formulaires devraient normalement s’afficher correctement, ce n’est cependant pas quelque chose que je maîtrise totalement, le rendu des PDF étant fait par une bibliothèque tierce. Si vous retombez sur un formulaire qui ne s’affiche pas correctement, vous pouvez me l’envoyer à clement.grennerat@free.fr pour que j’investigue le problème. En attendant, je ferme l’issue.
Merci à vous.
