### ISSUE TITLE
Pages exportées ne comportant pas les annotations

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#185]
Bonjour.

Je suis tombé face à un bug surprenant : sur plusieurs copies d'élèves, je me retrouve avec une page sans annotation. Les autres pages ont bien les annotations, et lorsque j'ouvre la copie dans pdf4teacher j'ai bien les annotations, mais lorsque j'exporte le pdf, je me retrouve avec une page vide. J'ai essayé de réexporter la copie mais le bug se produit toujours.

Je peux éventuellement envoyer en privé (à quelle adresse email ?) un exemple de copie posant problème, mais que dois-je envoyer exactement ? Je suppose que le pdf exporté ne suffira pas.

**Comment by DegrangeM** [comment]
Je viens de me rentre compte de quelque chose : il s'agit à chaque fois de la page 4 (et ce n'est pas toujours la dernière page).

A savoir que j'ai réordonné les pages, à la base la page 4 était en page 1 et je l'ai déplacé en page 4, mais pourtant je n'ai pas de soucis avec les pages 8 (qui était à la base en page 5 et que j'ai déplacé en page 8).

**Comment by ClementGre** [comment]
Ceci est en effet intriguant.
Pouvez-vous me partager le document qui pose problème à l'adresse clement.grennerat@free.fr, ainsi que l'édition associée, exportable en fichier .yml via Outils > Exporter/inporter des éditions/barèmes > Exporter les éditions / l'édition > Exporter pour ce document.
Ceci devrait me permettre de mieux identifier le bug.

**Comment by DegrangeM** [comment]
(juste au cas où que mon mail soit passé dans les spams, je précise ici que c'est envoyé, mais bien évidemment rien d'urgent)

**Comment by ClementGre** [comment]
Vous avez bien fait de me le dire ici car votre mail était bien dans mes spams...
Il s'agit bien d'un bug de PDF4Teachers qui positionne mal les éléments pour les pages qui sont à la fois tournées et recadrées, le recadrage étant dû à l'action de démontage d'un livret.

J'ai corrigé ce bug, qui ne devrait plus arriver dans les prochaines versions.

En attendant, ce problème peut être contourné en régénérant un PDF avec l'outil "Capturer toutes les pages du document PDF" puis en convertissant les images en un nouveau document, ce qui est assez fastidieux, mais qui devrait fonctionner si vous le faites avant démontage du livret (cela n'éliminera pas le recadrage, mais éliminera la rotation des pages).

**Comment by DegrangeM** [comment]
Super, merci :)
