### ISSUE TITLE
Ajout d'annotations vocales 

### ISSUE THREAD

**Issue by sebb916** [ClementGre/PDF4Teachers#186]
### Prérequis

- [X] J'ai vérifié que cette fonctionnalité n'a pas déjà été suggéré [ici](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.1%22+label%3A%22enhancement%22+)

### Votre demande de fonctionnalité est-elle relative à un problème ? Décrivez.

Bonjour,
Serait-il envidageable d'ajouter une fonction d'enregistrement audio pour incorporer une note vocale dans les documents ?
Merci

**Comment by ClementGre** [comment]
Bonjour,
Cette fonctionnalité avait déjà été proposée dans #41, et abandonnée principalement pour des raisons techniques (peu de logiciels supportent la lecture d'annotations audio et alourdissement des documents, [voir ici](https://github.com/ClementGre/PDF4Teachers/issues/41#issuecomment-731313809)).


Cette issue avait mené au support de liens web dans PDF4Teachers.
Je ne pense pas que cette fonctionnalité apparaîtra un jours dans PDF4Teachers. Si vous tenez aux annotations audio, vous pouvez partager un document audio joint au PDF, ou en hébergeant le fichier audio en ligne, vous pouvez inclure son lien sur le PDF.

**Comment by sebb916** [comment]
Merci beaucoup pour votre réponse.
Je ferai avec un logiciel tiers.
Bonne journée

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
