### ISSUE TITLE
Ability to change page geometry to enlarge place for comments

### ISSUE THREAD

**Issue by pagiraud** [ClementGre/PDF4Teachers#189]
### Prerequisite

- [X] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.4.1%22+label%3A%22enhancement%22+)

### Is your feature request related to a problem? Please describe.

It’s a bit frustrating when I want to add a long comment beside the text: the margins are often narrow and I just don’t have enough place.

### Describe the solution you'd like

So it would be nice if PDF4Teachers included a way to enlarge right and/or left margins (for the document or on a page per page basis) by changing the page geometry. It would render a bit like documents with comments in LibreOffice Writer for instance.

### Describe alternatives you've considered

I know I can add blank pages between pages, but it’s not the same.

**Comment by ClementGre** [comment]
This is a great idea! I'll look into it shortly.

**Comment by ClementGre** [comment]
I developed this feature that will be available in the next release.

It is possible to add margin to a page / all the pages / a selection of pages from:
- menu Tools > PDF Tools > Add margins;
- the red buttons on the top right corner of pages;
- the context menu of pages in the Page edit mode.

The margin can be specified as absolute (in the page coordinate space), or relative to page width. The interface is not yet translated, but here is a preview of the window:
<img width="516" alt="image" src="https://github.com/ClementGre/PDF4Teachers/assets/51322714/41935fde-474e-4164-a59b-124fff58f123">

A negative margin can be specified for cropping, but cropping on a single page can also be done with a zone selection (like for taking a screenshot of a page zone) from:
- the red buttons on the top right corner of pages;
- the context menu of pages in the Page edit mode.


When cropping or adding margins to a page, elements are correctly moved and scaled to stay as close as possible to their original location.
These operations can be undone with Ctrl/Cmd+Z or with Edit > Undo.

Thank you for this great idea!
