### ISSUE TITLE
Nouvelle fonctionnalité : Redimensionnement annotation textuelle

### ISSUE THREAD

**Issue by lemarn** [ClementGre/PDF4Teachers#27]
Bonjour
J'ai utilisé avec beaucoup d'intérêt votre application( sous Mac OS 10.14.6). Cela fonctionne très bien. Par contre j'ai remarqué qu'il n'était pas possible de redimensionner les annotations textuelles. Cela oblige à créer plusieurs éléments si on veut mettre un long commentaire.
J'attends aussi avec impatience l'ajout d'éléments graphiques.
Arnaud Lemaitre

**Comment by grensv** [comment]
Bonjour Arnaud,
A la base, nous voulions justement éviter la perte de temps liée au redimensionnement des éléments comme  par exemple dans Aperçu (que j'utilisais avant pour annoter des copies). Dans PDF4Teachers, l'idée est donc de saisir des retours à la ligne, pour limiter la longueur des annotations. Il faut reconnaître que ceci est parfois pénible quand on place un message de 4 ou 5 lignes.
Il serait donc peut-être utile d'ajouter uniquement un redimensionnement horizontal, qui insèrerait automatiquement les sauts de ligne, et que ceci se fasse sans manipulation dès que l'on atteint 90% de la largeur de la page.
Vincent.

**Comment by lemarn** [comment]
Oui cela serait suffisant. Merci

**Comment by ClementGre** [comment]
Bonjour,
J'ai travaillé sur cette question et je ne vois que deux moyens de faire cela :

- Il est tout d'abord possible de limiter la largeur des éléments textuels directement au niveau de la saisie, en insérant des retours à la ligne lorsque que l'élément est trop long. C'est cette méthode que j'ai choisie pour l'instant mais on atteins assez vite ses limites : on ne peut pas différencier les retours à la ligne entrés par l'utilisateur et ceux entrés automatiquement,
  - une solution est d'ignorer les retours à la ligne entrés par l'utilisateur en maximisant la longueur de chaque ligne, mais cela reviens à supprimer la fonctionnalité de retours à la ligne.
  - une autre solution, qui est celle que j'ai choisie, est de garder les retours à la ligne de l'utilisateur, mais l'algorithme, ne pouvant faire la différence entre les différents retours à la ligne, va garder tous les retours à la ligne et il fera donc un retours à la ligne à chaque mot lorsque l'on écrit au milieu du texte (Il va petit à petit insérer des retours à la ligne, au fur et à mesure que l'on va écrire). Pour palier à ceci, j'ai ajouté un menu contextuel sur le champ d'entrée permettant de réarranger le texte en optimisant la longueur des lignes, mais je crains que cela ne soit pas suffisant.
![image](https://user-images.githubusercontent.com/51322714/83763434-fa122180-a678-11ea-8be2-d3364e17ffe6.png)
  - Nous ne sommes pas obligé d'utiliser un algorithme qui traite tout le texte, il est possible de ne traiter que la dernière ligne, mais nous nous retrouverons avec encore plus de problèmes, ce qui nous ramènera à utiliser la proposition précédente.

- L'autre possibilité est de faire le traitement au niveau de l'affichage et de ne jamais modifier le texte de l'élément directement. Cette méthode a de nombreux avantages, mais il reste des désavantages comme l’impossibilité d'éditer les retours à la ligne, ou même de les voir dans le champ d'entrée.

\- Clément G.

**Comment by ClementGre** [comment]
Je vais garder cette option qui reste toujours la meilleure, il sera toujours possible de modifier l'algorithme afin de retirer le retours à la ligne de la ligne suivante (pour éviter ce bug là).
Nous avons aussi l'idée de rejoindre l'ergonomie classique en plaçant le champ d'entrée directement sur l'élément, mais cela ne sera pas implémenté dans la version 1.2.0

Je ferme ainsi cette issue.
\- Clément

**Comment by ClementGre** [comment]
Bonjour,
il est vrai qu'on peut souvent avoir besoin de limiter la largeur d'un élément à moins de la largeur de la page, et il est aussi vrai que cette solution était un peu bancale.
Après y avoir re-réfléchis, je pense qu'il ne serait pas si compliqué que ça de proposer un redimentionnement horizontal, et ainsi de limiter la largeur à l'affichage.

Je réouvre donc cette "issue", et vous tiens au courant.
\- Clément

**Comment by ClementGre** [comment]
Bonjour,

il est maintenant possible de définir une largeur maximale pour les éléments textuels.
Par défaut, la largeur maximale est de 90% de la largeur totale (ceci est paramétrable).

Il est possible de définir la largeur maximale avec la bordure droite :
![Screenshot_20210925_163627](https://user-images.githubusercontent.com/51322714/134775248-1cf54d9c-0f5b-4e21-a935-f1ffafe74fea.png)
![Screenshot_20210925_163551](https://user-images.githubusercontent.com/51322714/134775251-af2fa68e-94a2-4dac-ba21-266ff1447735.png)
![Screenshot_20210925_163659](https://user-images.githubusercontent.com/51322714/134775247-eb364169-b7a9-4964-98f3-9acd03253fd5.png)

La largeur maximale est mémorisée lors de l'enregistrement dans une liste d'éléments, mais elle n'est pas synchronisée, même si l'élément est lié avec l'élément de la liste : c'est seulement lors du clic "Ajouter aux éléments précédents/favoris" que l'élément de la liste prendra une largeur maximale égale à celle de l'élément du document.

N'hésitez pas si vous avez des remarques.
Merci à vous, Clément G.
