### ISSUE TITLE
Barême

### ISSUE THREAD

**Issue by al1g** [ClementGre/PDF4Teachers#28]
Bonjour,
je viens de mettre à jour pour passer à la version 1.1.1 et je rencontre un problème de barême.
Il est impossible de modifier le total qui reste sur 20 et d'indiquer des sous niveaux alors que cela était possible dans les versions précédentes.
Peut être ai je raté qq chose ?
Merci en tout cas pour cette appli bien pratique

**Comment by ClementGre** [comment]
Bonjour, cela peut vernir du verrouillage du barème, il y a un cadenas en haut dans l'onglet notes, que vous devrez pouvoir verrouiller ou déverrouiller pour pouvoir modifier le barème.

**Comment by al1g** [comment]
OK super,
je n'avais effectivement pas vu ce cadenas.
merci pour la réactivité

**Comment by ClementGre** [comment]
D'accord, je vais essayer de rendre plus clair la fonction de ce cadenas ou de mettre un message quand le barème est verrouillé dans les prochaines versions.
