### ISSUE TITLE
Polices non-libres incluses

### ISSUE THREAD

**Issue by nicolashainaux** [ClementGre/PDF4Teachers#29]
Bonjour !

D'abord merci pour ce projet qui risque d'être bien utile à bien des profs !!

Il y a cependant un petit souci côté licence car les polices Microsoft incluses dans PDF4Teachers ne sont pas libres, ce qui est contradictoire avec la licence Apache, non ? De plus, cela empêche d'empaqueter PDF4Teachers pour Debian, ce qui est dommage...

Je ne sais pas s'il est possible de remédier au problème simplement ?

Merci encore en tous cas et bon courage !

**Comment by grensv** [comment]
Bonjour Nicolas,

Merci beaucoup pour cette information importante, car effectivement, il s'agit d'une négligence de notre part qui pose des problèmes légaux.
Nous allons remédier à ceci dès la prochaine version, en incluant uniquement des polices libres, ou en utilisant le serveur de polices de l'OS utilisé.
