### ISSUE TITLE
Fichier pdf qui apparaît vide

### ISSUE THREAD

**Issue by cdaudet** [ClementGre/PDF4Teachers#30]
Bonjour,
Voici en PJ une copie d'élève qui apparaît vide dans PDF4Teacher alors qu'elle ne l'est pas sous acrobat. Je joins aussi mes copies d'écran.
Merci pour tout votre travail.
C Daudet
[DUTILLIEU Elian 14-05.pdf](https://github.com/ClementGre/PDF4Teachers/files/4649457/DUTILLIEU.Elian.14-05.pdf)
[bug_PDF4teacher.pdf](https://github.com/ClementGre/PDF4Teachers/files/4649458/bug_PDF4teacher.pdf)

**Comment by ClementGre** [comment]
Bonjour,

J'ai identifié le problème, cela est dus au format d'image qui ne peut pas être lus par une dépendance.
Bonne nouvelle, ce problème peut être réglé et il le sera dans la prochaine version.

J'espère que vous trouverez un moyen d'éditer cette copie avant la version 1.2.0.
\- Clément GRENNERAT
