### ISSUE TITLE
Insertion de notes avec exercices dans le désordre

### ISSUE THREAD

**Issue by cdaudet** [ClementGre/PDF4Teachers#31]
Bonjour,
Lorsque l'élève ne fait pas les exercices dans l'ordre, c'est plus compliqué de mettre les notes . Je commence par l'exercice 1 qui est à la fin : pas de souci pour mettre la note.
Mais si l'exercice 2 est au dessus de l'exercice 1, on ne peut pas mettre la note de l'exercice 2 avec le clic droit.

Autre suggestion : lorsqu'on insère une note avec le clic droit, pourrait-on rester sur l'onglet édition des commentaires et ne pas passer dans l'onglet notes ?

Merci beaucoup,
Cordialement,
C Daudet

**Comment by ClementGre** [comment]
Bonjour,

concernant votre première suggestion, il serait possible de modifier le mode de calcul de la prochaine note. actuellement, cela dépend de la position des notes sur le document, mais nous pouvons faire que le clic droit propose tout simplement la première note non saisie de la liste des notes. Je garde cette issue ouverte pour implémenter cette fonctionnalité dans la version 1.1.0

Pour votre autre suggestion, c'est le fait de sélectionner un élément (en le déplaçant par exemple) qui va sélectionner l'onglet correspondant au type de l'élément. C'est vrai que cette fonctionnalité peut être dérangeante dans votre cas par exemple. Il serait donc peut-être une bonne idée de supprimer cette fonctionnalité, ou du moins de la désactiver pour les notes ?

**Comment by ClementGre** [comment]
Bonjour,

après réflexion, je ne vois pas de moyen pour que l'on vous propose directement le bon exercice dans toutes les situations possibles, à part l'IA, mais je ne compte pas intégrer d'IA à PDF4Teachers 😂 

Votre problème est que l'élève à fais les exercices dans le mauvais ordre, et que vous corrigez dans le bon ordre (je n'avais pas compris la même chose lors de ma première réponse, mais après réflexion, il me semble que votre problème soit plutôt celui là). Vous vous retrouvez donc avec aucune proposition pour tout clic qui se situe avant l'exercice 1 (les propositions dépendent de la position de votre clic droit sur la page).
Lorsque vous placez une note, toutes les notes précédentes seront proposés avec un clic avant la note placée et toutes les notes suivantes seront proposés avec un clic après l'élément. Puisqu'il n'y a aucune note (à part Total) avant Exercice 1, aucune n'est proposée.

Ce système marche un peut mieux dans le cas ou l'enseignant corrige dans l'ordre de l'élève : s'il commence par l'exercice 2 l'exercice 3 lui sera bien proposé. L'exercice 1 devra cependant être entré sans le raccourcis du clic droit.

Ma proposition de proposer dans tout les cas la prochaine note non remplie peut être une bonne idée, cependant, les propositions ne dépendront plus de la position du clic sur le document. C'est à réfléchir.


Concernant le fait que l'on sois ramené sur le panneau des notes lors que l'on en sélectionne une, cela a été désactivé, mais uniquement pour les notes : on est ramené sur le panneau des éléments textuels lors de la sélection d'un élément textuel.

\- Clément G.

**Comment by ClementGre** [comment]
Bonjour,

Mon idée d'implémenter les deux algorithmes à la fois m'a semblé pertinente, j'ai don ajouté cela au code.
Sur cet exemple, on peut voir que l'exercice 3 a été placé avant l'exercice 2 (qui n'a pas encore été entré). Dans les propositions nous avons donc l'exercice 4, car c'est celui qui suit l'exercice 3, mais nous avons aussi l'exercice 2, car il est le premier exercice à ne pas avoir été entré.
Dans votre cas, nous aurons donc l'exercice 2 qui se proposera même si vous cliquez avant l'exercice 1.
![Annotation 2020-06-04 095725](https://user-images.githubusercontent.com/51322714/83730769-d84d7600-a649-11ea-96cb-116379bbcb5f.png)

\- Clément G.
