### ISSUE TITLE
Complémentarité et échange avec amc

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#33]
Amc (https://www.auto-multiple-choice.net/index.fr) et pdf4teacher (https://github.com/ClementGre/PDF4Teachers#pdf4teachers-fr) vont dans le même sens, faciliter la correction des copies. Sous forme de qcm pour l'un et sous forme de question ouvertes pour l'autre. Peut-être qu'une synergie pourrait avec lieu? Qu'en pensez-vous?

**Comment by grensv** [comment]
Merci Michel pour ce partage !
Je ne connaissais pas amc, bien que j'utilise des outils web de mon université pour générer des QCM en ligne. Je vois que AMC me permettra de faire la même chose en version papier, quand on reviendra aux évaluations en classe, dès la rentrée j'espère ! L'outil d'OMR de AMC a l'air très intéressant, et l'ensemble doit permettre un gain de temps très appréciable.
Etes-vous impliqué dans le développement d'AMC ? Avez vous des relations directes avec Alexis Bienvenüe ou des développeurs ?
En effet, PDF4Teachers et AMC semblent très complémentaires : AMC est plutôt focalisé sur les QCM format papier, et PDF4Teachers sur tout ce qui relève des annotations sur copie numérique et de l'évaluation plutôt formative, c'est à dire qui requiert un retour conséquent d'informations sur la copie. Si une synergie directe (intégration d'un outil dans l'autre par exemple) ne me semble pas pertinente car ces 2 logiciels sont basés sur des SDK complètement différents, il serait surement pertinent de communiquer l'un sur l'autre, les 2 projets étant totalement complémentaires et s'adressent au même type d'utilisateurs.
Vincent Grennerat.

**Comment by michelwend** [comment]
Bonsoir,
Malheureusement je suis simplement un utilisateur basique d'amc que j'ai découvert cette année suite au confinement et après avoir utilisé des outils non libre devant afflue des copies de seconde notamment. Je suis entrain de repenser toutes mes évaluations car je souhaite en garder une trace élève sous forme de copie papier ou de fichier pdf de manière à les rendre utilisables par amc ou pdf4teachers.

**Comment by grensv** [comment]
Comme vous semblez déjà bien connaître AMC, à quel type de synergie pensiez-vous ?

Vincent.

**Comment by michelwend** [comment]
D'un point de vue utilisateur je ne suis pas sur que le mot synergie soit le plus adapté mais en terme de fonctionnalité par contre le fait de pouvoir mélanger des questions qcm et ouvertes que l'on pourrait corriger au travers de la même interface au lieu d'avoir à passer le fichier initial dans chacun des programme serait un vrai plus. Notamment l'addition des points par compétences qui semble arriver avec la version 1.2 de pdf4teachers.

**Comment by ClementGre** [comment]
Bonjour,

Ce que vous souhaitez faire est donc de créer un sujet avec AMC, avec à la fois des questions de QCM d'AMC, corrigés automatiquement, et des questions ouvertes, que vous corrigerez avec PDF4Teachers.

Je suppose qu'actuellement, AMC vous génère des PDF ou des images avec les copies corrigés, que vous devez alors ouvrir dans PDF4Teachers pour pouvoir terminer la correction.


Vous souhaiterez donc qu'AMC puisse avoir les même fonctionnalités que PDF4Teachers, ou que PDF4Teachers puisse avoir les même fonctionnalités qu'AMC. Bien sûr, le plus simple serait de faire une sorte de fusion des deux applications, mais cela ne pourrait réellement marcher que si les deux applications utilisaient le même langage et éventuellement les même librairies graphiques. Comme l'a expliqué Vincent, cela n'est malheureusement pas le cas.

Mes deux premières solutions sont aussi irréalisables car redévelopper des applications qui ont pris des centaines d'heures à être développé, demanderait beaucoup trop de travail (Pour moi du moins). Ce qui reste possible est de faire en sorte que PDF4Teachers soit en capacité de "convertir" les donnés des QCM d'AMC en éditions (éditions de fichier PDF qu'utilise PDF4Teachers, fichier contenant toutes les annotations et notes). Je ne sait pas si AMC stocke les donnés des QCM, et si oui, s'il les stocke sous forme de fichier. Il est donc aussi possible de demander à AMC de pouvoir exporter les résultats sous forme d'édition YAML au format de PDF4Teachers, et d'exporter les images scannés en PDF (Du coup sans résultat puisque PDF4Teachers affichera les notes).

J'espère avoir répondu à votre question.
Cordialement, Clément GRENNERAT

**Comment by michelwend** [comment]
Merci pour vos retours et votre travail. Vous avez complètement répondu à la question.

**Comment by ClementGre** [comment]
Fermer cette issue signifie que vous n'avez plus besoin d'aide de notre part, s'il s'agissait uniquement d'une question, vous pouvez fermer l'issue, mais si vous souhaitez que je cherche à réaliser ce que j'ai dit, ré-ouvrez l'issue pour qu'elle soit dans ma to do list !

**Comment by michelwend** [comment]
A la vue de votre dernier commentaire j'avais cru comprendre que la mise en place des fonctionnalités du type Amc étaient trop complexes à implanter. Mais si c'est possible c'est avec grand plaisir que je réactive cette "issue".

**Comment by michelwend** [comment]
Une suggestion supplémentaire serait qu'il soit possible d'importer le devoir avec libreoffice et notamment son éditeur mathématiques. De plus si le scan des copies pourrait directement corriger les parties qcm ce serait pour moi suffisant complètement passer à pdf4teachers.

**Comment by ClementGre** [comment]
Lire directement des fichiers .odt serait trop compliqué pour PDF4Teachers car il faudrait décoder le fichier, certainement en utilisant une librairie de LibreOffice, ce qui alourdirait l'application.

Concernant les formules mathématiques, j'ai implémenté le LaTeX à la version 1.2.0. Le LaTeX permet décrire des formules mathématiques aisément et plus rapidement que l'éditeur de libre office. Son défaut est qu'il faut tout de même connaître les bases pour pouvoir s'en servir correctement.

Comme expliqué plus haut, je ne peut pas implémenter les fonctionnalités d'AMC directement, mais je vais essayer de contacter Alexis, pour voir s'il serait possible d'exporter un projet AMC sous format d'édition de PDF4Teachers, ou d'importer un projet AMC dans une édition PDF4Teachers.

\- Clément G.

**Comment by ClementGre** [comment]
Je vous redirige donc vers [cette issue](https://project.auto-multiple-choice.net/issues/733) sur le site d'AMC.
