### ISSUE TITLE
Avertissement Gdk-WARNING dans le terminal au lancement

### ISSUE THREAD

**Issue by omangeat** [ClementGre/PDF4Teachers#39]
bonjour
j'ai le message 
(java:15646): Gdk-WARNING **: 22:14:21.112: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
quand je lance PDF4teachers sur manjaro. Cela ne semble pas nuire au fonctionnement du programme.
Bravo pour le travail, ça me donne envie de corriger des copies numériques :-)
Tu auras compris que c'est mon premier passage sur Github

**Comment by ClementGre** [comment]
Bonjour,
ce message est bien visible uniquement dans le terminal, lors de l'ouverture de l'application et il n'empêche pas l'application de fonconner ?
Je vais essayer de trouver les raisons de ce message.

\- Clément G.

**Comment by omangeat** [comment]
Bonjour En effet l'application semble fonctionner normalement (je n'ai pas tout testé). Je précise que je suis sous manjaro.Bravo pour ce super boulot Envoyé de mon Galaxy A50 Orange
-------- Message d'origine --------De : Clément Grennerat <notifications@github.com> Date : 09/08/2020  12:03  (GMT+01:00) À : ClementGre/PDF4Teachers <PDF4Teachers@noreply.github.com> Cc : omangeat <olivier.mangeat@orange.fr>, Author <author@noreply.github.com> Objet : Re: [ClementGre/PDF4Teachers] linux non debian (#39) 

Bonjour,

ce message est bien visible uniquement dans le terminal, lors de l'ouverture de l'application et il n'empêche pas l'application de fonconner ?

Je vais essayer de trouver les raisons de ce message.

- Clément G.

**Comment by ClementGre** [comment]
L'origine de cet avertissement n'est pas connus et il ne semble pas poser de problèmes. Je ferme cette issue.
