### ISSUE TITLE
Enregistrer le Barème ou les Éditions dans un fichier ou dans UserData

### ISSUE THREAD

**Issue by MatQ07** [ClementGre/PDF4Teachers#40]
Bonjour,

Je trouve un peu obscure la manière dont le barème se sauvegarde. J'ai des classes qui n'avancent pas du tout au même rythme et je crains de devoir refaire le barème et mes commentaires pour chaque pool de copies, si je veux les rendre rapidement après les avoir récupérées. Je trouve ça dommage que l'on doive faire des choses répétitives en informatique. Ne serait-il pas envisageable d'avoir un fichier récapitulant tout cela que l'on enregistrerai, par exemple dans le dossier destiné à recevoir les copies des élèves et qui resortirait barème et commentaires pré-enregistrés ?

**Comment by grensv** [comment]
Bonjour,

Pour le moment, la logique qui a été adoptée pour le barème est que celui-ci est sauvegardé au côté des annotations, avec chaque copie PDF, sans aucun lien entre les différentes copies (un fichier d'éditions -annotations/barème- par PDF, sauvegardé dans le dossier caché .PDF4Teachers (l'emplacement dépend de l'OS). Le barème est donc propagé d'une copie vers les autres, avec la commande "Envoyer le barème sur d'autres éditions".
Une manière simple de sauvegarder ses barèmes de référence, que l'on voudrait donc conserver indépendamment d'une copie ou d'un paquet de copies, est :
- Créer un dossier pour y sauver tous les barèmes
- Dans ce dossier, créer un (des) fichier PDF vide(s) (juste une page blanche) nommés par exemple Barème_xxxx.pdf. On définit le barème dans ce fichier (ou bien on l'exporte depuis une copie PDF ouverte qui le contient déjà), puis on sauvegarde l'édition. Attention lors des copies de barème, pour éviter toute copie non souhaitée sur d'autres fichiers, de n'avoir d'ouvert dans le panneau des fichiers que les fichiers sur lesquels on veut copier le barème.
- Ne pas déplacer ensuite le dossier, ni les fichiers PDF vierges de barème, car PDF4Teachers fait le lien entre le chemin de ceux-ci et les fichiers d'édition du dossier .PDF4Teachers (cependant récupérable au besoin, avec la commande Fichier -> éditions du même nom)

Ma conclusion sur le plan évolution future de la gestion des barèmes :
- Ceci a le défaut de sauver les barèmes dans une zone "obscure" qu'est le dossier caché .PDF4Teachers,
- L'utilisateur qui ne met pas en place ce qui est décrit ci-dessus ne sait pas forcément où se trouve son barème sauvegardé,
- Il y a des risques d'erreurs de manipulation qui peuvent mener à la perte provisoire (déplacement du fichier PDF associé au barème) ou à la perte définitive (commande "supprimer les éditions des fichiers ouverts" si malheureusement le fichier de barème est ouvert).
=> Suggestions d'amélioration : 
- peut-être une fonction "archiver le barème" qui créerait dans un dossier de notre choix un fichier d'éditions yml contenant uniquement le barème à archiver.
- Il faudrait lui associer une fonction "copier un barème depuis une archive" qui permettrait d'appliquer un barème depuis un fichier yml à sélectionner dans un dossier de notre choix.
- Remarque 1 : pourquoi ne pas faire la même chose pour les listes favorites d'annotation, ça rassurerait les utilisateurs de les sauver eux même dans un dossier indépendant de PDF4Teachers.
- Remarque 2 : ces fonctionnalité pour barème et favoris permettrait le partage entre enseignants. (Pour le moment, pour faire ça, il faut qu'ils soient capables d'aller manuellement chercher le fichier yml, et avoir compris qu'il faut un fichier PDF nommé comme le fichier yml)

**Comment by ClementGre** [comment]
Concernant la réutilisation des éléments, il existe déjà une fonction permettant de sauvegarder les éléments favoris dans une Liste d'élémens ce qui avait pour but de régler ce problème, mais en y réfléchissant, les élémets favoris sont ceux qui sont communs entre les copies, ceux qui changent entre les copies sont les éléments précédents, **il faudrait donc pouvoir créer des listes d'éléments précédents à la place, en plus, ou en commun avec les listes d'éléments favoris.**

Concernant les notes, en effet, pour réutiliser un barème déjà créé, on est obligé de réouvrir un document qui contient le barème déjà créé avant de le copier sur les autres copies (d'une autre classe du même niveau par exemple). Il y a plusieurs solutions à ce problème :
- Créer des listes de barèmes enregistrables à la manière des listes d'éléments Favoris
- Pouvoir exporter les barèmes sous forme de fichier YAML, cela apporte l'avatage du partage entre différentes personnes, mais est-ce vraiment utile ? Et ne serait il pas plus ergonomique d'avoir son barème enregistré dans une liste, que de laisser l'utilisateur ranger le barème dans ses fichiers lui même.
- Il serait aussi envisageable de déplacer le lieu de stoquage du barème lui même. Enregistrer les barèmes dans les donnés utilisateurs, mais cela demanderait beaucoup de modifications. Il faudrait créer une interface graphique avec la liste des barèmes et permettre de les modifier. Sur les copies, on devrait sélexionner un barème avant de pouvoir commencer la notation. La différence de lieu de stokage entre la valeur de la note et son nom/total/hierarchie demanderait aussi beaucoup de travail qui n'est pas négligeable, pour au final apporter "uniquement" un moyen de stoquer les barèmes.

Cordialement, Clément

**Comment by ClementGre** [comment]
Concernant la réutilisation des éléments, comme cité précédamment, il sera disponible dans la prochaine version de PDF4Teachers de sauvegarder et de charger des listes à partir des éléments précédents ; et ces listes seront en commun avec celles des éléments favoris.

Concernant l'enregistrement des barèmes, je pense opter pour la solution nº2, c'est à dire pouvoir exporter le barème sous forme d'un fichier propre, et pouvoir les réimporter par la suite.
Comme me l'a proposé @michelwend dans #50, il serait aussi intéressant de pouvoir enregistrer les éditions complètes dans un fichier et pouvoir les importer par la suite. Cela peut permettre le partage rapide d'éditions et peut aussi faciliter l'importation d'éditions générées par des logiciels tiers, je pense par exemple à la collaboration envisagée avec AMC (#33).

\- Clément

**Comment by michelwend** [comment]
Oui merci!

**Comment by ClementGre** [comment]
Bonjour,
cette fonctionnalité a été développé et sera disponible dans le menu Outils de la version 1.2.1
Elle permet d'exporter/importer des éditions ou des barèmes.

![image](https://user-images.githubusercontent.com/51322714/101266951-4f5ae880-3719-11eb-9bc9-d436105e04ee.png)

Il est aussi possible d'exporter plusieurs éditions d'un coup avec la possibilité de les exporter dans le même fichier.

![image](https://user-images.githubusercontent.com/51322714/101266970-8d580c80-3719-11eb-9a4b-9758acb48982.png)

Concernant l'exportation des éléments favoris/précédents/des listes, ces donnés sont maintenant enregistrés dans un fichier séparé, accessible via le menu Débug d'Outils

![image](https://user-images.githubusercontent.com/51322714/101267005-f3dd2a80-3719-11eb-97cf-39aaa93a9c5b.png)

Ce fichier s'apelle ``textelements.yml``.

\- Clément Grennerat
