### ISSUE TITLE
Inclure des liens dans les documents PDF

### ISSUE THREAD

**Issue by ClementGre** [ClementGre/PDF4Teachers#41]
Philippe me propose d'ajouter un moyen d'ajouter des annotations audio à un documents PDF.
Ceci semble être possible avec les dépendances utilisés. Cependant, seul Acrobat Reader semble être capable de lire ce type de "pièces jointes". À voir ce que vous en pensez.

**Comment by ClementGre** [comment]
Une autre proposition est proposée : copier le fichier audio sur un serveur (ou demander à l'enseignant de fournir un lien de ficher .mp3 ou autre). Et ainsi proposer un QR code à afficher sur le document.

\- Clément

**Comment by grensv** [comment]
Je suis contre l’idée d’alourdir fortement par de l’audio les fichiers PDF, surtout si les lecteurs autres que AcrobatReader ne le prennent pas en charge. Aujourd’hui peu d’utilisateurs installent Acrobat Reader qui est lourd comparé aux lecteurs PDF intégrés comme Aperçu ou Edge.

L’idée du QR code est donc bonne, mais elle est surement très pénible à l’usage pour le prof (mettre manuellement en ligne sur un serveur à choisir, ne pas se tromper en copiant le QR code…)
À réfléchir…

Vincent.

**Comment by ClementGre** [comment]
Enregistrer des fichiers en ligne serait assez lourd à mettre en place : mettre en place un serveur qui pourrait télécharger des fichiers puis les redistribuer (via une interface html ou pas) demanderait beaucoup de travail. De plus, le but de PDF4Teachers est de permettre une correction rapide via des annotations. L'application n'est pas destiné à ce type de correction (Mais je ne suis pas contre ajouter de nouvelles fonctionnalités pour toucher un public plus grand donc ça pourrait être une bonne idée pour le futur).

L'option qui est choisie pour le moment serait de simplement pouvoir insérer des liens, avec des annotations, et l'idée de QR code pourrait être intéressante pour les professeurs qui impriment les copies (d'où le titre de l'issue qui a été changé).
