### ISSUE TITLE
.deb : Application qui ne se lance pas

### ISSUE THREAD

**Issue by l-leroux** [ClementGre/PDF4Teachers#42]
Bonjour,
j'avais installé en juin la version 1.0.2 qui continue à très bien fonctionner.
J'ai voulu essayé hier la version 1.2.0 en installant le .deb (je suis sous Mint 20 / Cinnamon). L'installation du .deb semble bien se dérouler, mais au lancement depuis le raccourci placé dans le menu, après un moment de réflexion...rien. 
Si je lance PDF4Teachers de opt/pdf.../bin dans un terminal, malgré le fait qu'il soit éxécutable, la commande n'est pas reconnue...
Une idée ?
Merci pour tout le travail déjà accompli !

**Comment by ClementGre** [comment]
Bonjour,
La version 1.0.2 de PDF4Teachers ne comprenait pas de fichier .deb. Il falait donc installer le programme à la main dans /usr/local. Faites attention à bien désinstaller l'ancienne version.

Je ne retrouve pas votre problème en installant la 1.2.0 après avoir installé la 1.0.2 sur Mint 20.
Vous devriez peut-être essayer de désinstaller complètement  PDF4Teachers puis d'installer la 1.2.0. Votre .deb ou votre exécutable de PDF4Teachers a dû être corrompus à un certain moment.

Si le problème persiste, essayer d'installer l'application à la main avec la version non packagé en .deb (Linux non Debian sur le site internet).

\- Clément

**Comment by l-leroux** [comment]
Bonjour,
merci de votre réponse.
Plusieurs purge/téléchargement du .deb n'ont rien fait, mais la version non packagée a fonctionné.
Bon courage pour la suite !
