### ISSUE TITLE
Dossier non ouvert dans le panneau latéral après conversion d'image lorsque le fichier s'appelle ".pdf"

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#43]
- Utiliser l'outil "convertir des fichiers en un document"
- Ne pas modifier le nom du document généré (laisser `.pdf`)
- Le dossier ne s'ouvre pas dans le panneau latéral 

---------

Bonjour,

J'ai utilisé le lien "convertir" pour convertir des images.

Le logiciel m'a indiqué qu'il avait fini et que le dossier avait été ouvert dans le panneau latéral.

Hors aucun dossier n'a été ouvert.

**Comment by DegrangeM** [comment]
Remarque : dans le dossier `C:\Users\XXX\AppData\Roaming\PDF4Teachers` le nom du pdf généré est uniquement `.pdf`.

**Comment by ClementGre** [comment]
Bonjour,
Avez-vous utilisé la fonction de conversion d'images en document PDF, ou celle de conversion de plusieurs images dans des dossiers en plusieurs documents PDF ?

Si vous avez convertis plusieurs dossiers en plusieurs documents PDF d'un coup et que vos dossiers sont vides, l'application ne génère aucun document PDF.

Cette génération d'un document nommé uniquement .pdf est étrange. Vous pouvez vérifier si il n'y a pas un message d'erreur généré dans la console de l'application après la génération. Vous pouvez faire apparaître la console avec avec Ctrl+Alt+C. dans l'application.

\- Clément G.

**Comment by DegrangeM** [comment]
J'ai utilisé l'onglet "convertir des fichiers en un document", pas d'erreur dans la console mais je vais essayer de reproduire mes actions pour voir si j'ai à nouveau le bug.

**Comment by DegrangeM** [comment]
C'est normal que le fichier s'appelle .pdf puisque le nom du fichier est demandé et est par défaut .pdf

**Comment by DegrangeM** [comment]
J'ai pu reproduire mes actions et à nouveau le dossier n'est pas ouvert dans le panneau latéral. Pas d'erreur dans la console à part "you did not close a pdf document" mais je crois que c'est du a autre chose.

**Comment by DegrangeM** [comment]
Je confirme : le bug se produti uniquement lorsque l'on ne change pas le nom du document et qu'on le laisse a `.pdf`

**Comment by ClementGre** [comment]
Merci pour ce debrief. Il s'agit donc du nom de fichier ".pdf" qui n'est pas détecté comme document de type PDF par le logiciel. De plus, PDF4Teachers ne devrait pas vous laisser convertir des images en un document de nom ".pdf".

Ce problème sera résolu dans la prochaine version.

\-Clément
