### ISSUE TITLE
Export des notes : Erreur de division par 0 sur la ligne des moyennes

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#47]
Bonjour,
Lors d'un export des notes en .cvs j'ai systématiquement une erreur sur le calcul de la moyenne. J'ai ouvert le fichier avec excel et calc. Auriez-vous une idée de la provenance de ce souci? En vous remerciant.
[moyenne.zip](https://github.com/ClementGre/PDF4Teachers/files/5523000/moyenne.zip)

**Comment by ClementGre** [comment]
Bonjour,
le message d'erreur que vous rencontrez est dû à une divivsion par 0 (``#DIV/0!``) que votre tableur essaye de faire.
Je ne peut pas localiser l'erreur car la formule ``=AVERAGE()`` n'est plus présente dans le document. je pense que vous avez ouvert le document avec un tabaleur pour l'éditer avant de le re-exporter.
Il est assez étrange de recontrer cette erreur avec la fonction AVERAGE.

Essayez de me fournir le document .csv que génère PDF4Teachers. Vous pouvez retirer le nom des élèves en éditant le fichier avec un éditeur de texte classique.
Il serait aussi bien que vous m'envoyez l'édition d'un des documents que vous avez exportés. (Les éditions se situent dans ``<dossier d'utilisateur> \AppData\Romaning\PDF4Teachers\<nom de l'édition>.yml`` le dernier élément du <nom de l'édition> représente le nom du fichier PDF en question.). Vous pouvez ici aussi éditer le fichier .yml avec un éditeur de texte pour supprimer les données sensibles.

\- Clément Grennerat

**Comment by michelwend** [comment]
[moyenne2.csv.txt](https://github.com/ClementGre/PDF4Teachers/files/5526957/moyenne2.csv.txt)
[D!P!!E!MECA!E!1_i2d!E!00_pdfRetourCopies!E!EV_CRIC!E!ZIANI Sami.pdf.yml.txt](https://github.com/ClementGre/PDF4Teachers/files/5526982/D.P.E.MECA.E.1_i2d.E.00_pdfRetourCopies.E.EV_CRIC.E.XXXX.xxxx.pdf.yml.txt)

**Comment by ClementGre** [comment]
Je n'arrive pas à reproduire votre problème, dites-moi quelles options avez-vous activé durant l’exportation.
Il me semble que vous ne m'ayez pas envoyé le fichier .csv que génère PDF4Teachers car il y a encore cette ligne :
``Moyenne;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!;#DIV/0!`` qui est généré par un tableur. Essayer de me ré-envoyer le fichier.

\-Clément G.

**Comment by michelwend** [comment]
Bonjour,
J'espérai pouvoir vous transmettre un nouveau fichier avec un autre devoir. Mais cela devient impossible le programme se fige. Une nouvelle installation s'impose. Heureusement j'ai quand même sauvegardé les copies corrigées.

**Comment by ClementGre** [comment]
Je ferme cette issue car aucun bug n'a été trouvé.
