### ISSUE TITLE
Impossible de sauvegarder une liste

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#48]
Bonjour,
La commande de sauvegarde de liste ne fonctionne pas; En cliquant sur la création de liste il me propose un nom: nouvelle liste en voulant sauvegarder sous ce nom ou en changeant cela ne fonctionne pas. Merci pour vos éclaircissements.
![liste](https://user-images.githubusercontent.com/11646494/98792274-8a157d80-2406-11eb-94ef-e5e138e34bed.png)

**Comment by ClementGre** [comment]
Bonjour,
Il est impossible de sauvegarder une nouvelle liste dans votre cas car il n'y a aucun élément à enregistrer : votre liste des éléments favoris est vide (sur la capture d'écran du moins).
Il pourraît être intéressant d'afficher un message d'avertissement lors de l'essai de l'enregistrement d'une liste vide.

\- Clément

**Comment by michelwend** [comment]
Je viens de faire un essai et j'obtiens cette fenêtre avec un texte qui disparait au fur et à mesure du temps qui s'écoule. A gauche du cadre. Et je n'arrive toujours pas à sauvegarder la liste. Auriez-vous une idée pour le faire? En vous remerciant.
![image](https://user-images.githubusercontent.com/11646494/98850243-bfe15300-2454-11eb-9784-44ca62858843.png)

**Comment by michelwend** [comment]
Je viens de réussir à sauvegarder une liste d'après le message donné par le logiciel. Mais pour la charger j'ai ce message:
![image](https://user-images.githubusercontent.com/11646494/98851241-45b1ce00-2456-11eb-9370-914bb0c529b7.png)

**Comment by ClementGre** [comment]
J'ai compris votre premier problème :
Le champ de texte prend beaucoup trop de place ce qui empèche le texte de s'afficher et ce qui fait déborder la suface d'affichage en dehors de la fenêtre. Les boutons OK et Annuler qui s'alignent à droite ne sont donc pas visibles car ils sont sur la partie de la surface d'affichage qui dépasse à droite de la fenêtre.
Ce fénomène est très étrange : le champ de texte n'est pas censé s'étirer comme ça.
Je suppose que vous avez pressé ENTRÉE pour réussir à activer le bouton OK. Ou avez vous trouvé une solution de faire afficher les boutons ?

Le second phénomène qui vous arrive est tout aussi étrange.
- Après avoir sauvegardé, pressez CTRL+ALT+C pour ouvrir le terminal d'exécution de l'application, envoyer moi une capture d'écran si vous voyez un message spécifique d'affiché.
- Vous pouvez aussi essayer de redémarer l'application après avoir sauvegardé la liste d'éléments et réessayer de la charger (tester s'il s'agit d'un problème de synchronisation).
- Enfin, vous pouvez m'envoyer le fichier userdata.yml qui se situe normalement dans votre dossier d'utilisateur \appdata\roaming\pdf4teachers\ vous devriez pouvoir entrer ceci dans votre explorateur de fichiers : ``~\appdata\roaming\pdf4teachers\``. (Sous Windows) Ce fichier contient uniquement des données sur les derniers fichiers ouverts, les derniers emplacements choisits et toutes les listes d'éléments. Vous pouvez vérifier qu'il n'y a aucune information personelle (userdata.yml est lisible par un éditeur de texte classique) et pouvez aussi me communiquer ce fichier par mail (clement.grennerat@free.fr).
- Vous pouvez aussi essayer de supprimer le fichier userdata.yml ce qui réinitialisera vos éléments favoris et précédents.

J'espère que vous trouverez une solution à votre problème.
\- Clément Grennerat

**Comment by michelwend** [comment]
Voilà la capture d'écran
![image](https://user-images.githubusercontent.com/11646494/98859154-01c4c600-2462-11eb-93c4-f46ac5f68a7c.png)

**Comment by ClementGre** [comment]
Il se passe en effet quelque-chose d'étrange avec votre barème, mais cette erreur n'a pas de lien avec les listes d'éléments textuels.

Essayez les autres points que j'ai mentionné dans mon message précédent.
\- Clément

**Comment by michelwend** [comment]
Je viens de sauvegarder une liste. Je suis sorti du programme et viens d'y retourner j'ai toujours cela.
![image](https://user-images.githubusercontent.com/11646494/98860022-59affc80-2463-11eb-8854-567d5da17b0e.png)
J'ajoute que ce phénomène c'est produit également sur la correction précédente et donc n'est pas lié à ce devoir précisément.

**Comment by ClementGre** [comment]
D'accord, essayez de m'envoyer et de supprimer le fichier userdata.yml comme je vous l'ai expliqué dans ma seconde réponse :

> J'ai compris votre premier problème :
> Le champ de texte prend beaucoup trop de place ce qui empèche le texte de s'afficher et ce qui fait déborder la suface d'affichage en dehors de la fenêtre. Les boutons OK et Annuler qui s'alignent à droite ne sont donc pas visibles car ils sont sur la partie de la surface d'affichage qui dépasse à droite de la fenêtre.
> Ce fénomène est très étrange : le champ de texte n'est pas censé s'étirer comme ça.
> Je suppose que vous avez pressé ENTRÉE pour réussir à activer le bouton OK. Ou avez vous trouvé une solution de faire afficher les boutons ?
> 
> Le second phénomène qui vous arrive est tout aussi étrange.
> 
>     * Après avoir sauvegardé, pressez CTRL+ALT+C pour ouvrir le terminal d'exécution de l'application, envoyer moi une capture d'écran si vous voyez un message spécifique d'affiché.
> 
>     * Vous pouvez aussi essayer de redémarer l'application après avoir sauvegardé la liste d'éléments et réessayer de la charger (tester s'il s'agit d'un problème de synchronisation).
> 
>     * Enfin, vous pouvez m'envoyer le fichier userdata.yml qui se situe normalement dans votre dossier d'utilisateur \appdata\roaming\pdf4teachers\ vous devriez pouvoir entrer ceci dans votre explorateur de fichiers : `~\appdata\roaming\pdf4teachers\`. (Sous Windows) Ce fichier contient uniquement des données sur les derniers fichiers ouverts, les derniers emplacements choisits et toutes les listes d'éléments. Vous pouvez vérifier qu'il n'y a aucune information personelle (userdata.yml est lisible par un éditeur de texte classique) et pouvez aussi me communiquer ce fichier par mail ([clement.grennerat@free.fr](mailto:clement.grennerat@free.fr)).
> 
>     * Vous pouvez aussi essayer de supprimer le fichier userdata.yml ce qui réinitialisera vos éléments favoris et précédents.
> 
> 
> J'espère que vous trouverez une solution à votre problème.
> - Clément Grennerat

**Comment by michelwend** [comment]
[userdata.txt](https://github.com/ClementGre/PDF4Teachers/files/5526899/userdata.txt)

**Comment by ClementGre** [comment]
Je ne vois rien d'incorrect dans ce fichier.
Essayez de le supprimer à un moment où l'application est fermée, puis relancez l'application.

\- Clément G.

**Comment by ClementGre** [comment]
Je ferme cette issue suite à son inactivité.

**Comment by ClementGre** [comment]
Je reviens vers vous suite à une réinspection de votre fichier userdata.yml.

Dans ce fichier :
```YAML
texts:
  favorites: []
  lasts: []
  lists: {}
  lastFont: {font: Open Sans, size: 14, color: '0xff0000ff', bold: false, italic: false}
```

on remarque que les listes des éléments favoris, des éléments précédents ainsi que des listes sont toutes trois vides.
Avez vous supprimé vous ces données du fichier, où alors les listes étaient bien vides ?
Je reviens sur cette idée :
> Il est impossible de sauvegarder une nouvelle liste dans votre cas car il n'y a aucun élément à enregistrer : votre liste des éléments favoris est vide (sur la capture d'écran du moins).

Avez vous réglé votre problème ?

\- Clément Grennerat

**Comment by michelwend** [comment]
Bonsoir,
J'avoue que je suis passé outre et j'ai réinstallé le logiciel. Je ferai à nouveau ce type d'essai lors de la nouvelle version qui semble poindre le bout de son nez. En tout cas merci encore.
