### ISSUE TITLE
Dupliquer un élément déjà présent sur le document avec un double clic

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#49]
Bonjour,
Pour copier un texte il faut le sélectionner dans le menu de gauche. Si celui-ci existe sur la copie on pourrait éventuellement faire un copier coller d'une remarque déjà sur la copie pour la mettre ailleurs.
Actuellement en étant dans la copie je déplace la souris de droite à gauche, je choisi la remarque qui se mettra à peu prêt au milieu sur la gauche du document, je sélectionne celle-ci puis je viens la placer sur la feuille au bon endroit; L'idée c'est de faire un copier coller sur la feuille directement.
Je ne sais pas s'il est possible d'implanter cette fonctionnalité? En vous remerciant.

**Comment by ClementGre** [comment]
Bonjour,

premièrement, il existe un menu contextuel qui affiche les 6 éléments les plus utilisés et qui pourrait probablement vous aider. Il faut faire un clic droit sur le document pour l'afficher (C.f. documentation).

Il est aussi possible de dupliquer un élément déjà présent sur le document via son menu contextuel (clic droit sur l'élément -> Dupliquer).

Il est vrai qu'il serait intéressant d'implémenter un moyen plus rapide de dupliquer un élément, avec un double clic sur celui-ci par exemple.

J'espère vous avoir aidé
\- Clément Grennerat

**Comment by michelwend** [comment]
Oui l'idée du double clic me semble pertinente merci.

**Comment by ClementGre** [comment]
D'accord, je révouvre l'issue pour ne pas oublier d'ajouter la fonctionnalité du double clic.

**Comment by michelwend** [comment]
Oui merci.

**Comment by ClementGre** [comment]
Je rapelle que...
> D'accord, je révouvre l'issue pour ne pas oublier d'ajouter la fonctionnalité du double clic.
