### ISSUE TITLE
Evolution sauvegarde

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#50]
Bonjour,
s'il était possible de prévoir une solution de sauvegarde qui inclurait les remarques et les notes dans un premier temps. Puis éventuellement les remarques, les notes et les copies? En vous remerciant.

**Comment by ClementGre** [comment]
Bonjour,
qu'entendez-vous par "une solution de sauvegarde" ?
Si vous parlez du support de l'exportation des éditions sous forme de fichiers (duplicate of #40), l'exportation des éditions complètes est bien prévu pour la prochaine version. Un message sera envoyé sur #40.

\- Clément GRENNERAT

**Comment by michelwend** [comment]
Ok merci. effectivement le message 40 devrait répondre à ma problématique.
