### ISSUE TITLE
Couleur fond noir/blanc

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#51]
En fonction du choix de la couleur du fond certains éléments disparaissent chaîne des remarques, sauvegarde des listes dans le menu qui s'ouvre juste après.

**Comment by ClementGre** [comment]
Bonjour,
j'imagine que le "choix de la couleur du fond" représente le choix d'activer le mode sombre.

Si "chaîne des remarques" symbolise pour vous les éléments dans les listes d'éléments textuels favoris, précédents et sur ce document dans le second onglet du panneau latéral, je n'arrive pas à reproduire votre problème de mon côté : les éléments trop fonçés sont automatiquement transformés en blanc avec le mode sombre et vice-versa avec le mode clair
![image](https://user-images.githubusercontent.com/51322714/98839701-1d4cb400-2403-11eb-918b-e88a89d157a1.png)
![image](https://user-images.githubusercontent.com/51322714/98840100-9ea44680-2403-11eb-8696-d74864cbdd87.png)

Concernant le dialogue de sauvegarde des listes, il y a en effet un problème avec le champ de texte qui a une couleur de fond innaproprié quand le thème sombre est activé :
![image](https://user-images.githubusercontent.com/51322714/98840302-dc08d400-2403-11eb-91c1-404b1bd482f0.png)
Ceci est un problème lié à une dépendance (JMetro) qui s'occupe du style et du design des composants de l'applications. Le problème a été rapporté [#158](https://github.com/JFXtras/jfxtras-styles/issues/158) et a été corrigé. Il ne sera plus présent dans la prochaine version de PDF4Teachers.

Cordialement
\- Clément G.

**Comment by michelwend** [comment]
Ok merci. Effectivement c'est lié à la couleur sombre. Mais je suis passé sur un fond clair et cela me va bien. C’était juste pour signalé le souci. Merci encore pour ce programme.
