### ISSUE TITLE
Empilement des notes lors de la définition de la première note

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#52]
Bonjour,
En mettant une nouvelle note par défaut elle se superpose à l'ancienne, s'il était possible de prévoir un décalage juste en-dessous, cela serait pas mal. En vous remerciant

**Comment by ClementGre** [comment]
Bonjour,
je ne comprend pas vraiment ce que vous souhaitez dire par "En mettant une nouvelle note par défaut".

Ce phénomène d'empillement peut se produire dans deux cas :
- quand vous donnez une valeur à une note et que tous ses parents se définissent pour la première fois : toutes les catégories plus la note en question vont être empillé.
- Si vous définissez plusieurs notes à la suite sans déplacer votre souris sur la page. Dans ce cas, je rapelle que "L’élément apparaît au bord gauche de la feuille. La hauteur dans la page à laquelle il apparaît correspond au dernier point de survol de la page par le pointeur de la souris." (C.f. documentation). Il est aussi possible de saisir les notes via le menu contextuel des pages (clic droit), ce qui placera la note à l'emplacement du clic.

Dans le premier cas, qui peut être perçu comme un bug, dans certaines Bêta de PDF4Teachers 1.1.0, les notes ne pouvaient pas être plaçées dans le désordre, elles étaient donc forçément les unes au dessus des autres, mais ce n'est plus le cas car ce système posait beaucoup de problème pour les élèves qui ne font pas les exercices dans le bon ordre.

Il faudrait donc interdire les éléments de notes de s'empiler dans l'axe X et Y ce qui peut être assez lourd pour l'application et ce qui peut même poser des limitations aux utilisateurs.
Le meilleur moyen serait d'ajouter automatiquement un décalage lors de la définition d'une note de type "catégorie", mais cela doit être bien fait car ce décalage ne devrait pas être appliqué dans toutes les situations.

Je vous tiens au courant
\- Clément Grennerat

**Comment by ClementGre** [comment]
Bonjour,
j'ai mis en place un système qui permet aux notes de se déplacer juste au dessus de la note enfant lorsqu’elle viens de recevoir une requête d'actualisation de la part de sa note enfant, et que sa note précédente était indéfinie.

À voir si cette fonctionnalité ne va pas poser de problèmes, mais elle fonctionne parfaitement pour le moment.
![image](https://user-images.githubusercontent.com/51322714/98879225-9e7b6980-244a-11eb-8f5a-d117cf9434ed.png)

\- Clément Grennerat
