### ISSUE TITLE
Allertes/Dialogues qui s'ouvrent sur l'écran primaire lorsque PDF4Teachers est sur l'écran secondaire

### ISSUE THREAD

**Issue by MatQ07** [ClementGre/PDF4Teachers#53]
Bonjour,

Je fais face à un petit défaut qui devient vite agacant à la longue : Quand je travaille en multi-écran (c'est le cas à la maison quand je branche mon portable sur un plus grand écran de bureau pour le confort), les messages d'alerte apparaissent sur l'écran du portable, comme je regarde l'autre écran, je ne m'en rends pas toujours compte et je me demandais si ce petit inconfort pouvait être résolu facilement.
Bien cordialement, 
MatQ07

**Comment by ClementGre** [comment]
Bonjour,
je pense que ce problème devrait pouvoir être résolu. Je vous tiens au courant.

\- Clément

**Comment by MatQ07** [comment]
Merci beaucoup

**Comment by grensv** [comment]
Bonjour,

J’ai effectivement l’habitude de ce genre d’ennui, notamment avec LibreOffice, qui a systématiquement ses fenêtres pop-up qui apparaissent sur le premier écran, alors que la fenêtre principale est sur le deuxième.

Ce qui est surprenant avec PDF4Teachers, c’est que si les fenêtres pop-up s’ouvrent bien sur le même écran que la fenêtre principale, par contre les pop-up d’avertissement / confirmation apparaissent sur le premier écran (Mac OS).

Clément, je pense qu’il doit y avoir une différence de paramétrage pour ces dernières fenêtres, qui doit pouvoir être corrigé (et donc faire mieux que LibreOffice !).

Mat, afin d’être sûr que ceci n’est pas lié à MacOS, pouvez-vous me dire sous quel OS vous utilisez PDF4Teachers ?

Vincent.

**Comment by ClementGre** [comment]
Bonjour,
il y a un paramètre dans JavaFx qui permet de définir le parent d'une fenêtre. Ce paramètre était définis pour les fenêtres annexes mais pas pour les dialogues/alertes classiques. Je pense que c'est ceci qui provoquait ce comportement particulier.

Un commit à essayé de régler ce problème en définissant un "owner" à ces dialogues ([c228e1f](https://github.com/ClementGre/PDF4Teachers/commit/c228e1fba2cf4532eb74d7525f6d86d91f9fc24f)). 
@grensv ce serait bien que tu testes si le bug est encore présent sur la dernière version .

\- Clément

**Comment by ClementGre** [comment]
Après vérifications sous OSX, le commit [c228e1f](https://github.com/ClementGre/PDF4Teachers/commit/c228e1fba2cf4532eb74d7525f6d86d91f9fc24f) a bien résolu le bug.
\- Clément
