### ISSUE TITLE
"Des erreurs sont apparues lors du rendu du document pdf"

### ISSUE THREAD

**Issue by MatQ07** [ClementGre/PDF4Teachers#54]
Bonjour,
Je génère des formulaires pdf sous libre office et demande à mes élèves de les compléter. Le problème, c'est que j'ai systématiquement l'erreur mentionnée en objet qui apparaît. Jusque-là, ce n'était accompagné que de désagréments pas trop gênants (des caractères spéciaux qui s'affichaient autrement), mais je viens de tomber sur une copie où certains champs apparaissaient vides dans pdf4teachers et pas dans mon lecteur pdf (j'étais étonné de la note d'une bonne élève). Je précise que je suis sous linux mint 20 et que je demande à mes élèves d'utiliser de préférence adobe pour remplir le formulaire (ils sont majoritairement sous windows et disposent tous d'un ordinateur sous win10 offert par le département). Y a-t-il un format de compatibilité particulière à respecter que je n'aurais pas pensé à utiliser pour éviter ce désagrément ?
Merci,
MatQ07

**Comment by MatQ07** [comment]
[301 - Activité documentaire - Le modèle de l'atome (formulaire).pdf](https://github.com/ClementGre/PDF4Teachers/files/5541124/301.-.Activite.documentaire.-.Le.modele.de.l.atome.formulaire.pdf)
Pour info, voici le doc en question

**Comment by ClementGre** [comment]
Bonjour,

comme expliqué dans #15, cette erreur est lié à une dépendance qui permet de générer la prévisualisation des documents PDF. Je n'ai pas vraiment de moyen de régler ce problème. Il faut compter sur les mises à jour de PDFBox d'Apache. 
PDFBox passera de la version 2.0.20 à 2.0.21 avec la version 1.2.1 de PDF4Teachers et il se peut que certains bugs soient réglés.

Cordialement, Clément.
