### ISSUE TITLE
Problème avec enregistrement des notes

### ISSUE THREAD

**Issue by Jean-Philippe-JtJ** [ClementGre/PDF4Teachers#57]
Bonjour,
Je tiens d'abord à vous remercier et vous féliciter pour les magnifiques perspectives de votre application. Une vraie aide pour les enseignants.
Comme vous pourrez le voir en cliquant sur le lien (vidéo) suivant:

https://drive.google.com/file/d/1z4ekIvCXSj0BmfJW8VPC7vq0PFzq8LjZ/view

après avoir ajouté des notifications à un pdf, les annotations ne sont pas enregistrées lorsque j'exporte le pdf. Est-ce un bug ou une erreur de ma part ?
Je vous remercie pour votre réponse.

MacOS 10.15.7. / PDF4Teachers 1.2.0

Javet Jean-Philippe

**Comment by ClementGre** [comment]
Bonjour,
normalement, si le fichier a une édition, cela ne devrait pas arriver. Vérifiez que le fichier pdf a bien une édition, il devrait y avoir marqué x Éléments dans l'onglet des fichiers, à côté des dossiers du document, sous son titre (cette partie n'est pas visible dans la vidéo, il faut faire défiler vers la droite).
J'ai aussi remarqué que votre fichier PDF se situe dans un dossier particulier, il s'agit certainement d'une copie de votre cloud Apple en local. Les applications tierces n'ont pas toujours accès à ce genre de dossier et cela peut causer des bugs. Je vous conseille de copier votre fichier dans votre dossier utilisateur, et de ramener l'édition sur cette copie avec Fichier -> Éditions des fichiers du même nom.

\- Clément GRENNERAT

**Comment by Jean-Philippe-JtJ** [comment]
Bonsoir,

Un grand merci pour votre réponse rapide. Vous mentionnez:

_J'ai aussi remarqué que votre fichier PDF se situe dans un dossier particulier, il s'agit certainement d'une copie de votre cloud Apple en local. Les applications tierces n'ont pas toujours accès à ce genre de dossier et cela peut causer des bugs. Je vous conseille de copier votre fichier dans votre dossier utilisateur(…)_

Le problème semble effectivement provenir de l'accès à ce dossier. Après recopie dans mon dossier utilisateur, je n'ai plus ce problème. Bravo et merci.

Jean-Philippe Javet

**Comment by ClementGre** [comment]
Il peut cependant s'agir d'un bug. Pouvez-vous me donner le chemin complet vers le dossier (qui provoquait ce problème) ainsi que le nom du fichier, pour que je puisse vérifier que ce ne soit pas un problème de caractères spéciaux utilisés dans les noms de dossier/fichier.

Clément

**Comment by Jean-Philippe-JtJ** [comment]
Si cela joue pour vous, je vous propose de répondre par mail afin de ne pas « polluer » la discussion sur GitHub. Le cas contraire, n’hésitez pas à me le faire savoir.

Voici le chemin obtenu:

/Users/jean-philippejavet/Library/Mobile Documents/com~apple~CloudDocs/Documents_ecole/Doc_HEP/HEP 2020-2021/MSMAT31-20A-Travail formatif SII (dici 23.11 à 18h00)-79056/II Lucie Jaques_448696_assignsubmission_file_/Analyse_de_tache_Ex2_Lucie_Jaques.pdf

Certes, il n’est pas très sympathique… Mais on ne s’en rend pas compte quand on manipule le fichier depuis le Finder.

Jean-Philippe Javet

**Comment by ClementGre** [comment]
Bonjour,
merci pour les informations.
Je pense pas que cela était dû à un bug, mais plutôt que vous deviez essayer d'écraser un fichier dans vos mails.

PS: répondre au mail de GitHub ajoute la réponse aussi sir GitHub.

\- Clément
