### ISSUE TITLE
Erreur de documentation du mode retranchement + fonctionnalité à revoir

### ISSUE THREAD

**Issue by ClementGre** [ClementGre/PDF4Teachers#58]
Certains enseignants souhaitent noter avec le maximum de points par défaut, puis compter les points négativement. Il faudrait donc ajouter un mode qui permettrait de modifier la manière dont les points sonts comptés.

Cette fonctionnalité est assez simple à implémenter (juste à changer la manière dont sonts calculés les totaux).

**Comment by MatQ07** [comment]
J'ai voulu essayer cette fonctionnalité mais j'y vois 2 problèmes : 

1. Il faut mettre 0 points retranchés à au moins une question de chaque groupe pour que ce soit mis à jour (et encore, les sous-notes suivantes du groupe restent à "?"
![Capture du 2021-01-17 19-11-59](https://user-images.githubusercontent.com/53429665/104852126-338e5900-58f9-11eb-9e82-3f610f14d484.png)

2. Cela n'affiche pas les points gagnés mais les points perdus

Est-il possible d'implémenter une fonction qui mette par défaut toutes les notes au max et que l'on n'ait qu'à éditer celles qui ont des points en moins ?

Merci :)

**Comment by ClementGre** [comment]
Il y a eu un problème au niveau de l'explication de cette fonctionnalité dans l'application.

Il s'agit en fait de "noter avec le maximum de points par défaut, puis compter les points négativement." comme expliqué dans le premier message de cette issue.
C'est à dire que les notes sans valeur comptent pour le maximum (et il faut qu'il y ait au moins une note entrée pour que le total soit affiché) et les notes entrées sont comptées négativement par rapport au nombre de points par défaut (le total).

Il y a en effet ce problème :
- Cela n'affiche pas les points gagnés mais les points perdus

La documentation de cette fonctionnalité sera modifiée pour la prochaine version. J'envisage aussi de la modifier pour faire ce à quoi vous vous attendiez, mais sachez que vous pouvez accorder tous les points avec un clic droit sur le total puis mettre toutes les sous notes à leur maximum.

L'utilité de cette fonctionnalité serait donc de pouvoir mettre les notes au maximum sans les afficher.

**Comment by ClementGre** [comment]
La fonctionnalité du mode retranchement a été supprimé.
À la place, il est conseillé d'utiliser la fonction du menu contextuel des notes "Attribuer tous les points", pour mettre toutes les notes à leur maximum.

Si vous ne corrigez pas avec un barème à position prédéfinie, il est maintenant possible de cacher les notes dont leur valeur est égale à leur total, pour éviter d'avoir à placer les notes sur les exercices qui ont tout les points :

![image](https://user-images.githubusercontent.com/51322714/111885382-0871c580-898d-11eb-92a0-84d51a2d3c89.png)
