### ISSUE TITLE
Installation 1.2.1 en .msi

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#60]
Bonjour,
Je viens d'installer la 1.2.1. D'abord sur la 1.2.0 mais comme cela ne fonctionnait pas j'ai supprimé cette version en passant par le désinstalleur de windows. J'ai donc effectué une nouvelle installation. Mais en sélectionnant le programme il ne se passe rien. Pourriez-vous m'aider? En vous remerciant.

**Comment by ClementGre** [comment]
Vous n'arrivez pas à exécuter l'application, essayez avec :
- Le raccourcis bureau
- Le raccourcis menu démarrer (winows 10)
- L'application dans le menu démarrer
- Le fichier .exe qui se situe dans C:\Program Files\PDF4Teachers
- Réessayer toutes ces options avec clic droit -> exécuter en tant qu'administrateur

Précisez aussi votre version Windows. Je n'arrive pas à reproduire le problème.

**Comment by michelwend** [comment]
Bonsoir,
Merci pour votre réponse. Je viens de faire les manipulations que vous proposez mais aucune ne fonctionne. Je viens de retélécharger le fichier et de refaire une installation mais cela ne fonctionne toujours pas. Je me souviens que pour la version 1.2.0 vous aviez fait une compilation particulière car j'avais également eu un souci pour cette version précédente.

**Comment by ClementGre** [comment]
D'accord. Le problème de la 1.2.0 était dû à autre chose, vous devriez d'ailleurs être capable de lancer l'application en lançant pdf4teachers.bat qui se situe dans C:\Program Files\PDF4Teachers\bin.

Ce problème est dû à la branche/version du Java Developpement Kit 15 (JDK 15) que j'utilise, ainsi que les versions des dépendances.

Je vais générer des version avec d'autres compilations de JDK et si besoin, il seras possible de repasser sous Java 14, qui ne posait pas ce problème.

Si vous voullez tester quelques solutions proposées à cette erreur : [https://windowsreport.com/exception-access-violation-windows-10/](https://windowsreport.com/exception-access-violation-windows-10/).

**Comment by michelwend** [comment]
Peut-être que la solution la plus simple est de créer un raccourci vers le .bat et de supprimer les raccourcis proposé lors de votre première réponse, et le tour est joué?

**Comment by ClementGre** [comment]
Oui, vous pouvez faire ça de votre côté mais ce n'est pas une solution envisageable à grande échelle : le .bat ouvre une console d'exécution et je ne pense pas qu'il puisse avoir un icône. De plus, je ne contrôle pas tous le processus d'installation et je ne peux pas décider de remplacer le .exe par un .bat.

**Comment by michelwend** [comment]
En attendant une autre compilation et éventuellement une version 1.2.2 , je vais faire cela car j'ai des copies à corriger. En tout cas merci pour ce superbe logiciel.

**Comment by ClementGre** [comment]
Je viens de générer une version différente de l'application, si vous pouvez tester [https://github.com/ClementGre/PDF4Teachers/releases/download/1.2.1/PDF4Teachers-Windows-1.2.1-Libertica.msi](https://github.com/ClementGre/PDF4Teachers/releases/download/1.2.1/PDF4Teachers-Windows-1.2.1-Libertica.msi)

**Comment by ClementGre** [comment]
Et voici la version sous Java 14 dans le cas où la précédente ne fonctionne toujours pas :
[https://github.com/ClementGre/PDF4Teachers/releases/download/1.2.1/PDF4Teachers-Windows-1.2.1-14.msi](https://github.com/ClementGre/PDF4Teachers/releases/download/1.2.1/PDF4Teachers-Windows-1.2.1-14.msi)

**Comment by michelwend** [comment]
Bonjour,
Je viens de faire l'installation avec [PDF4Teachers-Windows-1.2.1.msi](https://github.com/ClementGre/PDF4Teachers/releases/download/1.2.1/PDF4Teachers-Windows-1.2.1.msi) effectivement cela fonctionne. Merci encore.
