### ISSUE TITLE
Erreur de gestion des bonus en mode retranchement

### ISSUE THREAD

**Issue by MatQ07** [ClementGre/PDF4Teachers#61]
- [x] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.0%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
Les bonus sont mal gérés quand on compte les points par retranchement, ils sont gérés comme des malus

**To Reproduce**
1. Créer un barème incluant une note bonus
2. Valider l'option "compter par retranchement"
3. laisser le bonus à 0 
4. Passer le bonus à sa valeur max --> cela enlève des points au lieu d'en rajouter

**Check the console**
You can open the console window by pressing Ctrl/Cmd + Alt + C while the main window of PDF4Teachers is selected.
Please provide a screenshot of the console if it is not empty.
![console](https://user-images.githubusercontent.com/53429665/104851900-0e4d1b00-58f8-11eb-818c-b204b92dd8c2.png)

**Screenshots**
![Capture du 2021-01-17 19-11-59](https://user-images.githubusercontent.com/53429665/104851909-1311cf00-58f8-11eb-96ef-1ccf9be26c6b.png)

**Desktop (please complete the following information):**
 - Linux Mint 20 Ulyana base: Ubuntu 20.04 Kernel: 5.4.0-62-generic x86_64 bits

**Comment by ClementGre** [comment]
Fusion avec #58
