### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by oricou** [ClementGre/PDF4Teachers#62]
Linux users mostly use command lines with arguments. In our case it would be:

`pdf4teacher my_file.pdf`

or with a directory name if we are going to annotate many PDF

`pdf4teachers my_directory`

Of course there can be more options. "Help" and "version" use to be `pdf4teach -h` and `pdf4teacher -v` but since you have tools to transform images in PDF or to export students grades, they can be options too.

BTW do not user uppercase in the exec file, it is unusual (more difficult to type).

**Comment by grensv** [comment]
Thank you Olivier for these 3 suggestions. We are constrained by the Java SDK Jpackager tool we use to build .deb and other platform installers. It autogenerates the installation scripts, and the generation options are quite restrictive. We'll see what we can do, and maybe we can post-modify the Linux installation scripts if it's not too much work.
Vincent.

**Comment by ClementGre** [comment]
I think it could be possible to pass arguments from the executable to the java virtual machine, but it would be a lot of work to do what you want (execute actions which are currently gui actions, by cli).

Converting, exporting grades and exporting pdf via cli would be complicated (and would need a lot of options).
Using the gui is easier, even if we can't automate the actions. For the image conversion, you could use another cli software. (Tuto on our github wiki.)

I prefer use my time to develop others features that would be useful for more persons.

- Clément Grennerat
