### ISSUE TITLE
make executable visible under Linux

### ISSUE THREAD

**Issue by oricou** [ClementGre/PDF4Teachers#64]
The Debian package should add a link from `/opt/pdf4teachers/bin/PDF4Teachers` to `/usr/local/bin/pdf4teachers`

`ln -s /opt/pdf4teachers/bin/PDF4Teachers /usr/local/bin/pdf4teachers`

(please, do not use uppercases)

**Comment by ClementGre** [comment]
PDF4Teachers is not design to be used using Command Line Interface, that's why there is no link. (cfr #62).
