### ISSUE TITLE
Allow subfolder file search when opening folder

### ISSUE THREAD

**Issue by swirly** [ClementGre/PDF4Teachers#66]
Foremost, thanks for the grat job.

**Is your feature request related to a problem? Please describe.**
When you download moodle made assesment, you obtain a folder. In this folder, there is a subfolder for each pupil. The pdf can have the same name in each of these subfolderss.

**Describe the solution you'd like**
Actually, opening a folder does not scan subfolder. Opening a folder should have an option for opening subfolders, making pdf4teachers compatible with moodle

**Describe alternatives you've considered**
The alternative for me is to script this by myself in bash or python, adding the pupil name in front of pdf files. I can do that, but it's not that easy for a casual teacher.

**Comment by ClementGre** [comment]
I can easily add this feature for the next release.

There is multiple solutions :
  - Add an option on the File menu, to open a directory recursively.
  - Edit the way the actual "Open Folder" works, but in this case, we will not have the older option anymoremdr and maybe it will cause some other issues, when the exportation folder is into the source pdf folder for example.
  -  When opening a folder, if it contains subfolder(s) with pdf in it, a dialog asks you if you want to add the files recursively.
  - The app supports drag and drop, maybe you can select all directories in your file explorer and just drag them into PDF4Teachers' files panel. I never tested that but it should work.

I think the third is the best way to solve this, and the 4th should be a good alternative.

**Comment by ClementGre** [comment]
This feature has been addded : 
When opening a directory that contains pdf in sub-directory, the app will ask you if you want to open the files recursively.

![image](https://user-images.githubusercontent.com/51322714/111883030-6ea31c00-897e-11eb-8930-fa263b083fd0.png)

\- Clément G.

**Comment by swirly** [comment]
Great ! Thanks alot, now I can use it for moodle !
