### ISSUE TITLE
Impossible d'ouvrir les menus

### ISSUE THREAD

**Issue by Rabidax** [ClementGre/PDF4Teachers#71]
Bonjour

- [x] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
Les menus ne s'ouvrent pas correctement : ils apparaissent seulement pour la durée du clic (clignotent) et disparaisse sans que l'on puisse sélectionner un élément.

**To Reproduce**
1. Ouvrir l'app
2. Cliquer sur un menu

**Check the console**
Rien n'apparait quand j'ouvre la console et je reproduis le bug.

**Desktop (please complete the following information):**
 - OS+version: Xubuntu 20.04.2 (window manager : i3)

**Comment by MeisterLLD** [comment]
Même problème sur Arch Linux 01.04.2021 et xmonad comme gestionnaire de fenêtres.

**Comment by ClementGre** [comment]
Bonjour,

après quelques recherches, étant donné qu'à la fois I3 et Xmonad n'ont pas de barre de titre au dessus des fenêtre (avec habituellement l'icône, le nom de l'application, et les boutons minimiser, maximiser, fermer...), je pense que ce bug serait dû au gestionnaire de fenêtres qui couperait le haut de la fenêtre, comme décrit dans cette issue : [https://github.com/javafxports/openjdk-jfx/issues/546#issuecomment-741942108](https://github.com/javafxports/openjdk-jfx/issues/546#issuecomment-741942108).

Ce serait bien si vous pouviez me dire s'il s'agit de ce bug là particulièrement. Si c'est le cas, vous devriez être capable d'ouvrir les menus en cliquant tout en bas (sauf si les menus sont trop petits).
Je suppose aussi que vous n'avez aucun problème à ouvrir la page À Propos en cliquant au milieu du bouton ?
Le menu qui s'affiche/clignote devrait aussi s'afficher trop bas par rapport au dessous du bouton cliqué ?

Est-ce que les menus contextuels comme le clic droit sur un document, s'affichent eux aussi plus bas que le pointeur de la souris, ou sont-il bien aligné ?
Il y a plusieurs autres fonctions qui font référence aux coordonnées relatives à l'écran ou à la fenêtre, qui devraient être affectés, comme les pop up d'astuces, où même les dialogues et les fenêtres alternatives, mais ces changements seraient mineurs et compliqués à identifier.

Dans ce cas, il s'agirait d'un bug du gestionnaire de fenêtres et la seule chose que je puisse faire est d'ajouter de l'espace avant le menu pour ces configurations.

Sur ce rapport de bug : [https://bugs.openjdk.java.net/browse/JDK-8251240?attachmentViewMode=list](https://bugs.openjdk.java.net/browse/JDK-8251240?attachmentViewMode=list), le problème pourrait aussi venir du DPI de l'écran qui serait mal reconnu, et qui poserait aussi des problèmes de coordonnées (Je pense qu'il s'agit de ça pour vous @MeisterLLD), la résolution de #63 résoudrait donc le problème de votre côté.

Vous pouvez essayer les solutions proposées ici : 

> One possible explanation is that JavaFX is detecting Hi-DPI scaling in OpenJFX 14. If so, a possible workaround would be to set GDK_DISPLAY=1 in the environment. Another possibility is a bug in the GTK3 window toolkit (Glass) code. If so, another possible workaround would be to run with the following system property set:
> 
> $ java -Djdk.gtk.version=2

J'espère vous avoir aidé et vous remercie d'avance pour votre coopération !
Cordialement, Clément G.

**Comment by MeisterLLD** [comment]
Oui, bien vu, ça fonctionne bien si je clique tout en bas des boutons du menu. Pas de problème avec la page À propos même au milieu du bouton. Oui, les menus s'affichent un peu plus bas.

Pour les menus contextuels tout va bien.

Pour le lien avec #63, j'ai réduit ma résolution à 1920x1080 mais ça ne change rien au problème courant, donc pas sûr. Je vais répondre sur #63 

Merci à vous !

**Comment by MeisterLLD** [comment]
Oui, bien vu, ça fonctionne bien si je clique tout en bas des boutons du menu. Pas de problème avec la page À propos même au milieu du bouton. Oui, les menus s'affichent un peu plus bas.

Pour les menus contextuels tout va bien.

Pour le lien avec #63, j'ai réduit ma résolution à 1920x1080 mais ça ne change rien au problème courant, donc pas sûr. J'ai répondu sur #63 

Merci à vous !

**Comment by MeisterLLD** [comment]
Pour être plus précis, après avoir appliqué 
`gsettings set org.gnome.desktop.interface scaling-factor 2`
le problème est moindre : les menus apparaissent correctement tant que je clique sur la **moitié** basse des boutons (là où sans mise à l'échelle, il faut vraiment cliquer dans les 10% inférieurs à vue de nez).

**Comment by ClementGre** [comment]
D'accord, merci pour votre coopération !
Étant donné qu'il s'agit d'un problème interne au gestionnaire de fenêtres, il va être compliqué de résoudre ce problème dans PDF4Teachers, mais puisque l'application reconnaît bien le clic de l'utilisateur, je peut bien forcer le menu à s'ouvrir en le ré-ouvrant par exemple 50ms après un clic.
Ce problème devrait donc être résolu pour la prochaine version. Vous pourrez tester tout ça dans la pre-release de la 1.3.0.

Merci à vous, Clément G.

**Comment by ClementGre** [comment]
Bonjour,

j'ai mis en place différentes manières de résoudre ce problème.
Globalement, elles reposent toutes sur le même système : quand le menu s'ouvre, le forcer à rester ouvert durant les quelques ms qui suivent, en lui redemandant de se ré-ouvrir s'il n'y a plus de menu ouvert.

vous pourrez configurer tout ça dans les paramètres :
![image](https://user-images.githubusercontent.com/51322714/117519996-58b7dd80-af63-11eb-8769-e9185193b22a.png)

Vous devez entrer le nombre de millisecondes d'attente entre le moment où le menu est ouvert et celui où PDF4Teachers lui re-demande de s'ouvrir.

Malheureusement, je crois bien que cela dépendra de la durée de votre clic, car il se referme au moment où vous relâchez le clic.
J'ai ainsi créé des valeurs spéciales :
- Si vous réglez sur 1ms, l'application va essayer de réouvrir le menu toutes les 50ms jusqu'à 500ms (Un clic dure rarement plus de 500ms). Ceci permet d'éviter d'avoir le menu qui se ferme, puis se réouvre 200ms plus tard, en le forçant à se réouvrir dès que possible.
- Si au contraire, il n'y a besoin que de très peu de temps, vous pouvez régler sur 0, ce qui demandera au menu de se ré-ouvrir juste après le clic.

Vous me direz comment ça se passe lors de la pre-release !
Merci à vous, Clément

**Comment by ClementGre** [comment]
Bonjour,
la pre-release de la 1.3.0 a été publiée.
Je vous invite à l'installer pour tester cette "fonctionnalité", qui devrais résoudre le bug (Voir mon dernier message pour les différentes options/valeurs permettant de résoudre le bug).

Merci, Clément Grennerat.

**Comment by ClementGre** [comment]
Bonjour,
la v1.3.0 finale va paraître dans quelques jours.
Je supprime donc cette issue du projet 1.3.0 et je l'ajouterais au projet 1.3.1 ou 1.4.0 dans le cas où le bug n'est toujours pas résolu.

Merci à vous, Clément Grennerat

**Comment by MeisterLLD** [comment]
Bonjour,
Le bug est toujours présent malgré l'utilisation de l'option « Forcer les menus à bien s'ouvrir »

**Comment by MeisterLLD** [comment]
Bonjour. Avec 1ms ça fonctionne bien sous xmonad :)

**Comment by ClementGre** [comment]
Bonjour et merci pour votre réponse.

1ms correspond à ce fonctionnement :
Si vous réglez sur 1ms, l'application va essayer de réouvrir le menu toutes les 50ms jusqu'à 500ms (Un clic dure rarement plus de 500ms). Ceci permet d'éviter d'avoir le menu qui se ferme, puis se réouvre 200ms plus tard, en le forçant à se réouvrir dès que possible.

J'imagine que 0ms ne fonctionnait pas. Je pense donc que je vais proposer le fonctionnement du 1ms uniquement dans la prochaine version.

Merci !
