### ISSUE TITLE
Shortcuts / easier navigation

### ISSUE THREAD

**Issue by CardanoStakeGit** [ClementGre/PDF4Teachers#72]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
I often correct one problem at a time, so I go from one student to the next, and when I am done, I'll get to the first student again and then correct problem two. But

- PDF4Teachers doesn't remember where I was. That would make my life easier. And this is really part one of what I would love.
- PDF4Teachers doesn't do what I expect with arrowkeys and page up/page down. Or at least I don't know how to get it to work with the document which is active.
- Also would it be possible to get a way to easily jump to the next student. Like ctrl + arrow right / arrow left. (Part two of my wishlist).

**Describe the solution you'd like**
I think I already did.

**Describe alternatives you've considered**
I am using the mouse now. It works, but it's a slow and frustrating work-process. Which is a pity because I really like the program!

**Additional context**
NA

**Comment by ClementGre** [comment]
Hey @CardanoStakeGit,

that's true, the keys page next and page previous doesn't works in PDF4Teachers.
You are offering me very interesting little features to add to the app to make it perfect, and your ideas will be take in account for the next release.

Thank you for contributing,
\- Clément

**Comment by CardanoStakeGit** [comment]
I am new to GitHub. I don't know if this is the right way. But I just would like to add that I really like the program!
It is a bit annoying to keep moving my hand to the mouse, and then find the scroll-bar etc. etc. Still I actually have transistioned to use this program to correct my math homeworks.

So thanks!

And how do I use the grading system? I don't think it's not working. I just don't think I understand how it works. :)

**Comment by ClementGre** [comment]
Thank you, it's a pleasure to help you !

To use the grading scale, you can just click on the + button at the right of a grade to create a sub-grade of this grade.
You can see the video tutorial (it's in french but there is only subtitles):
[https://youtu.be/zqEOGA7G5bE](https://youtu.be/zqEOGA7G5bE)

You can also read the user manual (it's very short): Help > Load help documentation or [https://pdf4teachers.org/Documentation/](https://pdf4teachers.org/Documentation/).

**Comment by ClementGre** [comment]
Hi,

I added these features:

Now, PDF4Teachers can remember the scroll location when closing a file. This only works with documents with an edition, you do not have to save the file to save the scroll location (This is done automatically when there is an edit file).

I also added a lot of shortcuts:
- Ctrl + Backspace is considered ad Delete (For non-full keyboards and laptop)
- TAB can still be used to select the text tab or now, the paint/images tab if the text tab is already selected.
- Page Up/Down support
- End/Beginning or End/Home support
- Arrows can be used to scroll a bit vertically or horizontally
- Ctrl + Up can be used to zoom a bit
- Ctrl + Down is fitting the pages automatically in the available width (equals to the new fit button in the footer bar).
- Ctrl + Alt + Up is equals to Page Up
- Ctrl + Alt + Down is equals to Page Down
- Ctrl + Alt + Right is loading the next file in the files list
- Ctrl + Alt + Left is loading the previous file in the files list

Btw, the zoom animations options is now divided in two settings: trackpad mode and animations, so you can still have the animations other than the trackpad zoom/scroll while being on trackpad.

Thank you for your good ideas (I'm sorry I should have supported page up/down and beginning/end earlier)
\- Clément
