### ISSUE TITLE
Mixed LaTeX and plain text doesn't work with linebreak

### ISSUE THREAD

**Issue by CardanoStakeGit** [ClementGre/PDF4Teachers#73]
- [x] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
New line doesn't work well in mixed text with both math and non-math text (i.e. You have to do like this: $$x + 2 = (1) + 2 = 3$$ [enter pressed]Where you know that $$x$$ is 1.)

**To Reproduce**
1.  Write in multiline text with a bit of math included

**Desktop (please complete the following information):**
Windows 10 with PDF4Teachers 1.2.1

**Workaround - I can make it work, $$\\$$ will give me a new line. It's not pretty, but it works. I would like very much if you could do it prettier though. :)

**Comment by ClementGre** [comment]
Hi,
You are right, this is an issue, in the next release, any line break will be replaced by $$\\$$ in the plain text part or \\ in the LaTeX part (unless line break is useful in LaTeX).

\- Clement

**Comment by Butanium** [comment]
I have the same issue and when I try the ``$$\$$`` it gets worst
![image](https://user-images.githubusercontent.com/55806347/115902487-c5f74900-a462-11eb-9e5b-60a623ef5201.png)
$$\sqrt{x}$$ en - $$\infty $$ ... 
Et puis il fallait continuer, 
et puis le ln est négligeable tous comme l'exponantielle...

becomes :


![image](https://user-images.githubusercontent.com/55806347/115902400-b37d0f80-a462-11eb-9b0c-1d7ffc27bc91.png)
$$\sqrt{x}$$ en - $$\infty $$ ... 
Et puis il fallait continuer, ``$$\$$``
et puis le ln est négligeable tous comme l'exponantielle...

**Comment by ClementGre** [comment]
That's strange, usually, ``et puis le ln est négligeable tous comme l'exponantielle...`` should be considered as text and not LaTeX because it is not between ``$$``. I gonna fix this bug for the next release, thank you guys for reporting the issue.

While waiting for the next release, the best way is to use multiple text elements, one for each line.

Thank you, Clément G.

**Comment by ClementGre** [comment]
Hi,
I replaced all \n in LaTeX part to " \\ "
and all \n in plain text part to "} \\ \text{"

and this seems to work well with all kinds of line break.

Thank you for having reported this issue !
\- Clément G.
