### ISSUE TITLE
Possibilité de définir la valeur des notes à la souris

### ISSUE THREAD

**Issue by BGonard** [ClementGre/PDF4Teachers#75]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Lorsque l'on clique droit pour ajouter une note, il est possible de mettre directement les points maximaux en cliquant sur le nom de la question. On peut ensuite choisir la note minimale en double-cliquant dessus. Mais on ne peut avec la souris choisir les notes intermédiaires.

**Describe the solution you'd like**
Il serait agréable que toutes les alternatives de notes se présentent. Par exemple pour une note sur 2 les cases 0 0,5 1 1,5 2 apparaîtront et on cliquera sur celle que l'on choisit. 
Il faudra avoir défini, dans les barème, le pas choisi (ou 0,5 par exemple). 

On pourrait, au lieu des cases, faire apparaître une ligne graduée de 0 à 2. 

**Additional context**
Il serait souhaitable aussi selon moi d'ajouter la cas "N" ou "NT" pour "non traité", afin de signaler les questions non traitées, et dans ce cas la note ne sera pas affiché. Cela éviterait, pour une mauvaise copie où 4 questions de suite n'ont pas été traitées, d'afficher 0/1 0/1 0/1 0/1.

**Comment by ClementGre** [comment]
Bonjour,

j'ai rajouté cette fonction qui permet de choisir la note à la souris. Il faut faire un clic droit sur le menu contextuel de la note, ici :
![image](https://user-images.githubusercontent.com/51322714/117591717-e37b1280-b0f2-11eb-8f31-a3bc590b37c6.png)

Le menu suivant s'ouvrira alors, dans lequel vous pourrez choisir la note désiré, avec la précision voulue :
![image](https://user-images.githubusercontent.com/51322714/117591708-da8a4100-b0f2-11eb-9555-cdef3763f8db.png)

Concernant le NT, comme déjà expliqué, il faudrais faire beaucoup de changements pour au final pas grand chose car l'on peut laisser la case vide pour les questions non traités.

\- Clément

**Comment by DegrangeM** [comment]
> Bonjour,
> 
> j'ai rajouté cette fonction qui permet de choisir la note à la souris. Il faut faire un clic droit sur le menu contextuel de la note, ici :
> ![image](https://user-images.githubusercontent.com/51322714/117591717-e37b1280-b0f2-11eb-8f31-a3bc590b37c6.png)
> 
> Le menu suivant s'ouvrira alors, dans lequel vous pourrez choisir la note désiré, avec la précision voulue :
> ![image](https://user-images.githubusercontent.com/51322714/117591708-da8a4100-b0f2-11eb-9555-cdef3763f8db.png)
> 
> Concernant le NT, comme déjà expliqué, il faudrais faire beaucoup de changements pour au final pas grand chose car l'on peut laisser la case vide pour les questions non traités.
> 
> - Clément

Est-ce normal que cette fonctionnalité ne soit pas présente dans la pré release ? Merci.

**Comment by ClementGre** [comment]
Bonjour,
elle est bien présente dans la pre-release, il faut faire un clic droit sur le nom de la note, dans son menu contextuel, comme expliqué dans mon message précédent.
La fonctionnalitée fonctionne de mon côté.

\- Clément
