### ISSUE TITLE
Proposer de ramener la note finale sur 20 par exemple

### ISSUE THREAD

**Issue by BGonard** [ClementGre/PDF4Teachers#76]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Mon barème est toujours sur un nombre exotique, genre 92,5 points. Ensuite je fais une règle de trois pour le mettre sur 20. Par exemple je décide de le compter sur 80 donc je divise par 4. 

**Describe the solution you'd like**
J'aimerais qu'il existe la possibilité de mettre le total sur lequel on compte la note (ici 80) et le total auquel on souhaite se ramener (ici 20) et alors la règle de trois est appliquée, et le total sur 20 est affiché au début de la copie (avec le /20). 

**Describe alternatives you've considered**
Il faudrait alors choisir le style de la note finale.

**Comment by ClementGre** [comment]
Bonjour,

cette fonctinnalité a bien été développée pour la prochaine version (1.3.1).
Dans la cellule du Total du barème est maintenant inclut un nouveau champ pour ramener la note sur x.

La nouvelle valeur et le nouveau total sontaffichés sur le document (voir image).
Ceci fonctionne aussi lors de l'exportation du barème sur d'autres copies, et de l'exportation des notes en .csv.

![Screenshot_20210904_150801](https://user-images.githubusercontent.com/51322714/132095598-5d9abc19-ce90-4227-8ac1-b697aaa72186.png)

Merci à vous !
\- Clément G.
