### ISSUE TITLE
Menu du clic droit : Ne proposer que les annotations favorites

### ISSUE THREAD

**Issue by BGonard** [ClementGre/PDF4Teachers#77]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Le clic droit fournit les annotations les plus courantes, mais pour certaines comme "Non" c'est inutile.

**Describe the solution you'd like**
Je voudrais choisir les annotations qui apparaissent lorsque l'on clique droit sur la copie. Je préfèrerais que ce suit les favorites plutôt que les plus courante, et que l'on puisse les ordonner par glisser-déposer. 

**Describe alternatives you've considered**
Je ne trouver pas que les annotations "dans ce document" soient très utiles.

**Additional context**
Le checkmark est le plus utile je trouve, je voudrais qu'il apparaisse systématiquement, avec possibilité de le personnaliser.

**Comment by ClementGre** [comment]
Bonjour,
étant donné que les annotations proposées dans le menu du clic droit sont générées à chaque fois que le menu est demandé, il serait compliqué de personnaliser cette liste. Concernant la liste des éléments favoris et précédent, on ne peut pas les modifier à la main car elles sont automatiquement triées selon le mode de tri choisit.

La seule chose que je peut faire serait de proposer dans les paramètres de personnaliser le mode de tri utilisé pour générer cette liste qui actuellement propose les éléments les plus utilisés des favoris et précédents. Je peut aussi proposer de ne proposer que des éléments favoris et non pas à la fois les favoris et précédents.

Concernant le $$checkmark, il sera proposé en tant qu'image vectorielle dans le menu du clic droit, accompagné des nouvelles formes de la 1.3.0.

Merci de votre retour !
Cordialement, Clément

**Comment by ClementGre** [comment]
Je ferme cette issue car ces fonctionnalités ne sont pas forcément très utiles.
