### ISSUE TITLE
Icône de manipulation du PDF trop petites. Permutations des pages fastidueuses.

### ISSUE THREAD

**Issue by BGonard** [ClementGre/PDF4Teachers#78]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Des icônes rouges sur fond blanc apparaissent en haut à droite des pages pour donner la possibilité de permuter les pages, de les faire pivoter, de les supprimer etc. 
Mais si on dézoome elles deviennent très petites. 

Et quand un document est très désordonné c'est très long de tout reclasser juste avec la permutation avec la page suivante ou précédente. 

**Describe the solution you'd like**
Il faudrait que les icônes gardent une taille fixe. 
Il serait souhaitable que les pages soient permutables par simple glisser-déposé sur une vue d'ensemble.

**Comment by ClementGre** [comment]
Bonjour,

désormais, les boutons gardent la même taille peu importe le niveau de zoom.

Par ailleurs, il est désormais possible de déplacer les pages par glissé déposer quand le zoom est inférieur à 40%.
(J'ai aussi ajouté quelques animations lors de la rotation et lors du déplacement de pages pour plus de fluidité 👍)

J'espère que ces nouvelles fonctions vous satisferont !
\- Clément G.
