### ISSUE TITLE
Impossible d'exporter un fichier - PDF4Teachers

### ISSUE THREAD

**Issue by bhaddou** [ClementGre/PDF4Teachers#79]
Bonjour,

après avoir annoté et noté une copie, j'essaie de l'exporter à l'aide de la fonction Exporter (Ctrl E)
Une fois lancé l'export, j'ai un message d'erreur suivant :
C:\Users\Baptiste\Desktop\Enseignement\Prépa\TPC 2020-2021\Devoirs\DS6\DS6 Amaury.pdf (Accès refusé)
(Il s'agit du chemin initial du fichier)

Avez-vous déjà rencontré ce type de problème (accès refusé ?)

Merci par avance pour votre réponse et pour votre travail dans ce logiciel, que j'espère pouvoir continuer à utiliser (si j'arrive à exporter, bien sûr...)
Bonne journée,
B. Haddou

**Comment by bhaddou** [comment]
Problème réglé (ou tout du moins identifié), c'est mon antivirus Avast qui pose problème

**Comment by ClementGre** [comment]
Duplicate #5
