### ISSUE TITLE
Ajouter des contrôles du zoom à la souris (Slider + Ajuster la largeur)

### ISSUE THREAD

**Issue by lbaille20** [ClementGre/PDF4Teachers#80]
Bonjour
Tout d'abord, félicitations pour l'outil !
Pour l'instant, il me ravit et remplit toutes les exigences !
Je voulais signaler ici que le CTrl+Scrol ne fonctionne pas bien sur ma machine (ou avec ma souris ?)
Du coup, un bouton +/- serait peut-être utile ?
Ceci étant, ce problème ne tempère pas mon enthousiasme pour l'outil.
Bien cordialement
M. BAILLE

**Comment by lbaille20** [comment]
Peut-être un bouton "afficher à la largeur de la page" ?

**Comment by lbaille20** [comment]
Ajout : de mon usage personnel, j'aurais usage d'un cadre pour une appréciation générale, exportable (mais il est vrai que l'on peut exporter toutes les annotations, donc il est possible m'organiser pour faire ce que je souhaite sur ce point, à partir du .csv)

**Comment by ClementGre** [comment]
Bonjour,
Il était déjà prévu d'ajout un "slider" pour régler le niveau de zoom, mais l'idée d'ajouter un bouton "ajuster à la largeur de l'application" est intéressante et je veillerais à mettre ceci en place pour la prochaine version.

Concernant l'exportation de l'appréciation dans le csv, ceci demanderait de créer un nouveau type d'élément, et ce serait donc trop compliqué à faire pour le moment, mais oui, si vous exportez chaque copie dans un csv différent, vous pouvez récupérer les commentaires directement dans le csv.

\- Clément G.

**Comment by ClementGre** [comment]
Bonjour,
la fonctionnalité d'adapter le zoom à la largeur a bien été ajouté à l'application (bouton dans la barre du bas).
Le zoom est aussi adapté à la largeur par défaut lors de l'ouverture d'un document.
![image](https://user-images.githubusercontent.com/51322714/117554161-0afaae00-b013-11eb-8af4-12eb56c44a44.png)

MErci à vous, Clément G.
