### ISSUE TITLE
Possibilité d'entourer ou de mettre des flèches ?

### ISSUE THREAD

**Issue by RomainBondil** [ClementGre/PDF4Teachers#82]
Bonjour
bravo à vous et grand merci pour votre logiciel. Je débute avec, et je n'ai pas encore corrigé de copies avec barèmes, mais c'est une fonctionnalité qui m'intéresse beaucoup.
 Je me demandais s'il était possible d'entourer ou de souligner des parties d'une copie (même avec de simples ovales). Pour l'instant je fais juste des flèches en latex $$\uparrow$$ ou autre pour pointer vers une zone, mais cela me semble vraiment une fonctionnalité 
Encore félicitations
Romain Bondil
enseignant en prépa à Montpellier

**Comment by RomainBondil** [comment]
Bon je viens de voir que c'est une fonctionnalité en cours de développement, désolé du bruit..
j'espère aussi qu'il y aura un Ctrl-Z...

**Comment by ClementGre** [comment]
Bonjour,
en effet, c'est une fonctionnalité en cours de développement.
Concernant le Ctrl+Z, ce serait assez compliqué de mettre ceci en place, mais je vais y réfléchir.

\- Clément

**Comment by RomainBondil** [comment]
Merci beaucoup de votre réponse.
En fait le Ctrl+Z me serait surtout utile quand je fais un double clic involontaire qui recopie une deuxieme fois la même annotation, et que je suis obligé d’effacer avec la touche d’effacement lettre par lettre.
Mais peut-être y a t il une méthode moins maladroite…
rb

**Comment by ClementGre** [comment]
En effet, il y a d'autres moyens :
- clic droit sur l'élément > supprimer,
- bouton supprimer sous le champ de texte,
- touche suppr/delete de votre clavier.

Clément
