### ISSUE TITLE
Annotations textuelles : pouvoir ajouter en remplaçant l'élément sélexionné

### ISSUE THREAD

**Issue by omangeat** [ClementGre/PDF4Teachers#84]
- [ ] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
quand je commence à taper un texte et qu'ensuite je viens sélectionner un élèment en surbrillance dans une des listes, les deux s'affichent sur la page (le début du texte + le texte complet)

Le problème n'existe pas si on choisit l'élément de la liste au clavier

**Comment by omangeat** [comment]
Je ne suis pas sur que ce soit vraiment un problème

**Comment by ClementGre** [comment]
En effet, si vous souhaitez remplacer l'élément actuel, il ne faut pas cliquer sur l'élément, mais utiliser les flèches du clavier puis entrée.

Je peut cependant ajouter un moyen de faire ceci à la souris, par exemple avec Alt+Clic.

\- Clément

**Comment by ClementGre** [comment]
Il est désormais possible avec Ctrl + Clic ou Cmd + Clic de remplacer l'élément sélexionné par celui de la liste.

- Clément.
