### ISSUE TITLE
Meilleure proposition du dossier de destination lors de la conversion

### ISSUE THREAD

**Issue by lnain07** [ClementGre/PDF4Teachers#85]
Bonjour, et tout d'abord félicitations et merci pour ce travail.
Serait-il possible que pour le dossier de destination de conversion des pdf il y ait une suggestion de même dossier que celui contenant les fichiers à convertir ?
Merci

**Comment by ClementGre** [comment]
Bonjour,
généralement, on souhaite que les fichiers convertis arrivent dans le même dossier que celui des documents ouverts, c'est pourquoi le dossier par défaut va rester celui des documents ouverts dans l'onglet des fichiers.
Cependant, s'il n'y a pas de document dans cette liste, PDF4Teachers proposera maintenant le même chemin que le chemin source.
(Vous pouvez autrement faire un copié collé entre les deux champs de texte).

Pour résumer :
Le chemin source est toujours sauvegardé entre deux ouvertures de la fenêtre, il proposera donc toujours la dernière valeur entrée.
Le chemin de destination propose le chemin du premier fichier de la liste des documents ouverts. Si la liste est vide, il proposera la même valeur que le chemin source.

\- Clément
