### ISSUE TITLE
Offer system fonts / Allow to add custom fonts

### ISSUE THREAD

**Issue by MeisterLLD** [ClementGre/PDF4Teachers#86]
- [x] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [x] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
On my Linux (non deb) version, only some fonts are here (OpenSans, Jost, Lato Black...) but for instance Gentium, Symbola, Mononoki Nerd Font, Noto Emoji which are all present on my system (and for instance in LibreOffice Writer) are not in PDF4Teachers's font list. Fonts already present are ok, but I would like for instance the emoji support of Symbola. For instance right now in PDF4Teachers no font can display the warning sign emoji ⚠️.

**To Reproduce**
1. Install a new font and do fc-cache
2. Check if font is present in PDF4Teacher's list

**Desktop (please complete the following information):**
 - OS+version: [e.g. Arch Linux last version]

**Comment by ClementGre** [comment]
Hi @MeisterLLD,
currently, PDF4Teachers does not support system fonts, but only fonts that I chose myself, because when exporting a document, I have to add the .ttf file to the PDF, and it was too complicate to get a system font as a .ttf file.

I will see if I can add a support for taking in account the system fonts, and in case it is too hard, I will allow the users to add custom fonts.

Thank you, Clément

**Comment by MeisterLLD** [comment]
Thanks, I understand why this might be difficult. Maybe just adding a font with a good emoji support would be enough for most users ?

**Comment by ClementGre** [comment]
Hi @MeisterLLD,
maybe I spent too much time on this, but now, PDF4Teachers can fully read system fonts.
There could still be some issues, like the source folders, on Linux, it is:
> ~\.fonts
> /usr/share/fonts/truetype
> /usr/share/fonts/TTF

Also, not all types of fonts are supported, only TTF and TTC. Moreover, fonts have to have a header table (and not all have one).

Fonts will be indexed and then cached. to reload the fonts, you will need to go to the settings.
You will be able to test this feature during the 1.3.0 pre-release.

Thank you, Clément.

**Comment by ClementGre** [comment]
By the way, not all emojis fonts are supported. On Windows, Simbol does not works right.
Moreover, colored fonts are not supported so emojis will have a bad look.

With the font Twitter Color Emoji, you can get something like this:
![image](https://user-images.githubusercontent.com/51322714/116826260-5c58f800-ab50-11eb-9789-c0280ea3ad84.png)
