### ISSUE TITLE
v1.2.2, informations sur la 1.3.0

### ISSUE THREAD

**Issue by SebCanet** [ClementGre/PDF4Teachers#87]
Bonjour,
afin de montrer l'interface à d'autres profs et de les aiguiller vers ta solution TRES prometteuse, serait il possible de faire une release avec les nouvelles fonctions graphiques, ce qui me semble être la grosse amélioration déjà développée, en attendant une v1.3 ?

Pas mal de collègues avaient particulièrement apprécié le projet mais étaient restés sous des logiciels de PDF classiques (Adoce Acrobat, X-Change PDF Viewer, etc) pour corriger des copies en annotant par des dessins faits à la souris.

Si cette idée est saugrenue, merci de clore le ticket sans pb. Merci pour tout ce boulot !

**Comment by ClementGre** [comment]
Bonjour @SebCanet,
malheureusement, les fonctionnalités de dessin vectoriel n'ont pas encore été développées.
J'ai pour l'instant développé presque toutes les fonctions communes aux images et aux images vectorielles ainsi que toute la base permettant d'afficher des images et les listes d'images favories et gallerie.
Je pense être à moins de 50% du développement de ces fonctionnalités.

Par ailleurs, la 1.2.1, ayant très bien fonctionné (avec le confinement), a généré beaucoup de retours, dont une grande quantité de bugs que je tiens à résoudre avant la sortie de la 1.3.0 (En effet, je considère cette version comme une version majeure, qui ajoute beaucoup de fonctionnalitées.).

Vous pouvez suivre l'avancement du développement à ce lien : [https://github.com/ClementGre/PDF4Teachers/projects/3](https://github.com/ClementGre/PDF4Teachers/projects/3).

J'estime donc que cette version sera publié soit début juillet, soit en Septembre/Octobre. (Ma personalité perfectionnaliste ne m'aide pas à faire vite...)

Je souhaiterais de plus faire une pre-release (une béta) de 1 ou 2 semaines pour résoudre les bugs que ces fonctions auraient pu générer, et ainsi proposer en version finale un système qui fonctionne parfaitement. (Quelques "issues" ont elles aussi besoin d'une pre-release pour faire des tests assez techniques).

- Clément G.

**Comment by SebCanet** [comment]
Merci des détails. Bon courage !
