### ISSUE TITLE
Mauvais nom de dossier dans le menu Windows 10

### ISSUE THREAD

**Issue by fralbert** [ClementGre/PDF4Teachers#88]
Bonjour,

Il y a une erreur pour le raccourci du menu Démarrer sous Windows 10 (pas testé 7 ou autre).
Installation faite avec le msi de la 1.2.1.

Celui-ci va dans un dossier qui s'appelle :
--file-associations association-win.properties

![PDF4Teachers](https://user-images.githubusercontent.com/22766601/117409373-693f6800-af11-11eb-9663-4452a5921c97.png)

**Comment by ClementGre** [comment]
Bonjour,
il s'agissait en effet d'un bug dans le script de build.
Le problème a été résoulu.

Merci à vous, Clément G.
