### ISSUE TITLE
écriture manuscrite : bug de reprise du trait

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#97]
**Etapes pour reproduire**
1. Activer le mode écriture manuscrite et écrire un truc
2. Cliquer sur le bouton stylo (à côté du bouton règle). 
3. Cliquer à nouveau sur le bouton stylo
4. Écrire un truc
5. Un trait va être tracé entre la fin du tracé de l'étape 1 et le début du tracé de l'étape 4

**Screenshots**
![image](https://user-images.githubusercontent.com/53106394/122305513-53a56100-cf07-11eb-9c4c-decc7430f5ef.png)

**Desktop (please complete the following information):**
 - Windows 1.3.0-pre1

**Comment by ClementGre** [comment]
Bonjour,

Ce bug est courrant et il peut en effet arriver dans certains cas (je croyais l'avoir réglé complètement).
Ce cerait parfait si vous pouriez décrire les actions nécessaire pour le reproduire un peut plus clairement car je ne peux par le reproduire pour le moment :

https://user-images.githubusercontent.com/51322714/122306961-a0b51300-cec6-11eb-8204-73e5e8055810.mov

Merci à vous,
Clément Grennerat

**Comment by DegrangeM** [comment]
Je fais exactement la même chose.


https://user-images.githubusercontent.com/53106394/122599530-d1d04780-d06e-11eb-8d95-aa8bae032a0d.mp4

**Comment by DegrangeM** [comment]
> C'est assez étrange car ce bug ne se produit pas à chaque fois : je suppose que vous pouvez bien dessiner plusieurs courbes séparés, sans qu'elles se lient entre elles.

Le problème apparait à chaque fois que je suis exactement ces étapes. En revanche si entre l'étape 3 et 4 je clic n'importe où ailleurs avant de dessiner, ça fonctionne. Comme si le premier clic après la pression du bouton était mangé.

**Comment by ClementGre** [comment]
Merci, je marque cette issue comme "duplicate" de #98.
