### ISSUE TITLE
Écriture manuscrite : clic manqué lorsque un popup de tutoriel est ouvert => rendu du dessin impossible.

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers#98]
**Etapes pour reproduire**
1. Activer le mode écriture manuscrite et écrire un truc
2. Appuyer sur le bouton corbeille
3. Réactiver le mode écriture manuscrite et tenter d'écrire un truc
4. Rien ne va s'afficher, il faut cliquer sur le champs texte contenant le chemin SVG et le vider afin de pouvoir réécrire

**Desktop (please complete the following information):**
 - Windows 1.3.0-pre1

**Comment by DegrangeM** [comment]
Même soucis via le bouton à gauche du bouton corbeille et en sélectionnant New Freeform Line

**Comment by ClementGre** [comment]
Bonjour,

je n'arrive pas à reproduire ce problème.
Est-ce que vous pouvez détailer la procédure de reproduction un peut plus précisément ?

Est-ce que vous pouvez aussi m'envoyer une capture d'écran de la console de l'application pour vérifier que celà n'est dû à aucune erreur interne (Ctrl+Alt+C) ?

Merci, Clément G.

**Comment by DegrangeM** [comment]
La console indique bel et bien des messages liés au bug:
![image](https://user-images.githubusercontent.com/53106394/122599687-09d78a80-d06f-11eb-8787-2905683d7958.png)

Je vais voir pour faire une vidéo

**Comment by DegrangeM** [comment]
https://user-images.githubusercontent.com/53106394/122600114-9bdf9300-d06f-11eb-805b-627b5bc27f22.mp4

**Comment by ClementGre** [comment]
Bonjour,
merci pour la vidéo et la capture d'écran, j'ai pu identifier le problème : PDF4Teachers détecte bien le mouvement de glissé (drag), mais il ne capte pas le clic, c'est pourquoi il n'arrive pas à afficher le dessin : il ne connais pas les coordonnées du point initial. Il s'agit du même problème dans #97, où le trait est prolongé au lieu de reprendre à un nouveau point.

C'est assez étrange car ce bug ne se produit pas à chaque fois : je suppose que vous pouvez bien dessiner plusieurs courbes séparés, sans qu'elles se lient entre elles.

Quel outil utilisez-vous pour dessiner (tablette graphique, écran tactile, souris) ?
Il doit s'agir d'un problème de configuration de votre tablette/écran, qui n'émet pas toujours un signal de clic.
Je peut aussi essayer d'améliorer certains points dans PDF4Teachers (Meilleur support du tactile, prévoir que l'évènement de clic n'est pas toujours présent).

Je vais donc aussi essayer d'actualiser la pre-release Windows en apportant quelques modifiations.

Merci à vous, Clément Grennerat

**Comment by DegrangeM** [comment]
> Quel outil utilisez-vous pour dessiner (tablette graphique, écran tactile, souris) ?

Une simple souris.

**Comment by ClementGre** [comment]
Ceci est bien étrange, d'autant plus que le bug se faisait avec une simple souris.

Je vais tout de même mettre en place un système de prévention pour éviter que ces problèmes de points manqués ne se reproduisent (le bug #97 ne poura pas être résolu, mais celui-ci oui).

Merci !

**Comment by DegrangeM** [comment]
Je pense avoir des pistes sur la vraie origine du bug. J'ai supprimé le dossier pdf4teacher du dossier appdata et le bug est revenu.

Je soupçonne qu'il soit lié aux popup de tutoriel qui s'affiche lors du lancement du logiciel.

**Comment by DegrangeM** [comment]
Oui c'est ça je confirme : lorsque l'on clic sur le bouton stylo, la popup tuto s'affiche et lorsque l'on clic pour reprendre le dessin, cela ferme la popup et cette action "mange" l'action du clic qui n'est alors pas détecté par l'action dessin. Si je ferme la popup, celle-ci arrête de s'afficher et le bug disparait.

**Comment by ClementGre** [comment]
D'accord, merci beaucoup, j'arrive bien à reproduire le bug de mon côté.
C'est bien l'action de re-sélectionner la fenêtre principale de l'application qui pose ce problème.

Je vais voir comment résoudre ce problème.
Merci encore, Clément Grennerat
